<?php
/**
 * The question templates in French. Keyed by the English template's code;
 * see install/mission-templates-all.php for how the two halves are joined.
 *
 * GENDER AND ARTICLES
 *
 * One sentence is written for a dozen different words, so the words are chosen
 * to fit it: every creature and every object is masculine plural, every
 * container feminine, and each place carries its own preposition - dans le pre,
 * sur la plage. The sentence never has to guess which word turned up.
 *
 * The reading and grammar questions are not translations: rhymes, plurals and
 * past tenses only exist inside one language, so those are written fresh here.
 */

$creatures = ['lapins', 'chatons', 'chiots', 'canetons', 'écureuils', 'hérissons',
              'poissons', 'dauphins', 'pingouins', 'renards', 'hiboux', 'crapauds'];

$things = ['boutons', 'cailloux', 'crayons', 'autocollants', 'ballons', 'bonbons',
           'coquillages', 'glands', 'rubans', 'timbres', 'cubes', 'dés'];

$places = ['dans le pré', 'dans le jardin', 'près de la mare', 'dans la forêt',
           'dans la cour', 'sur la plage', 'dans le verger', 'dans la cabane',
           'dans la grange', 'au bord du bassin'];

$names = ['Léa', 'Hugo', 'Chloé', 'Noé', 'Camille', 'Théo',
          'Sana', 'Milo', 'Bella', 'Pedro', 'Ada', 'Nour'];

$containers = ['boîtes', 'caisses', 'corbeilles', 'bassines', 'trousses', 'valises', 'poches'];

$treats = ['biscuits', 'raisins', 'sandwichs', 'gâteaux', 'muffins', 'bonbons'];

return [

    // ----------------------------------------------------------------- MATHS
    'math-add' => [
        'name'    => 'Additionner',
        'pattern' => 'Il y a {a} {creature} {place}. {b} autres arrivent. Combien y a-t-il de {creature} maintenant ?',
        'answer'  => '{a+b} {creature}',
        'patterns' => [
            '{b} {creature} de plus arrivent {place}, où il y en avait déjà {a}. Combien maintenant ?',
            'Compte les {creature} {place} : {a} au départ, puis {b} de plus.',
            'D’abord {a} {creature} {place}, puis {b} de plus. En tout ?',
            'Additionne : {a} {creature} {place} et {b} qui viennent d’arriver.',
            'Il y avait {a} {creature} {place}. Maintenant il y en a {b} de plus. Ça fait combien ?',
            'Combien de {creature} y a-t-il {place} quand {b} rejoignent les {a} déjà là ?',
            '{a} et {b} de plus : ça fait combien de {creature} ?',
        ],
        'hint'    => 'Compte-les tous ensemble.',
        'lists'   => ['creature' => $creatures, 'place' => $places],
    ],
    'math-sub' => [
        'name'    => 'Soustraire',
        'pattern' => '{who} a ramassé {a} {thing}. {who} en donne {b}. Combien lui en reste-t-il ?',
        'answer'  => '{a-b} {thing}',
        'patterns' => [
            '{who} avait {a} {thing} ce matin et en a déjà donné {b}. Combien lui en reste-t-il ?',
            'Sur {a} {thing}, {who} en donne {b} à un ami. Combien en garde-t-il ?',
            '{who} donne {b} de ses {a} {thing}. Combien en reste-t-il ?',
            'Enlève {b} à {a} {thing}. Combien en reste-t-il à {who} ?',
            '{who} avait {a} {thing} au départ. Il en manque {b}. Combien maintenant ?',
            'Sur {a} {thing}, {b} disparaissent. Combien en reste-t-il ?',
            '{a} {thing}, moins les {b} que {who} a donnés. Combien ?',
        ],
        'hint'    => 'Pars de ce que tu avais et enlève le reste.',
        'lists'   => ['thing' => $things, 'who' => $names],
    ],
    'math-count-back' => [
        'name'    => 'Compter à rebours',
        'pattern' => 'Pars de {a} et compte {b} en arrière. Où arrives-tu ?',
        'answer'  => '{a-b}',
        'patterns' => [
            'Compte {b} en arrière à partir de {a}. Quel nombre dis-tu en dernier ?',
            'Tu es sur {a} et tu fais {b} pas en arrière. Où t’arrêtes-tu ?',
            '{a}, et {b} pas en arrière. Quel nombre est-ce ?',
            'Dis le nombre auquel tu arrives en reculant de {b} depuis {a}.',
            'Enlève {b} à {a} en comptant à l’envers.',
            'Commence à {a}. Recule un par un, {b} fois. Où es-tu ?',
            '{a} moins {b} : compte-le à l’envers à voix haute.',
        ],
        'hint'    => 'Sers-toi de tes doigts si ça aide.',
    ],
    'math-double' => [
        'name'    => 'Le double',
        'pattern' => '{who} a {a} {thing} et en trouve exactement autant une deuxième fois. Combien en a-t-il maintenant ?',
        'answer'  => '{a+a} {thing}',
        'patterns' => [
            '{who} a {a} {thing}. Double cette quantité. Ça fait combien ?',
            'Il y a {a} {thing} sur la table et autant dans la boîte. Combien en tout ?',
            'Deux fois {a} {thing} : combien ?',
            '{who} trouve encore {a} {thing}. Quel est le total ?',
            '{a} {thing} dans une main, {a} dans l’autre. Combien en tout ?',
            'Double {a}. Qu’est-ce que ça donne ?',
            '{a} {thing} plus autant encore. Combien ?',
        ],
        'hint'    => 'Le double, c’est la même quantité deux fois.',
        'lists'   => ['thing' => $things, 'who' => $names],
    ],
    'math-mul' => [
        'name'    => 'Des paquets de',
        'pattern' => 'Il y a {a} {container} et chacune contient {b} {thing}. Combien de {thing} en tout ?',
        'answer'  => '{a*b} {thing}',
        'patterns' => [
            '{a} {container}, {b} {thing} dans chacune. Ça fait combien de {thing} ?',
            'Chacune des {a} {container} contient {b} {thing}. Calcule le total.',
            'Combien de {thing} y a-t-il dans {a} {container} de {b} ?',
            '{b} {thing} dans une {container}. Combien dans {a} ?',
            'Multiplie : {a} fois {b} {thing}.',
            'Il y a {a} {container}. Chacune contient {b} {thing}. Compte-les toutes.',
            '{a} fois {b} {thing} : quel est le total ?',
        ],
        'hint'    => 'Compte les paquets, puis ce qu’il y a dans chacun.',
        'lists'   => ['container' => $containers, 'thing' => $things],
    ],
    'math-div' => [
        'name'    => 'Partager',
        'pattern' => 'Partage {a} {treat} équitablement entre {b} amis. Combien chacun en reçoit-il ?',
        'answer'  => '{a/b} {treat} chacun',
        'patterns' => [
            '{b} amis se partagent {a} {treat} à parts égales. Combien chacun en a-t-il ?',
            'Partage {a} {treat} en {b} tas égaux. Combien y en a-t-il dans un tas ?',
            '{a} {treat} partagés entre {b}. Combien chacun ?',
            'Combien de {treat} reçoit chacun des {b} amis s’il y en a {a} ?',
            'Divise {a} {treat} par {b}.',
            'Il y a {b} assiettes et {a} {treat}. Mets-en autant dans chacune.',
            '{a} {treat}, {b} enfants, la même chose pour tous. Combien ?',
        ],
        'hint'    => 'Distribue-les un par un, comme des cartes.',
        'lists'   => ['treat' => $treats],
    ],
    'math-missing' => [
        'name'    => 'Le nombre manquant',
        'pattern' => '{who} avait des {thing}, en a reçu {b} de plus, et en a maintenant {c}. Combien en avait-il au départ ?',
        'answer'  => '{c-b} {thing}',
        'patterns' => [
            '{who} a maintenant {c} {thing}, après en avoir reçu {b}. Combien en avait-il avant ?',
            'On a donné {b} {thing} à {who}, ce qui fait {c} en tout. Combien en avait-il au départ ?',
            '{who} finit avec {c} {thing} après en avoir reçu {b}. Avec combien a-t-il commencé ?',
            'Quelque chose plus {b} fait {c}. C’était combien ?',
            '{who} a maintenant {c} {thing}. {b} sont nouveaux. Combien sont anciens ?',
            'Remonte : {c} {thing} maintenant, dont {b} arrivés aujourd’hui.',
            '{c} {thing} en tout, {b} offerts. Combien y en avait-il avant ?',
        ],
        'hint'    => 'Remonte à partir du total.',
        'lists'   => ['thing' => $things, 'who' => $names],
    ],
    'math-word2' => [
        'name'    => 'Problème de pièces',
        'pattern' => 'Tu as {a} pièces. Tu achètes {b} {thing} à {c} pièces chacun. Combien de pièces te reste-t-il ?',
        'answer'  => '{a-b*c} pièces',
        'patterns' => [
            '{b} {thing} coûtent {c} pièces chacun. Tu paies avec {a} pièces. Combien te rend-on ?',
            'Tu commences avec {a} pièces et tu achètes {b} {thing} à {c} pièces. Combien te reste-t-il ?',
            '{a} pièces dans ta poche et {b} {thing} à {c} pièces chacun. Que reste-t-il ?',
            'Chacun des {b} {thing} coûte {c} pièces. Tu avais {a}. Combien de pièces maintenant ?',
            'Dépense {c} pièces {b} fois sur {a}. Que reste-t-il ?',
            'Tu paies {b} {thing} à {c} pièces avec {a} pièces. Combien te rend-on ?',
            '{a} pièces moins {b} fois {c}. Combien de pièces restent ?',
        ],
        'hint'    => 'Calcule d’abord la dépense, puis enlève-la de ce que tu avais.',
        'lists'   => ['thing' => $things],
    ],
    'math-two-step' => [
        'name'    => 'Deux étapes',
        'pattern' => '{who} remplit {a} {container} avec {b} {thing} dans chacune, puis {c} {thing} tombent. Combien en reste-t-il de rangés ?',
        'answer'  => '{a*b-c} {thing}',
        'patterns' => [
            'On remplit {a} {container} avec {b} {thing} chacune, puis {c} {thing} tombent. Combien en reste-t-il rangés ?',
            '{who} met {b} {thing} dans chacune des {a} {container} et en perd {c} en route. Combien arrivent ?',
            '{a} {container} contiennent {b} {thing} chacune. On en perd {c}. Combien en reste-t-il ?',
            'Remplis {a} {container} avec {b} {thing}, puis enlève {c}. Combien ?',
            '{b} {thing} dans chacune des {a} {container}, moins les {c} tombés.',
            'Multiplie {a} par {b}, puis enlève {c}. Ça fait combien de {thing} ?',
            '{who} avait {a} {container} de {b} {thing} et en a fait tomber {c}. Combien sont arrivés ?',
        ],
        'hint'    => 'Multiplie d’abord, soustrais ensuite.',
        'lists'   => ['container' => $containers, 'thing' => $things, 'who' => $names],
    ],

    // -------------------------------------------------------------- LITERACY
    'lit-rhyme' => [
        'name'    => 'Trouve une rime',
        'pattern' => 'Dis un mot qui rime avec « {word} ».',
        'answer'  => 'N’importe quel vrai mot qui rime',
        'patterns' => [
            'Quels mots riment avec « {word} » ? Dis-en un.',
            'Trouve un mot qui finit comme « {word} ».',
        ],
        'hint'    => 'Dis-le à voix haute et écoute la fin.',
        'lists'   => ['word' => ['chat', 'fleur', 'souris', 'bateau', 'lune', 'main',
                                 'gâteau', 'grenouille', 'nez', 'ballon', 'étoile', 'poule',
                                 'chaise', 'porte', 'chapeau', 'train', 'mouton', 'cuillère',
                                 'mur', 'chemin', 'soleil', 'jardin']],
    ],
    'lit-letter' => [
        'name'    => 'Le son du début',
        'pattern' => 'Nomme {a} choses qui commencent par la lettre « {letter} ».',
        'answer'  => 'N’importe quels {a} mots valables',
        'patterns' => [
            'Regarde autour de toi et trouve {a} choses qui commencent par « {letter} ».',
            '« {letter} » : nomme {a} choses qui commencent par ce son.',
        ],
        'hint'    => 'Regarde autour de toi pour trouver des idées.',
        'lists'   => ['letter' => ['B', 'C', 'D', 'F', 'G', 'L', 'M', 'P', 'R', 'S', 'T', 'V']],
    ],
    'lit-opposite' => [
        'name'    => 'Les contraires',
        'pattern' => 'Quel est le contraire de « {word} » ?',
        'answer'  => 'Le bon contraire',
        'patterns' => [
            '« {word} » : et le contraire ?',
            'Si quelque chose n’est pas « {word} », comment est-ce ?',
        ],
        'hint'    => 'Pense au mot qui veut dire l’inverse.',
        'lists'   => ['word' => ['chaud', 'grand', 'rapide', 'content', 'jour', 'en haut',
                                 'bruyant', 'mouillé', 'plein', 'tôt', 'dur', 'près',
                                 'ouvert', 'lourd', 'jeune', 'propre', 'premier', 'dedans',
                                 'sucré', 'rugueux', 'courageux', 'éveillé']],
    ],
    'lit-define' => [
        'name'    => 'Avec tes mots',
        'pattern' => 'Que veut dire le mot « {word} » ? Explique-le avec tes mots.',
        'answer'  => 'Toute explication sensée compte',
        'patterns' => [
            'Explique « {word} » à quelqu’un qui ne l’a jamais entendu.',
            'On te demande ce que veut dire « {word} ». Que réponds-tu ?',
        ],
        'hint'    => 'Essaie d’abord de l’utiliser dans une phrase.',
        'lists'   => ['word' => ['courage', 'curieux', 'doux', 'ancien', 'fragile',
                                 'généreux', 'têtu', 'reconnaissant', 'inquiet', 'fidèle',
                                 'patient', 'honnête', 'maladroit', 'énorme', 'silencieux',
                                 'jaloux', 'poli', 'épuisé', 'délicat', 'fier']],
    ],
    'lit-sentence' => [
        'name'    => 'Construis une phrase',
        'pattern' => 'Invente une phrase qui utilise à la fois « {word} » et « {other} ».',
        'answer'  => 'Toute phrase contenant les deux mots',
        'patterns' => [
            'Utilise « {word} » et « {other} » dans la même phrase.',
            'Fais une seule phrase où il y a « {word} » et « {other} ».',
        ],
        'hint'    => 'Elle peut être aussi farfelue que tu veux.',
        'lists'   => ['word'  => ['rivière', 'château', 'tempête', 'lanterne', 'port', 'prairie',
                                  'escalier', 'marché', 'phare', 'verger'],
                      'other' => ['silencieux', 'doré', 'soudain', 'énorme', 'gelé', 'tordu',
                                  'oublié', 'bruyant', 'à l’envers', 'invisible']],
    ],
    'lit-story' => [
        'name'    => 'Continue l’histoire',
        'pattern' => 'Raconte la suite de l’histoire : « {opening} »',
        'answer'  => 'Toute suite qui se tient',
        'patterns' => [
            'Voici le début : « {opening} » Que se passe-t-il ensuite ?',
            '« {opening} » Continue à partir de là.',
        ],
        'hint'    => 'Deux ou trois phrases suffisent.',
        'lists'   => ['opening' => [
            'La porte en haut de l’escalier n’avait jamais été ouverte...',
            'La carte montrait une île qui ne figurait sur aucune autre carte...',
            'Tout le village s’est réveillé en parlant à l’envers...',
            'Le vieux phare s’est rallumé tout seul après vingt ans...',
            'Une lettre est arrivée au nom de quelqu’un qui n’habitait pas là...',
            'Le chat est rentré avec un collier que personne n’avait acheté...',
            'Toutes les horloges de la maison se sont arrêtées à la même minute...',
            'Il y avait une deuxième lune dans le ciel, et seuls les enfants la voyaient...',
            'La bibliothèque avait une étagère qui n’existait pas hier...',
            'Des empreintes sortaient de la mer et s’arrêtaient devant la porte...',
            'Le plus vieil arbre du parc avait une porte, ce matin-là...',
            'Un colis est arrivé sans adresse, avec un trou sur le côté...',
            'La cloche de l’école a sonné une heure trop tôt, sans que personne n’y touche...',
            'Quelqu’un avait dessiné une carte sur la dernière page du cahier...',
            'Tous les oiseaux ont quitté la ville le même après-midi...',
            'Une fenêtre bloquée depuis des années s’est ouverte toute seule...',
        ]],
    ],

    // --------------------------------------------------------------- ENGLISH
    // In French this is French grammar: its own plurals and past tenses.
    'eng-plural' => [
        'name'    => 'Un et plusieurs',
        'pattern' => 'Quel est le pluriel de « {word} » ?',
        'answer'  => 'Le bon pluriel',
        'patterns' => [
            'Comment dit-on « {word} » quand il y en a plusieurs ?',
            'Un « {word} », mais deux, ça se dit comment ?',
        ],
        'hint'    => 'Certains mots changent plus que tu ne crois.',
        'lists'   => ['word' => ['cheval', 'journal', 'oeil', 'genou', 'bijou',
                                 'travail', 'chou', 'caillou', 'vitrail', 'ciel',
                                 'animal', 'hibou', 'pneu', 'nez', 'gaz',
                                 'bateau', 'oiseau', 'festival', 'bocal', 'jeu']],
    ],
    'eng-verb' => [
        'name'    => 'Hier',
        'pattern' => 'Mets cette phrase au passé composé : « Tous les jours, je {verb}. »',
        'answer'  => 'Le passé composé correct de « {verb} »',
        'patterns' => [
            '« Tous les jours, je {verb} » : dis-le comme si c’était hier.',
            'Change « je {verb} » pour parler du passé.',
        ],
        'hint'    => 'Dis-le comme si c’était déjà fait.',
        'lists'   => ['verb' => ['cours', 'nage', 'mange', 'écris', 'chante',
                                 'prends', 'bois', 'pars', 'dessine', 'dors',
                                 'vais', 'fais', 'dis', 'vois', 'lis',
                                 'mets', 'viens', 'joue', 'apprends', 'ouvre']],
    ],
    'eng-describe' => [
        'name'    => 'Décris-le',
        'pattern' => 'Décris {thing} à quelqu’un qui n’en a jamais vu, sans dire le mot.',
        'answer'  => 'Toute description claire',
        'patterns' => [
            'Explique ce qu’est {thing} sans dire le mot.',
            'Quelqu’un n’a jamais vu {thing}. Décris-le-lui.',
        ],
        'hint'    => 'Commence par ce à quoi ça sert.',
        'lists'   => ['thing' => ['un vélo', 'un parapluie', 'une bouilloire', 'un escalier',
                                  'un télescope', 'un château de sable', 'un moulin', 'un cerf-volant',
                                  'un phare', 'une brouette', 'une fermeture éclair', 'un miroir',
                                  'une échelle', 'une horloge', 'une éponge', 'un sifflet',
                                  'un lacet', 'un bonhomme de neige']],
    ],

    // --------------------------------------------------------------- SCIENCE
    'sci-sense' => [
        'name'    => 'Quel sens ?',
        'pattern' => 'Quelle partie de ton corps utilises-tu pour {sense} ?',
        'answer'  => 'L’organe du sens qui convient',
        'patterns' => [
            'Tu veux {sense}. Quelle partie de toi fait le travail ?',
            'Quel sens utilises-tu pour {sense} ?',
        ],
        'hint'    => 'Montre-la du doigt.',
        'lists'   => ['sense' => ['sentir une fleur', 'entendre une cloche', 'goûter du miel',
                                  'voir un arc-en-ciel', 'sentir le sable chaud', 'entendre le tonnerre',
                                  'goûter un citron', 'voir une étoile la nuit', 'sentir le pain chaud',
                                  'toucher une vitre froide', 'entendre ton prénom', 'goûter du sel',
                                  'voir la couleur rouge', 'sentir un chat qui ronronne']],
    ],
    'sci-float' => [
        'name'    => 'Flotte ou coule ?',
        'pattern' => 'Est-ce que {thing} flotterait ou coulerait dans l’eau ? Dis pourquoi tu le penses.',
        'answer'  => 'Les deux réponses vont, avec une raison',
        'patterns' => [
            'Tu mets {thing} dans l’eau. Ça flotte ou ça coule ? Pourquoi ?',
            'Est-ce que {thing} resterait à la surface ou irait au fond ? Dis pourquoi.',
        ],
        'hint'    => 'Pense à son poids par rapport à sa taille.',
        'lists'   => ['thing' => ['un bouchon', 'une pierre', 'une pomme', 'une pièce', 'une plume',
                                  'une éponge', 'un clou', 'une bougie', 'une orange', 'une cuillère en bois',
                                  'un raisin', 'une bouteille en plastique fermée', 'un trombone',
                                  'un citron', 'un canard en plastique', 'une brique', 'un crayon', 'une bille']],
    ],
    'sci-change' => [
        'name'    => 'Que se passe-t-il ?',
        'pattern' => 'Que se passe-t-il si {event} ? Explique du mieux que tu peux.',
        'answer'  => 'Une explication raisonnable',
        'patterns' => [
            'Dis ce que tu verrais si {event}.',
            '{event} : que se passe-t-il, et pourquoi ?',
        ],
        'hint'    => 'Dis ce que tu verrais, puis pourquoi.',
        'lists'   => ['event' => [
            'tu laisses un glaçon dans une pièce chaude',
            'on garde une plante dans un placard sombre',
            'tu frottes tes mains très vite',
            'on remue du sel dans un verre d’eau',
            'on laisse un ballon au soleil',
            'une flaque reste au soleil toute la matinée',
            'tu souffles sur une vitre froide',
            'on laisse une pomme coupée sur la table',
            'tu approches un aimant d’un tas de trombones',
            'on laisse un vélo sous la pluie pendant un mois',
            'tu lâches une pierre et une plume en même temps',
            'on pose un bocal sur une bougie allumée',
            'on étend du linge mouillé un jour de vent',
            'tu secoues une bouteille d’eau et d’huile',
            'on plante une graine et on l’arrose chaque jour',
        ]],
    ],

    // ---------------------------------------------------------------- NATURE
    'nature-animal' => [
        'name'    => 'Les cris des animaux',
        'pattern' => 'Quel cri fait {animal} ? Imite-le du mieux que tu peux !',
        'answer'  => 'Toute tentative compte',
        'patterns' => [
            'Fais le cri de {animal}.',
            '{animal} est derrière toi. Qu’entendrais-tu ?',
        ],
        'hint'    => 'Personne ne te met de note ici.',
        'lists'   => ['animal' => ['une vache', 'un canard', 'un lion', 'un mouton', 'un hibou',
                                   'une grenouille', 'un cheval', 'une abeille', 'un chat',
                                   'un loup', 'une chèvre', 'un corbeau', 'un cochon', 'un âne',
                                   'une poule', 'une souris', 'un serpent', 'un éléphant',
                                   'un chien', 'une mouette', 'un singe', 'un grillon']],
    ],
    'nature-home' => [
        'name'    => 'Où vit-il ?',
        'pattern' => 'Où vit {animal} ?',
        'answer'  => 'Le bon type d’abri',
        'patterns' => [
            'Quelle sorte d’abri a {animal} ?',
            'Si tu cherchais {animal}, où regarderais-tu ?',
        ],
        'hint'    => 'Pense à ce dont il a besoin pour être en sécurité.',
        'lists'   => ['animal' => ['une abeille', 'un lapin', 'un manchot', 'un chameau', 'un poisson',
                                   'un hibou', 'une taupe', 'un crabe', 'une chauve-souris', 'un écureuil',
                                   'un ours polaire', 'un kangourou', 'une araignée', 'un castor',
                                   'une fourmi', 'une hirondelle', 'une tortue', 'un blaireau',
                                   'un dauphin', 'un hérisson']],
    ],
    'nature-season' => [
        'name'    => 'Les saisons',
        'pattern' => 'Nomme deux choses qui arrivent {season}. Regarde {aspect}.',
        'answer'  => 'Deux réponses sensées',
        'patterns' => [
            'Pense {season}. Nomme deux choses qui changent {aspect}.',
            'Qu’est-ce qui est différent {aspect} {season} ? Dis deux choses.',
        ],
        'hint'    => 'Pense au temps qu’il fait, et aux plantes.',
        'lists'   => ['season' => ['au printemps', 'en été', 'en automne', 'en hiver'],
                      'aspect' => ['du côté du temps qu’il fait', 'du côté des arbres',
                                   'du côté des animaux', 'du côté des vêtements',
                                   'du côté du jardin']],
    ],
    'nature-chain' => [
        'name'    => 'Qui mange quoi',
        'pattern' => 'Que peut manger {animal}, et qui pourrait le manger ?',
        'answer'  => 'Une chaîne alimentaire sensée',
        'patterns' => [
            '{animal} mange quelque chose, et quelque chose le mange. Quoi ?',
            'Où se place {animal} dans la chaîne alimentaire ? Dis ce qu’il y a au-dessus et en dessous.',
        ],
        'hint'    => 'Chaque animal est le dîner de quelqu’un.',
        'lists'   => ['animal' => ['une souris', 'une grenouille', 'un lapin', 'un poisson',
                                   'une chenille', 'un moineau', 'un ver de terre', 'un escargot',
                                   'une sauterelle', 'un caneton', 'un écureuil', 'une coccinelle',
                                   'une crevette', 'un campagnol', 'un jeune hibou', 'un têtard']],
    ],

    // ----------------------------------------------------------------- LOGIC
    'logic-odd' => [
        'name'    => 'L’intrus',
        'pattern' => 'Quel est l’intrus : {set} ? Dis pourquoi.',
        'answer'  => 'Toute réponse bien justifiée',
        'patterns' => [
            'Un de ceux-là ne va pas avec les autres : {set}. Lequel, et pourquoi ?',
            '{set} : barre-en un et dis ce que les autres ont en commun.',
        ],
        'hint'    => 'Il peut y avoir plusieurs bonnes réponses.',
        'lists'   => ['set' => [
            'pomme, banane, carotte, poire',
            'chien, chat, poisson, lapin',
            'rouge, bleu, carré, vert',
            'chaussure, chaussette, chapeau, cuillère',
            'voiture, bateau, vélo, arbre',
            'cuillère, fourchette, couteau, crayon',
            'pluie, neige, brouillard, montagne',
            'deux, quatre, sept, six',
            'guitare, tambour, tableau, piano',
            'lundi, mardi, juillet, vendredi',
            'chaise, table, nuage, lit',
            'lion, tigre, vache, léopard',
            'œil, oreille, nez, gant',
            'rivière, lac, mer, désert',
            'football, tennis, échecs, natation',
            'chêne, pin, rose, bouleau',
            'marteau, scie, pomme, tournevis',
            'cercle, triangle, rouge, carré',
        ]],
    ],
    'logic-seq' => [
        'name'    => 'Quelle est la suite ?',
        'pattern' => 'Quel nombre vient ensuite : {a}, {b}, {c}, ... ?',
        'answer'  => 'Le nombre qui continue la suite',
        'patterns' => [
            'Continue la suite : {a}, {b}, {c}, ...',
            '{a}, {b}, {c} : quel nombre vient après ?',
        ],
        'hint'    => 'Cherche le pas entre les nombres.',
    ],
    'logic-riddle' => [
        'name'    => 'Devinette',
        'pattern' => '{riddle}',
        'answer'  => 'La réponse de la devinette',
        'patterns' => [
            'Voici une devinette. {riddle}',
            'Essaie de trouver celle-ci : {riddle}',
        ],
        'hint'    => 'Relis-la deux fois : l’astuce est dans les mots.',
        'lists'   => ['riddle' => [
            'J’ai des aiguilles mais je ne couds pas. Qui suis-je ?',
            'Plus j’essuie, plus je suis mouillée. Qui suis-je ?',
            'J’ai des touches mais je n’ouvre aucune porte. Qui suis-je ?',
            'Plus tu m’enlèves, plus je deviens grand. Qui suis-je ?',
            'Je monte et je descends sans bouger de place. Qui suis-je ?',
            'J’ai un cadran et deux aiguilles, mais ni bras ni jambes. Qui suis-je ?',
            'Je suis pleine de trous et je retiens quand même l’eau. Qui suis-je ?',
            'Je te suis toute la journée et je disparaîts la nuit. Qui suis-je ?',
            'J’ai un col mais pas de tête. Qui suis-je ?',
            'Plus il y en a, moins tu vois. Qui suis-je ?',
            'J’ai des dents mais je ne mange pas. Qui suis-je ?',
            'Je suis grande quand je suis jeune et petite quand je suis vieille. Qui suis-je ?',
            'J’ai des feuilles mais je ne suis pas un arbre. Qui suis-je ?',
            'On peut m’attraper mais pas me lancer. Qui suis-je ?',
            'Je descends toujours et ne remonte jamais. Qui suis-je ?',
            'J’ai un lit mais je ne dors pas, une bouche mais je ne mange pas. Qui suis-je ?',
            'J’ai un chas mais je ne vois rien. Qui suis-je ?',
            'Qu’est-ce qu’il faut casser avant de pouvoir s’en servir ?',
        ]],
    ],

    // ------------------------------------------------------------ LIFE SKILLS
    'life-kind' => [
        'name'    => 'Un geste gentil',
        'pattern' => 'Nomme une chose gentille que tu pourrais faire aujourd’hui pour {who}.',
        'answer'  => 'Toute idée gentille compte',
        'patterns' => [
            'Pense à une chose gentille que tu pourrais faire pour {who}.',
            'Comment pourrais-tu faire plaisir à {who} aujourd’hui ?',
        ],
        'hint'    => 'Les petites choses comptent aussi.',
        'lists'   => ['who' => ['un ami', 'quelqu’un de ta famille', 'un voisin',
                                'un nouvel élève à l’école', 'quelqu’un qui est triste',
                                'un enfant plus jeune', 'quelqu’un qui t’a aidé la semaine dernière',
                                'un maître ou une maîtresse', 'quelqu’un qui mange tout seul',
                                'un grand-parent', 'quelqu’un qui est malade',
                                'la personne assise à côté de toi', 'quelqu’un qui a les mains pleines',
                                'quelqu’un qui vient de perdre une partie',
                                'quelqu’un avec qui tu t’es disputé', 'quelqu’un qui vient d’arriver dans le pays']],
    ],
    'life-safe' => [
        'name'    => 'Rester en sécurité',
        'pattern' => 'Que devrais-tu faire si {situation} ?',
        'answer'  => 'Toute réponse prudente et sensée',
        'patterns' => [
            '{situation} : que fais-tu en premier ?',
            'Imagine que {situation}. Quelle est la chose prudente à faire ?',
        ],
        'hint'    => 'Trouver un adulte de confiance est souvent la première chose à faire.',
        'lists'   => ['situation' => [
            'tu perds ton adulte dans un magasin',
            'un inconnu te demande de le suivre',
            'ça sent le brûlé à la maison',
            'tu vois quelqu’un se faire faire mal',
            'tu te sens mal à l’école',
            'tu te coupes le doigt et ça ne s’arrête pas de saigner',
            'l’alarme incendie sonne et tu es à l’étage',
            'quelqu’un sur internet te demande où tu habites',
            'tu trouves une boîte de médicaments par terre',
            'ton ballon roule sur la route',
            'tu es à vélo et tes freins lâchent',
            'un chien que tu ne connais pas court vers toi',
            'tu te perds sur le chemin de la maison',
            'quelqu’un t’envoie des messages qui te font de la peine',
            'tu es le premier à trouver quelqu’un qui est tombé',
        ]],
    ],
    'life-choice' => [
        'name'    => 'Que ferais-tu ?',
        'pattern' => 'Que ferais-tu si {situation} ?',
        'answer'  => 'Il n’y a pas une seule bonne réponse : sois gentil',
        'patterns' => [
            'Imagine que {situation}. Que fais-tu ensuite ?',
            '{situation} : parles-en avec les autres. Que choisirais-tu ?',
        ],
        'hint'    => 'Dis ce que tu ferais, et pourquoi.',
        'lists'   => ['situation' => [
            'un ami se faisait gronder à ta place',
            'tu avais oublié tes devoirs',
            'tu trouvais quelque chose qui appartient à quelqu’un d’autre',
            'tu avais promis le même après-midi à deux personnes',
            'quelqu’un copiait ton travail et était félicité pour ça',
            'tu cassais quelque chose sans que personne ne le voie',
            'on te rendait trop de monnaie dans un magasin',
            'ton équipe voulait laisser quelqu’un de côté',
            'un ami te confiait un secret qui t’inquiète',
            'tu étais en train de gagner et ton ami voulait arrêter',
            'quelqu’un se moquait de la façon de parler d’un autre enfant',
            'on te posait une question et tu ne savais pas répondre',
            'un ami voulait copier tes devoirs',
            'tu faisais mal à quelqu’un sans le vouloir en jouant',
            'on t’offrait un cadeau qui ne te plaît pas',
            'tu voyais quelqu’un perdre de l’argent sans s’en rendre compte',
        ]],
    ],

    // ------------------------------------------------------------- GEOGRAPHY
    'geo-where' => [
        'name'    => 'Près et loin',
        'pattern' => 'Trouverais-tu {thing} près de chez toi, ou très loin ?',
        'answer'  => 'L’un ou l’autre, avec une raison',
        'patterns' => [
            '{thing}, c’est le genre de chose qu’on trouve à côté ou très loin ?',
            '{thing} : près de chez toi ou très loin ? Pourquoi ?',
        ],
        'hint'    => 'Pense à ce qu’il y a autour de chez toi.',
        'lists'   => ['thing' => ['une montagne', 'une plage', 'une rivière', 'un désert',
                                  'une forêt', 'un port', 'un volcan', 'une ferme',
                                  'une gare', 'un glacier', 'un lac', 'une île',
                                  'un canal', 'une forêt tropicale', 'une cascade', 'une grotte',
                                  'un pont au-dessus d’une vallée', 'un champ de blé']],
    ],
    'geo-direction' => [
        'name'    => 'De quel côté ?',
        'pattern' => 'Si tu regardes vers le {direction} et que tu tournes {turn}, vers où regardes-tu ?',
        'answer'  => 'La direction {turn} du {direction}',
        'patterns' => [
            'Regarde vers le {direction}, puis tourne {turn}. Tu regardes où maintenant ?',
            'Tu regardes vers le {direction}. Tu tournes {turn} : c’est quelle direction ?',
        ],
        'hint'    => 'Imagine une boussole, ou sers-toi de tes mains.',
        'lists'   => ['direction' => ['nord', 'sud', 'est', 'ouest'],
                      'turn'      => ['à droite', 'à gauche', 'deux fois à droite', 'd’un demi-tour']],
    ],
    'geo-place' => [
        'name'    => 'Des endroits sur Terre',
        'pattern' => 'Nomme un pays où tu t’attendrais à trouver {feature}, et dis pourquoi.',
        'answer'  => 'Tout pays qui convient, avec une raison',
        'patterns' => [
            'Quel pays aurait {feature} ? Dis comment tu le sais.',
            'Où dans le monde irais-tu voir {feature} ?',
        ],
        'hint'    => 'Pense à la chaleur ou au froid qu’il y fait.',
        'lists'   => ['feature' => ['une forêt tropicale', 'un désert', 'de la neige toute l’année',
                                    'des volcans en activité', 'des récifs de corail', 'de très longs fleuves',
                                    'des manchots en liberté', 'des oliviers', 'du thé cultivé à flanc de colline',
                                    'des éleveurs de rennes', 'de très hautes montagnes avec des alpinistes',
                                    'des canaux à la place des rues', 'des éléphants sauvages', 'des fjords',
                                    'des moulins à vent partout', 'une très longue muraille']],
    ],
    // -------------------------------------------------- NOUVELLES QUESTIONS
    'sci-hotcold' => [
        'name'    => 'Chaud ou froid ?',
        'pattern' => '{thing} : c’est plutôt chaud ou plutôt froid ?',
        'answer'  => 'L’un ou l’autre, avec une raison',
        'patterns' => [
            '{thing} : ça serait chaud ou froid au toucher ?',
            'Chaud ou froid : {thing} ?',
        ],
        'hint'    => 'Imagine que tu le touches.',
        'lists'   => ['thing' => ['Une glace', 'Une soupe', 'La neige', 'Un radiateur', 'La mer en hiver',
                                  'Une tasse de thé', 'L’intérieur du frigo', 'La flamme d’une bougie',
                                  'Le sable de la plage en été', 'Un glaçon', 'Une bouillotte',
                                  'La rosée du matin', 'Un four', 'Une boule de neige', 'Du lait tiède',
                                  'Un congélateur', 'Un mur au soleil', 'L’eau du robinet froid']],
    ],
    'sci-living' => [
        'name'    => 'Vivant ou pas ?',
        'pattern' => '{thing} : est-ce que c’est vivant ? Comment le sais-tu ?',
        'answer'  => 'La bonne réponse avec une raison sensée',
        'patterns' => [
            'Dirais-tu que {thing}, c’est vivant ? Pourquoi ?',
            'Vivant ou pas vivant : {thing} ? Donne une raison.',
        ],
        'hint'    => 'Ce qui est vivant grandit et a besoin de quelque chose pour continuer.',
        'lists'   => ['thing' => ['Un arbre', 'Un caillou', 'Un chat', 'Un nuage', 'Un champignon',
                                  'Un vélo', 'Un ver de terre', 'Une rivière', 'Une pâquerette',
                                  'Un ours en peluche', 'Une araignée', 'Une bougie', 'L’herbe',
                                  'Un coquillage', 'Une abeille', 'Une flaque', 'Une graine',
                                  'Un robot jouet']],
    ],
    'logic-same' => [
        'name'    => 'Qu’est-ce qui est pareil ?',
        'pattern' => 'Qu’est-ce que {pair} ont en commun ?',
        'answer'  => 'Tout point commun sensé',
        'patterns' => [
            '{pair} : nomme une chose qu’ils partagent.',
            'Pense à {pair}. Qu’est-ce qui est pareil chez eux ?',
        ],
        'hint'    => 'Pense à quoi ça sert, ou de quoi c’est fait.',
        'lists'   => ['pair' => ['un vélo et une voiture', 'une pomme et une banane',
                                 'un chien et un loup', 'la pluie et la neige', 'une chaise et un lit',
                                 'une cuillère et une fourchette', 'le soleil et une lampe',
                                 'un livre et un journal', 'une rivière et un lac',
                                 'des chaussures et des gants', 'un piano et une guitare',
                                 'un arbre et une fleur', 'un avion et un oiseau',
                                 'une horloge et un calendrier', 'un couteau et une scie',
                                 'un bateau et un canard']],
    ],
    'logic-order' => [
        'name'    => 'Du plus petit au plus grand',
        'pattern' => 'Range-les du plus petit au plus grand : {set}.',
        'answer'  => 'Les trois dans le bon ordre',
        'patterns' => [
            'Du plus petit au plus grand : {set}. Dis-les dans l’ordre.',
            '{set} : lequel est le plus petit, lequel le plus grand ?',
        ],
        'hint'    => 'Imagine-les l’un à côté de l’autre.',
        'lists'   => ['set' => ['une fourmi, un chien, un éléphant', 'une tasse, un seau, une baignoire',
                                'une minute, une heure, un jour', 'un caillou, un rocher, une montagne',
                                'une graine, une fleur, un arbre', 'une chaussure, une voiture, une maison',
                                'une goutte, une flaque, un lac', 'une pièce, une assiette, une table',
                                'une souris, un chat, un cheval', 'une feuille, une branche, un tronc',
                                'un pas, une rue, un pays', 'une cuillère, une pelle, une pelleteuse',
                                'un bébé, un enfant, un adulte', 'un bouton, une assiette, une roue',
                                'une bougie, un lampadaire, une tour',
                                'un flocon, une boule de neige, un bonhomme de neige']],
    ],
    'logic-truefalse' => [
        'name'    => 'Vrai ou faux ?',
        'pattern' => 'Vrai ou faux : {claim} ? Dis pourquoi.',
        'answer'  => 'La bonne réponse avec une raison',
        'patterns' => [
            'Est-ce juste ou faux : {claim} ? Explique.',
            'Quelqu’un dit que {claim}. Tu es d’accord ? Dis pourquoi.',
        ],
        'hint'    => 'Un seul contre-exemple suffit pour que ce soit faux.',
        'lists'   => ['claim' => ['tous les oiseaux volent', 'tout carré est aussi un rectangle',
                                  'tous les poissons vivent dans l’eau', 'toutes les araignées ont six pattes',
                                  'le soleil se lève à l’ouest', 'certains chats n’ont pas de queue',
                                  'tout triangle a trois côtés', 'la glace est plus lourde que l’eau',
                                  'tous les mois ont trente jours', 'toutes les plantes ont des fleurs',
                                  'la baleine est un poisson', 'aucun nombre n’est à la fois pair et impair']],
    ],
    'geo-hotcold' => [
        'name'    => 'Pays chaud ou pays froid ?',
        'pattern' => 'Aurais-tu besoin de {thing} dans un pays chaud ou dans un pays froid ?',
        'answer'  => 'L’un ou l’autre, avec une raison',
        'patterns' => [
            '{thing} : tu le mettrais dans ta valise pour un pays chaud ou un pays froid ?',
            'Pays chaud ou pays froid : où as-tu besoin de {thing} ?',
        ],
        'hint'    => 'Pense à ce que tu mets le jour le plus froid de l’année.',
        'lists'   => ['thing' => ['un bonnet en laine', 'des lunettes de soleil', 'une écharpe',
                                  'des sandales', 'un manteau épais', 'un chapeau de soleil',
                                  'des gants', 'un ventilateur', 'des bottes de neige',
                                  'un maillot de bain', 'une couverture bien chaude', 'un short',
                                  'une boisson chaude', 'des patins à glace', 'une boisson fraîche',
                                  'de la crème solaire']],
    ],
    'geo-travel' => [
        'name'    => 'Comment y aller ?',
        'pattern' => 'Comment irais-tu jusqu’à {place} ?',
        'answer'  => 'Toute façon sensée de voyager',
        'patterns' => [
            'Prépare le voyage jusqu’à {place}. Tu voyages dans quoi ?',
            'Comment fait-on pour aller à {place} ?',
        ],
        'hint'    => 'Pour certains endroits il faut plusieurs voyages.',
        'lists'   => ['place' => ['une île en pleine mer', 'le sommet d’une montagne',
                                  'le magasin au bout de la rue', 'un pays très lointain',
                                  'une ferme de l’autre côté des champs', 'le milieu d’un grand lac',
                                  'une ville de l’autre côté du fleuve', 'la lune',
                                  'un village en haut d’une côte raide', 'la plage', 'une grotte',
                                  'le milieu d’une forêt', 'une grande ville',
                                  'un phare sur les rochers', 'la rue d’à côté', 'un aéroport']],
    ],
    'geo-difference' => [
        'name'    => 'Quelle différence ?',
        'pattern' => 'Quelle est la différence entre {pair} ?',
        'answer'  => 'Toute différence claire',
        'patterns' => [
            '{pair} : qu’est-ce qui les distingue ?',
            'Explique ce qui rend {pair} différents.',
        ],
        'hint'    => 'La taille est une réponse, mais pas la seule.',
        'lists'   => ['pair' => ['un lac et une mer', 'une colline et une montagne',
                                 'un village et une ville', 'une rivière et un canal',
                                 'une île et une presqu’île', 'un bois et une forêt',
                                 'une route et une autoroute', 'un ruisseau et un fleuve',
                                 'une plage et une falaise', 'une ferme et un champ',
                                 'une carte et un globe', 'un pays et un continent']],
    ],
    'eng-article' => [
        'name'    => 'Le ou la ?',
        'pattern' => 'Est-ce qu’on dit "le" ou "la" devant "{word}" ?',
        'answer'  => 'Le bon article',
        'patterns' => [
            '« {word} » : c’est « le » ou « la » ?',
            'Dis « {word} » avec le bon petit mot devant.',
        ],
        'hint'    => 'Dis-le à voix haute avec les deux et écoute ce qui sonne juste.',
        'lists'   => ['word' => ['pomme', 'livre', 'arbre', 'table', 'eau', 'main',
                                 'journée', 'problème', 'fleur', 'voiture', 'lait', 'carte',
                                 'nez', 'chien', 'classe', 'canapé']],
    ],
    'eng-question' => [
        'name'    => 'Pose la question',
        'pattern' => 'Transforme cette phrase en question : « {sentence} »',
        'answer'  => 'Les mêmes mots, sous forme de question',
        'patterns' => [
            'Au lieu de le dire, demande-le : « {sentence} »',
            '« {sentence} » : transforme ça en question.',
        ],
        'hint'    => 'Parfois il suffit d’ajouter « est-ce que » au début.',
        'lists'   => ['sentence' => ['Tu as faim.', 'Elle sait nager.', 'Ils sont rentrés.',
                                     'Il pleut.', 'Il a un vélo.', 'Nous sommes en retard.',
                                     'Le chien dort.', 'Tu aimes les pommes.',
                                     'Il faisait froid hier.', 'Ils sont prêts.',
                                     'Elle a trouvé la clé.', 'Le bus arrive.',
                                     'Tu m’entends.', 'Il était à l’école.',
                                     'Le gâteau est fini.', 'Nous en avons assez.']],
    ],
    'nature-baby' => [
        'name'    => 'Les petits des animaux',
        'pattern' => 'Comment appelle-t-on le petit {animal} ?',
        'answer'  => 'Le bon nom du petit',
        'patterns' => [
            '{animal} a un petit. Comment l’appelle-t-on ?',
            'Quel nom donne-t-on au petit {animal} ?',
        ],
        'hint'    => 'Certains ont un nom à eux, d’autres sont juste « un petit ».',
        'lists'   => ['animal' => ['du chat', 'du chien', 'de la vache', 'du mouton', 'du canard',
                                   'du cheval', 'de la grenouille', 'de l’ours', 'de la chèvre',
                                   'de la poule', 'du cochon', 'du cygne', 'du cerf', 'du kangourou',
                                   'du papillon', 'du hibou']],
    ],
    'nature-need' => [
        'name'    => 'De quoi a-t-il besoin ?',
        'pattern' => 'Nomme deux choses dont {living} a besoin pour rester en vie.',
        'answer'  => 'Deux besoins sensés',
        'patterns' => [
            '{living} : nomme deux choses sans lesquelles il ne peut pas vivre.',
            'De quoi aurait besoin {living} si tu t’en occupais ?',
        ],
        'hint'    => 'La nourriture et l’eau en font deux - et ensuite ?',
        'lists'   => ['living' => ['un arbre', 'un chien', 'un poisson', 'une abeille', 'une personne',
                                   'une plante en pot', 'un oiseau', 'un ver de terre', 'un cheval',
                                   'un chat', 'un tournesol', 'une grenouille', 'un lapin',
                                   'un champignon']],
    ],
    'life-tidy' => [
        'name'    => 'Ça se range où ?',
        'pattern' => 'Quand tu ranges, où va {thing} ?',
        'answer'  => 'Tout endroit sensé',
        'patterns' => [
            'Tu ranges : quelle est la place de {thing} ?',
            '{thing} traîne par terre. Où est-ce que ça va ?',
        ],
        'hint'    => 'Là où tu le chercherais la prochaine fois.',
        'lists'   => ['thing' => ['tes chaussures', 'une assiette sale', 'un livre de la bibliothèque',
                                  'ton manteau', 'les déchets', 'une petite voiture',
                                  'une serviette mouillée', 'des chaussettes sales', 'le lait',
                                  'un crayon', 'ton cartable', 'une bouteille vide',
                                  'un trognon de pomme', 'des vêtements propres',
                                  'des bottes pleines de boue', 'une paire de ciseaux']],
    ],
    'life-before' => [
        'name'    => 'Qu’est-ce qui vient d’abord ?',
        'pattern' => 'Nomme deux choses à faire avant de {activity}.',
        'answer'  => 'Deux étapes sensées',
        'patterns' => [
            'Que faut-il faire avant de {activity} ? Nomme deux choses.',
            'Tu vas {activity}. Qu’est-ce que tu règles d’abord ?',
        ],
        'hint'    => 'Pense à ce qui irait mal si tu oubliais.',
        'lists'   => ['activity' => ['aller à la piscine', 'préparer un repas', 'partir à vélo',
                                     'partir à l’école', 'inviter des amis à la maison',
                                     'partir en longue randonnée', 'planter des graines',
                                     'prendre le bus tout seul', 'commencer tes devoirs',
                                     'aller te coucher', 'nourrir un animal', 'faire ta valise']],
    ],
    // Les cinq qui n’existaient qu’en anglais
    'life-action' => [
        'name'    => 'Fais-le tout de suite',
        'pattern' => 'Essaie de {action} pendant {n} secondes. Si tu y arrives, tu continues !',
        'answer'  => 'Réussir l’action',
        'patterns' => [
            'Tu arrives à {action} pendant {n} secondes ? Vas-y !',
            '{n} secondes pour {action}. Tout le monde compte.',
        ],
        'hint'    => 'Tout le monde compte à voix haute.',
        'lists'   => ['action' => ['sauter à cloche-pied', 'rester debout sur un pied',
                                   'applaudir le plus vite possible', 'tourner lentement sur toi-même',
                                   'rire très fort', 'imiter un chat',
                                   'tenir un livre en équilibre sur la tête', 'marcher à reculons',
                                   'toucher tes pieds', 'rester immobile comme une statue',
                                   'parler sans dire la lettre S', 'marcher sur place']],
    ],
    'life-team' => [
        'name'    => 'Que ferais-tu ?',
        'pattern' => 'Que ferais-tu si {situation} ? Propose une façon de régler ça.',
        'answer'  => 'Toute réponse réfléchie',
        'patterns' => [
            'Suppose que {situation}. Quelle est ton idée ?',
            '{situation} : dis à la table une façon de régler ça.',
        ],
        'hint'    => 'Dis ce que tu essaierais en premier.',
        'lists'   => ['situation' => ['un ami tombait dans la cour',
                                      'ton groupe n’arrivait à se mettre d’accord sur rien',
                                      'tu renversais de l’eau sur toute la table',
                                      'tu voyais quelqu’un assis tout seul',
                                      'quelqu’un était laissé de côté dans un jeu',
                                      'deux amis voulaient commencer tous les deux',
                                      'les règles n’étaient pas claires et une dispute commençait',
                                      'quelqu’un coupait la parole à tout le monde']],
    ],
    'en-word' => [
        'name'    => 'Les mots de l’aventure',
        'pattern' => 'Que veut dire le mot « {word} » ? Explique-le avec tes mots.',
        'answer'  => 'Toute explication sensée compte',
        'patterns' => [
            'Quelqu’un dans ton jeu dit « {word} ». Qu’est-ce que ça veut dire ?',
            'Explique « {word} » comme si tu racontais l’histoire.',
        ],
        'hint'    => 'Utilise-le dans une phrase sur ton jeu.',
        'lists'   => ['word' => ['forêt', 'rivière', 'montagne', 'trésor', 'pont',
                                 'château', 'dragon', 'boussole', 'île', 'voyage',
                                 'courage', 'amitié', 'port', 'lanterne', 'naufrage', 'carte']],
    ],
    'science-why' => [
        'name'    => 'Pourquoi ça arrive ?',
        'pattern' => 'Pourquoi {phenomenon} ?',
        'answer'  => 'Toute explication raisonnable',
        'patterns' => [
            'Sais-tu expliquer pourquoi {phenomenon} ?',
            'On te demande : pourquoi {phenomenon} ? Que réponds-tu ?',
        ],
        'hint'    => 'Dis d’abord ce que tu as remarqué, puis pourquoi à ton avis.',
        'lists'   => ['phenomenon' => ['il pleut', 'y a-t-il des arcs-en-ciel après la pluie',
                                       'la glace fond quand on la laisse dehors',
                                       'les feuilles changent de couleur en automne',
                                       'on voit les étoiles la nuit',
                                       'les ballons à l’hélium montent',
                                       'les ombres sont plus longues l’après-midi',
                                       'on frissonne quand on a froid',
                                       'le pain durcit quand on le laisse dehors',
                                       'les bateaux flottent',
                                       'la lune change de forme',
                                       'on a besoin de dormir']],
    ],
    'geo-continent' => [
        'name'    => 'Quel continent ?',
        'pattern' => 'Sur quel continent se trouve {place} ?',
        'answer'  => 'Le bon continent',
        'patterns' => [
            '{place} se trouve sur quel continent ?',
            'Montre le continent où se trouve {place} et nomme-le.',
        ],
        'hint'    => 'Il y en a sept.',
        'lists'   => ['place' => ['l’Égypte', 'le Brésil', 'le Japon', 'l’Italie', 'le Kenya',
                                  'le Canada', 'l’Inde', 'la Norvège', 'le Pérou', 'le Vietnam',
                                  'l’Australie', 'le Mexique', 'l’Espagne', 'la Chine',
                                  'le Maroc', 'l’Argentine']],
    ],
    // ------------------------------------------- D’AUTRES QUESTIONS DE MATHS
    'math-halve' => [
        'name'    => 'La moitié',
        'pattern' => '{who} partage {a} {thing} équitablement avec un ami. Combien chacun en a-t-il ?',
        'answer'  => '{a/2} {thing}',
        'hint'    => 'Distribue un par un : un pour toi, un pour moi.',
        'lists'   => ['thing' => $things, 'who' => $names],
        'patterns' => [
            'La moitié de {a} {thing}, ça fait combien ?',
            'Sépare {a} {thing} en deux tas égaux. Combien dans un tas ?',
            '{a} {thing} partagés entre deux. Combien chacun ?',
            'Quelle est la moitié de {a} ?',
            '{who} garde la moitié de {a} {thing}. Ça fait combien ?',
            'Deux enfants, {a} {thing}, autant pour chacun. Combien ?',
            'Coupe {a} {thing} en deux parts égales. Ça donne quoi ?',
            'Si on divise {a} {thing} en deux, quelle est la taille d’une part ?',
        ],
    ],
    'math-tens' => [
        'name'    => 'Ajouter dix',
        'pattern' => 'Combien font {a} + 10 ?',
        'answer'  => '{a+10}',
        'hint'    => 'Seul le chiffre des dizaines change.',
        'patterns' => [
            'Ajoute dix à {a}.',
            '{a} et dix de plus, ça fait combien ?',
            'Dix de plus que {a}, c’est combien ?',
            'Pars de {a} et saute dix en avant.',
            'Quel nombre est dix de plus que {a} ?',
            '{a} + 10 = ?',
            'Compte dix à partir de {a}. Où arrives-tu ?',
            'Si tu avais {a} et que tu en trouvais dix de plus, tu en aurais combien ?',
        ],
    ],
    'math-compare' => [
        'name'    => 'Lequel est le plus grand ?',
        'pattern' => 'Lequel est le plus grand : {a} ou {b} ? De combien ?',
        'answer'  => '{a}, de {a-b}',
        'hint'    => 'Compte à partir du plus petit.',
        'patterns' => [
            '{a} et {b} : lequel est le plus grand, et de combien ?',
            'Mets le signe « plus grand que » entre {a} et {b}. Dans quel sens ?',
            'De combien {a} est-il plus grand que {b} ?',
            '{a} ou {b} : lequel préfères-tu, et pourquoi est-ce plus ?',
            'Quelle est la différence entre {a} et {b} ?',
            'Deux tas : un de {a}, un de {b}. Combien de plus dans le grand ?',
            'Est-ce que {a} est plus ou moins que {b} ? Dis de combien.',
            'Compte l’écart entre {b} et {a}.',
        ],
    ],
    'math-order' => [
        'name'    => 'Range-les',
        'pattern' => 'Range-les du plus petit au plus grand : {a}, {b}, {c}.',
        'answer'  => 'Les trois nombres dans l’ordre',
        'hint'    => 'Regarde d’abord les dizaines.',
        'patterns' => [
            'Lequel de {a}, {b} et {c} est le plus petit ? Et ensuite ?',
            'Aligne {a}, {b} et {c} du petit au grand.',
            '{a}, {b}, {c} : dis-les plutôt du plus grand au plus petit.',
            'Trie ces trois-là : {a}, {b}, {c}.',
            'Lequel vient en premier sur la ligne des nombres : {a}, {b} ou {c} ?',
            'Ordonne {a}, {b} et {c}, du plus petit au plus grand.',
            'Montre le plus grand de {a}, {b} et {c}, puis le plus petit.',
            'Trois nombres : {a}, {b}, {c}. Lequel est au milieu ?',
        ],
    ],
    'math-repeat' => [
        'name'    => 'Compter de {b} en {b}',
        'pattern' => 'Compte de {b} en {b} à partir de {a}. Dis les trois suivants.',
        'answer'  => '{a+b}, {a+b+b}, {a+b+b+b}',
        'hint'    => 'Dis chaque nombre à voix haute avant le suivant.',
        'patterns' => [
            'Pars de {a} et continue d’ajouter {b}. Quels sont les trois suivants ?',
            '{a}, puis {b} de plus, et encore {b}. Dis-les.',
            'Fais trois bonds de {b} à partir de {a}.',
            'Qu’est-ce qui vient après {a} si on compte de {b} en {b} ?',
            'En comptant de {b} en {b} : {a}, et ensuite ?',
            'Ajoute {b} à {a}, puis encore, puis encore.',
            'Trois pas de {b} depuis {a} : où arrives-tu ?',
            'Dis la table de {b} en partant de {a}, trois nombres.',
        ],
    ],
    'math-remainder' => [
        'name'    => 'Ce qui reste',
        'pattern' => 'Partage {a} {thing} entre {b} amis, un par un. Combien en reste-t-il à la fin ?',
        'answer'  => '{a%b} {thing}',
        'hint'    => 'Distribue jusqu’à ne plus pouvoir en donner un à chacun.',
        'lists'   => ['thing' => $things],
        'patterns' => [
            '{a} {thing} entre {b}. Combien ne peuvent pas être partagés ?',
            'Distribue {a} {thing} à {b} enfants un par un. Combien restent en trop ?',
            '{a} {thing} en groupes de {b} : quel est le reste ?',
            '{b} amis se partagent {a} {thing}. Combien restent dans la boîte ?',
            'Divise {a} {thing} par {b}. Que reste-t-il ?',
            'Fais des groupes de {b} avec {a} {thing}. Combien restent sans groupe ?',
            '{a} {thing}, {b} assiettes, autant sur chacune. Combien restent dans la boîte ?',
            'Partage {a} {thing} entre {b} et compte ce qui reste.',
        ],
    ],
];
