<?php
/**
 * The question templates in German. Keyed by the English template's code;
 * see install/mission-templates-all.php for how the two halves are joined.
 *
 * CASE AND GENDER
 *
 * German bends the words around a blank, and one sentence has to hold a dozen
 * different ones. So each place carries its own preposition and case - im
 * Garten, auf der Wiese - and the sentences are written to avoid an article in
 * front of a blank: "mit je 5 Murmeln" rather than "in jedem Korb". Every
 * creature and object is a plural, which needs no gender.
 *
 * The reading and grammar questions are not translations: rhymes, plurals and
 * past tenses only exist inside one language, so those are written fresh here.
 */

$creatures = ['Kaninchen', 'Kätzchen', 'Welpen', 'Entenküken', 'Frösche', 'Bienen',
              'Pinguine', 'Füchse', 'Eulen', 'Schildkröten', 'Eichhörnchen', 'Delfine'];

$things = ['Äpfel', 'Murmeln', 'Aufkleber', 'Buntstifte', 'Muscheln', 'Eicheln',
           'Knöpfe', 'Kieselsteine', 'Bänder', 'Kastanien', 'Federn', 'Kirschen'];

$places = ['auf der Wiese', 'im Garten', 'am Teich', 'im Wald', 'auf dem Spielplatz',
           'am Strand', 'im Obstgarten', 'im Baumhaus', 'in der Scheune', 'am Bach'];

$names = ['Mia', 'Ben', 'Lina', 'Jonas', 'Emma', 'Theo',
          'Sana', 'Milo', 'Bella', 'Pedro', 'Ada', 'Noor'];

$containers = ['Körbe', 'Kisten', 'Gläser', 'Eimer', 'Taschen', 'Schachteln', 'Tabletts'];

$treats = ['Kekse', 'Trauben', 'Brote', 'Erdbeeren', 'Muffins', 'Pflaumen'];

return [

    // ----------------------------------------------------------------- MATHS
    'math-add' => [
        'name'    => 'Dazuzählen',
        'pattern' => 'Es sind {a} {creature} {place}. {b} weitere kommen dazu. Wie viele {creature} sind es jetzt?',
        'answer'  => '{a+b} {creature}',
        'patterns' => [
            '{b} weitere {creature} kommen {place} dazu, wo schon {a} waren. Wie viele sind es jetzt?',
            'Zähl die {creature} {place}: erst {a}, dann kommen {b} dazu.',
            'Erst {a} {creature} {place}, dann {b} weitere. Zusammen?',
            'Rechne zusammen: {a} {creature} {place} und {b}, die gerade gekommen sind.',
            'Es waren {a} {creature} {place}. Jetzt sind {b} mehr da. Wie viele sind das?',
            'Wie viele {creature} sind {place}, wenn {b} zu den {a} dazukommen?',
            '{a} und {b} mehr - wie viele {creature} sind das?',
        ],
        'hint'    => 'Zähle alle zusammen.',
        'lists'   => ['creature' => $creatures, 'place' => $places],
    ],
    'math-sub' => [
        'name'    => 'Wegnehmen',
        'pattern' => '{who} hat {a} {thing} gesammelt und verschenkt {b} davon. Wie viele {thing} bleiben übrig?',
        'answer'  => '{a-b} {thing}',
        'patterns' => [
            '{who} hatte heute Morgen {a} {thing} und hat schon {b} verschenkt. Wie viele bleiben?',
            'Von {a} {thing} gibt {who} {b} an einen Freund. Wie viele bleiben übrig?',
            '{who} verschenkt {b} von {a} {thing}. Wie viele bleiben?',
            'Nimm {b} von {a} {thing} weg. Wie viele bleiben {who}?',
            '{who} hatte am Anfang {a} {thing}. {b} sind weg. Wie viele jetzt?',
            'Von {a} {thing} verschwinden {b}. Wie viele sind noch da?',
            '{a} {thing}, minus die {b}, die {who} verschenkt hat. Wie viele?',
        ],
        'hint'    => 'Fang bei dem an, was du hattest, und nimm den Rest weg.',
        'lists'   => ['thing' => $things, 'who' => $names],
    ],
    'math-count-back' => [
        'name'    => 'Rückwärts zählen',
        'pattern' => 'Fang bei {a} an und zähle {b} zurück. Wo kommst du an?',
        'answer'  => '{a-b}',
        'patterns' => [
            'Zähle von {a} aus {b} zurück. Welche Zahl sagst du zuletzt?',
            'Du stehst auf {a} und gehst {b} Schritte zurück. Wo bleibst du stehen?',
            '{a} und {b} Schritte zurück. Welche Zahl ist das?',
            'Sag die Zahl, bei der du landest, wenn du von {a} aus {b} zurückgehst.',
            'Nimm {b} von {a} weg, indem du rückwärts zählst.',
            'Fang bei {a} an. Geh {b}-mal einen Schritt zurück. Wo bist du?',
            '{a} minus {b} - zähl es laut rückwärts.',
        ],
        'hint'    => 'Nimm die Finger zu Hilfe, wenn es hilft.',
    ],
    'math-double' => [
        'name'    => 'Verdoppeln',
        'pattern' => '{who} hat {a} {thing} und findet noch einmal genauso viele. Wie viele sind es jetzt?',
        'answer'  => '{a+a} {thing}',
        'patterns' => [
            '{who} hat {a} {thing}. Verdopple das. Wie viele sind es?',
            'Auf dem Tisch liegen {a} {thing} und in der Kiste noch einmal genauso viele. Wie viele sind das?',
            'Zweimal {a} {thing} - wie viele?',
            '{who} findet noch einmal {a} {thing}. Wie viele sind es insgesamt?',
            '{a} {thing} in einer Hand, {a} in der anderen. Wie viele zusammen?',
            'Verdopple {a}. Was kommt heraus?',
            '{a} {thing} und noch einmal so viele. Wie viele?',
        ],
        'hint'    => 'Verdoppeln heißt: dieselbe Menge zweimal.',
        'lists'   => ['thing' => $things, 'who' => $names],
    ],
    'math-mul' => [
        'name'    => 'Gruppen von',
        'pattern' => '{a} {container}, jeweils {b} {thing} darin. Wie viele {thing} sind das zusammen?',
        'answer'  => '{a*b} {thing}',
        'patterns' => [
            '{a} {container} und jeweils {b} {thing}. Wie viele {thing} sind das?',
            'Rechne aus: {a} {container}, jeweils {b} {thing}.',
            'Wie viele {thing} sind in {a} {container} zu je {b}?',
            '{b} {thing} in einer {container}. Wie viele in {a} davon?',
            'Male: {a} mal {b} {thing}.',
            'Es gibt {a} {container}, jeweils {b} {thing} darin. Zähl alle.',
            '{a} mal {b} {thing} - wie viele sind das?',
        ],
        'hint'    => 'Zähle die Gruppen und dann, was in jeder steckt.',
        'lists'   => ['container' => $containers, 'thing' => $things],
    ],
    'math-div' => [
        'name'    => 'Gerecht teilen',
        'pattern' => 'Teile {a} {treat} gerecht unter {b} Freunden auf. Wie viele bekommt jeder?',
        'answer'  => '{a/b} {treat} pro Kind',
        'patterns' => [
            '{b} Freunde teilen sich {a} {treat} gerecht. Wie viele bekommt jeder?',
            'Teile {a} {treat} in {b} gleich große Stapel. Wie viele sind in einem Stapel?',
            '{a} {treat} unter {b} aufgeteilt. Wie viele für jeden?',
            'Wie viele {treat} bekommt jeder der {b} Freunde von {a}?',
            'Teile {a} {treat} durch {b}.',
            'Es gibt {b} Teller und {a} {treat}. Leg auf jeden gleich viele.',
            '{a} {treat}, {b} Kinder, alle gleich viel. Wie viele?',
        ],
        'hint'    => 'Gib sie einzeln aus, wie Spielkarten.',
        'lists'   => ['treat' => $treats],
    ],
    'math-missing' => [
        'name'    => 'Die fehlende Zahl',
        'pattern' => '{who} hatte ein paar {thing}, bekam {b} dazu und hat jetzt {c}. Wie viele waren es am Anfang?',
        'answer'  => '{c-b} {thing}',
        'patterns' => [
            '{who} hat jetzt {c} {thing}, nachdem {b} dazugekommen sind. Wie viele waren es vorher?',
            'Jemand gab {who} {b} {thing}, damit waren es {c}. Wie viele waren es davor?',
            '{who} hat am Ende {c} {thing}, nachdem {b} dazukamen. Womit hat {who} angefangen?',
            'Irgendetwas plus {b} ergibt {c}. Wie viel war das?',
            '{who} hat jetzt {c} {thing}. {b} davon sind neu. Wie viele sind alt?',
            'Rechne zurück: jetzt {c} {thing}, davon {b} von heute.',
            '{c} {thing} insgesamt, {b} geschenkt. Wie viele waren es vorher?',
        ],
        'hint'    => 'Rechne von der Gesamtzahl rückwärts.',
        'lists'   => ['thing' => $things, 'who' => $names],
    ],
    'math-word2' => [
        'name'    => 'Rechnen mit Münzen',
        'pattern' => 'Du hast {a} Münzen. Du kaufst {b} {thing} für je {c} Münzen. Wie viele Münzen bleiben dir?',
        'answer'  => '{a-b*c} Münzen',
        'patterns' => [
            '{b} {thing} kosten je {c} Münzen. Du zahlst mit {a} Münzen. Wie viel bekommst du zurück?',
            'Du fängst mit {a} Münzen an und kaufst {b} {thing} zu je {c} Münzen. Wie viel bleibt?',
            '{a} Münzen in der Tasche und {b} {thing} zu je {c} Münzen. Was bleibt?',
            'Jedes der {b} {thing} kostet {c} Münzen. Du hattest {a}. Wie viele Münzen jetzt?',
            'Gib {b}-mal {c} Münzen von {a} aus. Was bleibt?',
            'Du bezahlst {b} {thing} zu je {c} Münzen von {a} Münzen. Wie viel bekommst du zurück?',
            '{a} Münzen minus {b} mal {c}. Wie viele Münzen bleiben?',
        ],
        'hint'    => 'Rechne erst die Kosten aus und zieh sie dann ab.',
        'lists'   => ['thing' => $things],
    ],
    'math-two-step' => [
        'name'    => 'Zwei Schritte',
        'pattern' => '{who} packt {a} {container}, jeweils {b} {thing} hinein, dann fallen {c} {thing} heraus. Wie viele sind noch eingepackt?',
        'answer'  => '{a*b-c} {thing}',
        'patterns' => [
            '{a} {container} werden gefüllt, jeweils {b} {thing}, dann fallen {c} {thing} heraus. Wie viele sind noch drin?',
            '{who} packt {a} {container}, jeweils {b} {thing}, und verliert unterwegs {c}. Wie viele kommen an?',
            '{a} {container} enthalten je {b} {thing}. {c} gehen verloren. Wie viele bleiben?',
            'Füll {a} {container} mit je {b} {thing} und nimm dann {c} weg. Wie viele?',
            '{b} {thing} in jeder der {a} {container}, ohne die {c}, die herausgefallen sind.',
            'Male {a} mit {b} und zieh dann {c} ab. Wie viele {thing} sind das?',
            '{who} hatte {a} {container} zu je {b} {thing} und hat {c} verloren. Wie viele kamen an?',
        ],
        'hint'    => 'Erst malnehmen, dann abziehen.',
        'lists'   => ['container' => $containers, 'thing' => $things, 'who' => $names],
    ],

    // -------------------------------------------------------------- LITERACY
    'lit-rhyme' => [
        'name'    => 'Finde einen Reim',
        'pattern' => 'Sag ein Wort, das sich auf „{word}“ reimt.',
        'answer'  => 'Jedes echte Reimwort zählt',
        'patterns' => [
            'Welche Wörter reimen sich auf „{word}“? Sag eines.',
            'Finde ein Wort, das hinten klingt wie „{word}“.',
        ],
        'hint'    => 'Sprich es laut aus und hör auf das Ende.',
        'lists'   => ['word' => ['Haus', 'Baum', 'Stern', 'Maus', 'Hand', 'Katze',
                                 'Blume', 'Schnecke', 'Nase', 'Boot', 'Glocke', 'Kuchen',
                                 'Stuhl', 'Tür', 'Mond', 'Hut', 'Zug', 'Schaf',
                                 'Löffel', 'Wand', 'Weg', 'Sonne']],
    ],
    'lit-letter' => [
        'name'    => 'Der erste Laut',
        'pattern' => 'Nenne {a} Dinge, die mit dem Buchstaben „{letter}“ anfangen.',
        'answer'  => 'Beliebige {a} passende Wörter',
        'patterns' => [
            'Schau dich um und finde {a} Dinge, die mit „{letter}“ anfangen.',
            '„{letter}“: Nenne {a} Dinge, die mit diesem Laut beginnen.',
        ],
        'hint'    => 'Schau dich im Raum um, das gibt Ideen.',
        'lists'   => ['letter' => ['B', 'D', 'F', 'G', 'H', 'K', 'L', 'M', 'R', 'S', 'T', 'W']],
    ],
    'lit-opposite' => [
        'name'    => 'Gegenteile',
        'pattern' => 'Was ist das Gegenteil von „{word}“?',
        'answer'  => 'Das richtige Gegenteil',
        'patterns' => [
            '„{word}“ - und andersherum?',
            'Wenn etwas nicht „{word}“ ist, wie ist es dann?',
        ],
        'hint'    => 'Denk an das Wort, das genau andersherum bedeutet.',
        'lists'   => ['word' => ['heiß', 'groß', 'schnell', 'fröhlich', 'Tag', 'oben',
                                 'laut', 'nass', 'voll', 'früh', 'hart', 'nah',
                                 'offen', 'schwer', 'jung', 'sauber', 'erster', 'drinnen',
                                 'süß', 'rau', 'mutig', 'wach']],
    ],
    'lit-define' => [
        'name'    => 'Mit eigenen Worten',
        'pattern' => 'Was bedeutet das Wort „{word}“? Erkläre es mit deinen eigenen Worten.',
        'answer'  => 'Jede sinnvolle Erklärung zählt',
        'patterns' => [
            'Erkläre „{word}“ jemandem, der es noch nie gehört hat.',
            'Jemand fragt dich, was „{word}“ bedeutet. Was sagst du?',
        ],
        'hint'    => 'Bau es erst einmal in einen Satz ein.',
        'lists'   => ['word' => ['Mut', 'neugierig', 'sanft', 'uralt', 'zerbrechlich',
                                 'großzügig', 'stur', 'dankbar', 'ängstlich', 'treu',
                                 'geduldig', 'ehrlich', 'ungeschickt', 'riesig', 'still',
                                 'eifersüchtig', 'höflich', 'erschöpft', 'empfindlich', 'stolz']],
    ],
    'lit-sentence' => [
        'name'    => 'Bau einen Satz',
        'pattern' => 'Denk dir einen Satz aus, in dem „{word}“ und „{other}“ beide vorkommen.',
        'answer'  => 'Jeder Satz mit beiden Wörtern',
        'patterns' => [
            'Verwende „{word}“ und „{other}“ im selben Satz.',
            'Bau einen einzigen Satz, in dem „{word}“ und „{other}“ vorkommen.',
        ],
        'hint'    => 'Er darf so albern sein, wie du willst.',
        'lists'   => ['word'  => ['Fluss', 'Burg', 'Sturm', 'Laterne', 'Hafen', 'Wiese',
                                  'Treppe', 'Markt', 'Leuchtturm', 'Obstgarten'],
                      'other' => ['still', 'golden', 'plötzlich', 'riesig', 'gefroren', 'krumm',
                                  'vergessen', 'laut', 'verkehrt herum', 'unsichtbar']],
    ],
    'lit-story' => [
        'name'    => 'Erzähl weiter',
        'pattern' => 'Erzähl, wie die Geschichte weitergeht: „{opening}“',
        'answer'  => 'Jede Fortsetzung, die dazu passt',
        'patterns' => [
            'Hier ist der Anfang: „{opening}“ Wie geht es weiter?',
            '„{opening}“ Mach von dort aus weiter.',
        ],
        'hint'    => 'Zwei oder drei Sätze reichen völlig.',
        'lists'   => ['opening' => [
            'Die Tür oben an der Treppe war noch nie offen gewesen ...',
            'Auf der Karte war eine Insel, die auf keiner anderen Karte stand ...',
            'Das ganze Dorf wachte auf und sprach rückwärts ...',
            'Der alte Leuchtturm ging nach zwanzig Jahren von selbst wieder an ...',
            'Ein Brief kam für jemanden, der dort gar nicht wohnte ...',
            'Die Katze kam mit einem Halsband nach Hause, das niemand gekauft hatte ...',
            'Alle Uhren im Haus blieben in derselben Minute stehen ...',
            'Am Himmel stand ein zweiter Mond, und nur die Kinder sahen ihn ...',
            'In der Bibliothek gab es ein Regal, das gestern noch nicht da war ...',
            'Fußspuren kamen aus dem Meer und endeten vor der Haustür ...',
            'Der älteste Baum im Park hatte an diesem Morgen eine Tür ...',
            'Ein Paket kam ohne Adresse, mit einem Loch an der Seite ...',
            'Die Schulglocke läutete eine Stunde zu früh, und niemand hatte sie berührt ...',
            'Jemand hatte auf die letzte Seite des Hefts eine Karte gezeichnet ...',
            'Alle Vögel verließen die Stadt am selben Nachmittag ...',
            'Ein Fenster, das seit Jahren klemmte, ging von selbst auf ...',
        ]],
    ],

    // --------------------------------------------------------------- ENGLISH
    // In German this is German grammar: its own plurals and past tenses.
    'eng-plural' => [
        'name'    => 'Eins und viele',
        'pattern' => 'Wie heißt die Mehrzahl von „{word}“?',
        'answer'  => 'Die richtige Mehrzahl',
        'patterns' => [
            'Wie heißt „{word}“, wenn es mehrere sind?',
            'Ein „{word}“ - und zwei davon heißen wie?',
        ],
        'hint'    => 'Manche Wörter ändern sich mehr, als man denkt.',
        'lists'   => ['word' => ['Kind', 'Maus', 'Blatt', 'Fuß', 'Buch',
                                 'Messer', 'Gans', 'Haus', 'Zahn', 'Baby',
                                 'Mann', 'Frau', 'Schaf', 'Wolf', 'Stadt',
                                 'Kirche', 'Hälfte', 'Mensch', 'Apfel', 'Kartoffel']],
    ],
    'eng-verb' => [
        'name'    => 'Gestern',
        'pattern' => 'Setz den Satz in die Vergangenheit: „Jeden Tag {verb} ich.“',
        'answer'  => 'Die richtige Vergangenheitsform von „{verb}“',
        'patterns' => [
            '„Jeden Tag {verb} ich“ - sag es so, als wäre es gestern gewesen.',
            'Ändere „ich {verb}“ so, dass es von früher erzählt.',
        ],
        'hint'    => 'Sag es so, als wäre es schon passiert.',
        'lists'   => ['verb' => ['laufe', 'schwimme', 'esse', 'schreibe', 'singe',
                                 'denke', 'bringe', 'fange', 'male', 'fliege',
                                 'gehe', 'nehme', 'gebe', 'schlafe', 'kaufe',
                                 'lese', 'trage', 'baue', 'finde', 'trinke']],
    ],
    'eng-describe' => [
        'name'    => 'Beschreib es',
        'pattern' => 'Beschreibe {thing} jemandem, der so etwas noch nie gesehen hat - ohne das Wort zu benutzen.',
        'answer'  => 'Jede klare Beschreibung',
        'patterns' => [
            'Erkläre, was {thing} ist, ohne das Wort zu sagen.',
            'Jemand hat {thing} noch nie gesehen. Beschreib es ihm.',
        ],
        'hint'    => 'Fang damit an, wozu man es braucht.',
        'lists'   => ['thing' => ['ein Fahrrad', 'einen Regenschirm', 'einen Wasserkocher', 'eine Treppe',
                                  'ein Teleskop', 'eine Sandburg', 'eine Windmühle', 'einen Drachen',
                                  'einen Leuchtturm', 'eine Schubkarre', 'einen Reißverschluss',
                                  'einen Spiegel', 'eine Leiter', 'eine Uhr', 'einen Schwamm',
                                  'eine Trillerpfeife', 'einen Schnürsenkel', 'einen Schneemann']],
    ],

    // --------------------------------------------------------------- SCIENCE
    'sci-sense' => [
        'name'    => 'Welcher Sinn?',
        'pattern' => 'Welchen Körperteil brauchst du, um {sense}?',
        'answer'  => 'Das passende Sinnesorgan',
        'patterns' => [
            'Du willst {sense}. Welcher Teil von dir macht die Arbeit?',
            'Welchen Sinn brauchst du, um {sense}?',
            'Zeig auf den Teil von dir, mit dem du {sense} kannst.',
            'Ohne welchen Körperteil könntest du nicht {sense}?',
            '{sense} - welcher Sinn ist das?',
            'Nenne den Körperteil, der arbeitet, wenn du {sense} willst.',
            'Halt den Teil zu, mit dem du {sense} würdest. Welcher ist es?',
        ],
        'hint'    => 'Zeig darauf.',
        'lists'   => ['sense' => ['an einer Blume zu riechen', 'eine Glocke zu hören',
                                  'Honig zu schmecken', 'einen Regenbogen zu sehen',
                                  'warmen Sand zu spüren', 'Donner zu hören',
                                  'eine Zitrone zu schmecken', 'nachts einen Stern zu sehen',
                                  'frisches Brot zu riechen', 'eine kalte Scheibe zu spüren',
                                  'deinen eigenen Namen zu hören', 'Salz zu schmecken',
                                  'die Farbe Rot zu sehen', 'eine schnurrende Katze zu spüren']],
    ],
    'sci-float' => [
        'name'    => 'Schwimmt es oder geht es unter?',
        'pattern' => 'Würde {thing} im Wasser schwimmen oder untergehen? Sag, warum du das denkst.',
        'answer'  => 'Beides gilt, wenn eine Begründung dabei ist',
        'patterns' => [
            'Du legst {thing} ins Wasser. Schwimmt es oder geht es unter? Warum?',
            'Bliebe {thing} oben auf dem Wasser oder ginge es unter? Sag warum.',
            'Was würde {thing} in einer Schüssel Wasser machen? Sag warum.',
            'Schwimmt oder sinkt: {thing}? Nenne einen Grund.',
            'Würdest du erwarten, dass {thing} oben bleibt oder untergeht?',
            'Leg {thing} in die Badewanne. Was passiert?',
            'Schwer für seine Größe oder leicht? Würde {thing} schwimmen?',
        ],
        'hint'    => 'Denk daran, wie schwer es für seine Größe ist.',
        'lists'   => ['thing' => ['ein Korken', 'ein Stein', 'ein Apfel', 'eine Münze', 'eine Feder',
                                  'ein Schwamm', 'ein Nagel', 'eine Kerze', 'eine Orange',
                                  'ein Holzlöffel', 'eine Weintraube', 'eine verschlossene Plastikflasche',
                                  'eine Büroklammer', 'eine Zitrone', 'eine Gummiente', 'ein Ziegelstein',
                                  'ein Bleistift', 'eine Murmel']],
    ],
    'sci-change' => [
        'name'    => 'Was passiert dann?',
        'pattern' => 'Was passiert, wenn {event}? Erkläre es so gut du kannst.',
        'answer'  => 'Eine sinnvolle Erklärung',
        'patterns' => [
            'Sag, was du sehen würdest, wenn {event}.',
            '{event} - was passiert dann, und warum?',
            'Sag voraus, was passiert, wenn {event}.',
            'Jemand sagt, {event}. Was würdest du wohl sehen?',
            'Beschreib, was sich ändert, wenn {event}.',
            'Was würdest du als Erstes bemerken, wenn {event}?',
            'Erkläre Schritt für Schritt, was passiert, wenn {event}.',
        ],
        'hint'    => 'Sag, was du sehen würdest, und dann warum.',
        'lists'   => ['event' => [
            'du einen Eiswürfel in einem warmen Zimmer liegen lässt',
            'eine Pflanze in einem dunklen Schrank steht',
            'du deine Hände schnell aneinander reibst',
            'man Salz in ein Glas Wasser rührt',
            'ein Luftballon in der Sonne liegt',
            'eine Pfütze den ganzen Vormittag in der Sonne steht',
            'du eine kalte Fensterscheibe anhauchst',
            'ein aufgeschnittener Apfel auf dem Tisch liegen bleibt',
            'du einen Magneten neben einen Haufen Büroklammern hältst',
            'ein Fahrrad einen Monat lang im Regen steht',
            'du einen Stein und eine Feder gleichzeitig fallen lässt',
            'man ein Glas über eine brennende Kerze stülpt',
            'nasse Wäsche an einem windigen Tag draußen hängt',
            'du eine Flasche mit Wasser und Öl schüttelst',
            'ein Samenkorn eingepflanzt und jeden Tag gegossen wird',
        ]],
    ],

    // ---------------------------------------------------------------- NATURE
    'nature-animal' => [
        'name'    => 'Tierstimmen',
        'pattern' => 'Welches Geräusch macht {animal}? Mach es so gut nach, wie du kannst!',
        'answer'  => 'Jeder gute Versuch zählt',
        'patterns' => [
            'Mach das Geräusch nach, das {animal} macht.',
            '{animal} steht hinter dir. Was würdest du hören?',
            'Alle Augen zu - und jetzt mach {animal} nach.',
            'Welches Geräusch würde dir sagen, dass {animal} in der Nähe ist?',
            'Mach {animal} nach. Wie klingt das?',
            'Wenn {animal} sprechen könnte - was käme zuerst? Mach das Geräusch.',
            'Welches Tier macht dieses Geräusch? Mach {animal}.',
        ],
        'hint'    => 'Hier gibt niemand Noten.',
        'lists'   => ['animal' => ['eine Kuh', 'eine Ente', 'ein Löwe', 'ein Schaf', 'eine Eule',
                                   'ein Frosch', 'ein Pferd', 'eine Biene', 'eine Katze',
                                   'ein Wolf', 'eine Ziege', 'eine Krähe', 'ein Schwein', 'ein Esel',
                                   'ein Huhn', 'eine Maus', 'eine Schlange', 'ein Elefant',
                                   'ein Hund', 'eine Möwe', 'ein Affe', 'eine Grille']],
    ],
    'nature-home' => [
        'name'    => 'Wo wohnt es?',
        'pattern' => 'Wo wohnt {animal}?',
        'answer'  => 'Die richtige Art von Zuhause',
        'patterns' => [
            'Was für ein Zuhause hat {animal}?',
            'Wenn du {animal} suchen würdest, wo würdest du nachsehen?',
            'Nenne den Ort, den {animal} sein Zuhause nennt.',
            'Würdest du {animal} unter der Erde, in einem Baum oder im Wasser finden?',
            'Mal in die Luft, wo {animal} schläft.',
            '{animal} braucht einen sicheren Platz. Wohin geht es?',
            'Wo würdest du ein Haus für {animal} bauen?',
        ],
        'hint'    => 'Denk daran, was es braucht, um sicher zu sein.',
        'lists'   => ['animal' => ['eine Biene', 'ein Kaninchen', 'ein Pinguin', 'ein Kamel', 'ein Fisch',
                                   'eine Eule', 'ein Maulwurf', 'eine Krabbe', 'eine Fledermaus',
                                   'ein Eichhörnchen', 'ein Eisbär', 'ein Känguru', 'eine Spinne',
                                   'ein Biber', 'eine Ameise', 'eine Schwalbe', 'eine Schildkröte',
                                   'ein Dachs', 'ein Delfin', 'ein Igel']],
    ],
    'nature-season' => [
        'name'    => 'Die Jahreszeiten',
        'pattern' => 'Nenne zwei Dinge, die {season} passieren. Schau {aspect}.',
        'answer'  => 'Zwei sinnvolle Antworten',
        'patterns' => [
            'Denk an die Zeit {season}. Nenne zwei Dinge, die sich {aspect} ändern.',
            'Was ist {season} anders {aspect}? Nenne zwei Dinge.',
            'Zwei Dinge, die {season} {aspect} anders sind - nenne sie.',
            '{season}: Was würdest du {aspect} bemerken?',
            'Nenne zwei Veränderungen, die {season} {aspect} kommen.',
            'Was ist {season} {aspect} los?',
            'Stell dir die Zeit {season} vor. Nenne zwei Dinge, die {aspect} passieren.',
        ],
        'hint'    => 'Denk an das Wetter und an die Pflanzen.',
        'lists'   => ['season' => ['im Frühling', 'im Sommer', 'im Herbst', 'im Winter'],
                      'aspect' => ['beim Wetter', 'bei den Bäumen', 'bei den Tieren',
                                   'bei der Kleidung', 'im Garten']],
    ],
    'nature-chain' => [
        'name'    => 'Wer frisst was',
        'pattern' => 'Was frisst {animal} wohl, und wer frisst es vielleicht?',
        'answer'  => 'Eine sinnvolle Nahrungskette',
        'patterns' => [
            '{animal} frisst etwas, und etwas frisst {animal}. Was denn?',
            'Wo steht {animal} in der Nahrungskette? Sag, was darüber und darunter kommt.',
            'Was ist das Abendessen von {animal}, und wessen Abendessen ist {animal}?',
            'Setz {animal} in eine Nahrungskette. Was kommt davor und danach?',
            'Vor wem sollte sich {animal} in Acht nehmen?',
            'Nenne etwas, das {animal} frisst, und etwas, das es frisst.',
            '{animal} steht mitten in einer Kette. Füll beide Enden aus.',
        ],
        'hint'    => 'Jedes Tier ist das Abendessen von jemandem.',
        'lists'   => ['animal' => ['eine Maus', 'ein Frosch', 'ein Kaninchen', 'ein Fisch',
                                   'eine Raupe', 'ein Spatz', 'ein Regenwurm', 'eine Schnecke',
                                   'ein Grashüpfer', 'ein Entenküken', 'ein Eichhörnchen',
                                   'ein Marienkäfer', 'eine Garnele', 'eine Feldmaus',
                                   'eine junge Eule', 'eine Kaulquappe']],
    ],

    // ----------------------------------------------------------------- LOGIC
    'logic-odd' => [
        'name'    => 'Was passt nicht?',
        'pattern' => 'Was passt hier nicht dazu: {set}? Sag warum.',
        'answer'  => 'Jede Antwort mit guter Begründung',
        'patterns' => [
            'Eines passt nicht zu den anderen: {set}. Welches, und warum?',
            '{set}: Streich eines und sag, was die anderen gemeinsam haben.',
        ],
        'hint'    => 'Es kann mehr als eine richtige Antwort geben.',
        'lists'   => ['set' => [
            'Apfel, Banane, Karotte, Birne',
            'Hund, Katze, Fisch, Kaninchen',
            'rot, blau, Quadrat, grün',
            'Schuh, Socke, Hut, Löffel',
            'Auto, Boot, Fahrrad, Baum',
            'Löffel, Gabel, Messer, Bleistift',
            'Regen, Schnee, Nebel, Berg',
            'zwei, vier, sieben, sechs',
            'Gitarre, Trommel, Gemälde, Klavier',
            'Montag, Dienstag, Juli, Freitag',
            'Stuhl, Tisch, Wolke, Bett',
            'Löwe, Tiger, Kuh, Leopard',
            'Auge, Ohr, Nase, Handschuh',
            'Fluss, See, Meer, Wüste',
            'Fußball, Tennis, Schach, Schwimmen',
            'Eiche, Kiefer, Rose, Birke',
            'Hammer, Säge, Apfel, Schraubenzieher',
            'Kreis, Dreieck, rot, Quadrat',
        ]],
    ],
    'logic-seq' => [
        'name'    => 'Wie geht es weiter?',
        'pattern' => 'Welche Zahl kommt als Nächstes: {a}, {b}, {c}, ... ?',
        'answer'  => 'Die Zahl, die die Reihe fortsetzt',
        'patterns' => [
            'Führe die Reihe fort: {a}, {b}, {c}, ...',
            '{a}, {b}, {c} - welche Zahl kommt danach?',
        ],
        'hint'    => 'Finde heraus, wie groß der Schritt dazwischen ist.',
    ],
    'logic-riddle' => [
        'name'    => 'Rätsel',
        'pattern' => '{riddle}',
        'answer'  => 'Die Lösung des Rätsels',
        'patterns' => [
            'Hier ist ein Rätsel. {riddle}',
            'Versuch mal dieses hier: {riddle}',
        ],
        'hint'    => 'Lies es zweimal - der Trick steckt in den Worten.',
        'lists'   => ['riddle' => [
            'Ich habe Zeiger, aber keine Hände. Was bin ich?',
            'Je mehr ich trockne, desto nasser werde ich. Was bin ich?',
            'Ich habe Tasten, aber öffne kein Schloss. Was bin ich?',
            'Je mehr du von mir wegnimmst, desto größer werde ich. Was bin ich?',
            'Ich gehe hinauf und hinunter und bleibe doch am selben Platz. Was bin ich?',
            'Ich habe ein Gesicht und zwei Zeiger, aber weder Arme noch Beine. Was bin ich?',
            'Ich bin voller Löcher und halte trotzdem Wasser. Was bin ich?',
            'Ich folge dir den ganzen Tag und verschwinde nachts. Was bin ich?',
            'Ich habe einen Hals, aber keinen Kopf. Was bin ich?',
            'Je mehr es von mir gibt, desto weniger siehst du. Was bin ich?',
            'Ich habe Zähne, aber esse nichts. Was bin ich?',
            'Jung bin ich lang, alt bin ich kurz. Was bin ich?',
            'Ich habe Blätter, bin aber kein Baum. Was bin ich?',
            'Man kann mich fangen, aber nicht werfen. Was bin ich?',
            'Ich komme herunter, gehe aber nie hinauf. Was bin ich?',
            'Ich habe ein Bett, schlafe aber nie, und einen Mund, esse aber nie. Was bin ich?',
            'Ich habe ein Auge und sehe doch nichts. Was bin ich?',
            'Was muss man zerbrechen, bevor man es benutzen kann?',
        ]],
    ],

    // ------------------------------------------------------------ LIFE SKILLS
    'life-kind' => [
        'name'    => 'Etwas Nettes',
        'pattern' => 'Nenne eine nette Sache, die du heute für {who} tun könntest.',
        'answer'  => 'Jede nette Idee zählt',
        'patterns' => [
            'Denk dir etwas Nettes aus, das du für {who} tun könntest.',
            'Wie könntest du {who} heute eine Freude machen?',
        ],
        'hint'    => 'Auch kleine Sachen zählen.',
        'lists'   => ['who' => ['einen Freund', 'jemanden aus deiner Familie', 'einen Nachbarn',
                                'ein neues Kind in der Klasse', 'jemanden, der traurig ist',
                                'ein jüngeres Kind', 'jemanden, der dir letzte Woche geholfen hat',
                                'eine Lehrerin oder einen Lehrer', 'jemanden, der allein isst',
                                'ein Großelternteil', 'jemanden, der krank ist',
                                'die Person neben dir', 'jemanden mit vollen Händen',
                                'jemanden, der gerade verloren hat',
                                'jemanden, mit dem du dich gestritten hast',
                                'jemanden, der neu im Land ist']],
    ],
    'life-safe' => [
        'name'    => 'Sicher bleiben',
        'pattern' => 'Was solltest du tun, wenn {situation}?',
        'answer'  => 'Jede vernünftige, sichere Antwort',
        'patterns' => [
            '{situation} - was machst du als Erstes?',
            'Stell dir vor, {situation}. Was ist das Sicherste, was du tun kannst?',
        ],
        'hint'    => 'Eine vertraute erwachsene Person zu suchen, ist meist der erste Schritt.',
        'lists'   => ['situation' => [
            'du im Geschäft deine erwachsene Begleitung verlierst',
            'eine fremde Person dich bittet mitzukommen',
            'es zu Hause verbrannt riecht',
            'du siehst, dass jemandem wehgetan wird',
            'dir in der Schule schlecht wird',
            'du dir in den Finger schneidest und es nicht aufhört zu bluten',
            'der Feueralarm losgeht, während du oben bist',
            'dich jemand im Internet fragt, wo du wohnst',
            'du eine Packung Tabletten auf dem Boden findest',
            'dein Ball auf die Straße rollt',
            'beim Radfahren die Bremsen nicht mehr gehen',
            'ein fremder Hund auf dich zurennt',
            'du dich auf dem Heimweg verläufst',
            'dir jemand Nachrichten schickt, die dich trauriger machen',
            'du als Erste jemanden findest, der gestürzt ist',
        ]],
    ],
    'life-choice' => [
        'name'    => 'Was würdest du tun?',
        'pattern' => 'Was würdest du tun, wenn {situation}?',
        'answer'  => 'Es gibt keine einzig richtige Antwort - sei einfach freundlich',
        'patterns' => [
            'Stell dir vor, {situation}. Was machst du dann?',
            '{situation} - besprich es mit den anderen. Wofür würdest du dich entscheiden?',
        ],
        'hint'    => 'Sag, was du tun würdest, und warum.',
        'lists'   => ['situation' => [
            'ein Freund die Schuld für etwas auf sich nimmt, das du getan hast',
            'du deine Hausaufgaben vergessen hast',
            'du etwas findest, das jemand anderem gehört',
            'du denselben Nachmittag zwei Leuten versprochen hast',
            'jemand deine Arbeit abschreibt und dafür gelobt wird',
            'du etwas kaputt machst und niemand es sieht',
            'du im Laden zu viel Wechselgeld zurückbekommst',
            'deine Mannschaft jemanden nicht mitspielen lassen will',
            'ein Freund dir ein Geheimnis erzählt, das dir Sorgen macht',
            'du gerade gewinnst und dein Freund aufhören will',
            'jemand sich über die Sprache eines anderen Kindes lustig macht',
            'du etwas gefragt wirst und die Antwort nicht weißt',
            'ein Freund deine Hausaufgaben abschreiben will',
            'du beim Spielen aus Versehen jemandem wehtust',
            'du ein Geschenk bekommst, das dir nicht gefällt',
            'du siehst, wie jemandem Geld hinfällt, ohne es zu merken',
        ]],
    ],

    // ------------------------------------------------------------- GEOGRAPHY
    'geo-where' => [
        'name'    => 'Nah und fern',
        'pattern' => 'Würdest du {thing} in der Nähe deines Zuhauses finden oder weit weg?',
        'answer'  => 'Beides geht, mit einer Begründung',
        'patterns' => [
            'Ist {thing} eher etwas aus der Nähe oder von weit weg?',
            '{thing}: in der Nähe deines Zuhauses oder weit weg? Warum?',
        ],
        'hint'    => 'Denk daran, was es rund um deinen Wohnort gibt.',
        'lists'   => ['thing' => ['einen Berg', 'einen Strand', 'einen Fluss', 'eine Wüste',
                                  'einen Wald', 'einen Hafen', 'einen Vulkan', 'einen Bauernhof',
                                  'einen Bahnhof', 'einen Gletscher', 'einen See', 'eine Insel',
                                  'einen Kanal', 'einen Regenwald', 'einen Wasserfall', 'eine Höhle',
                                  'eine Brücke über ein Tal', 'ein Weizenfeld']],
    ],
    'geo-direction' => [
        'name'    => 'In welche Richtung?',
        'pattern' => 'Du schaust nach {direction} und drehst dich {turn}. Wohin schaust du jetzt?',
        'answer'  => 'Die Richtung {turn} von {direction}',
        'patterns' => [
            'Schau nach {direction} und dreh dich dann {turn}. Wohin schaust du jetzt?',
            'Du schaust nach {direction}. Du drehst dich {turn} - welche Richtung ist das?',
        ],
        'hint'    => 'Stell dir einen Kompass vor, oder nimm die Hände zu Hilfe.',
        'lists'   => ['direction' => ['Norden', 'Süden', 'Osten', 'Westen'],
                      'turn'      => ['nach rechts', 'nach links', 'zweimal nach rechts',
                                      'einmal ganz herum']],
    ],
    'geo-place' => [
        'name'    => 'Orte auf der Erde',
        'pattern' => 'Nenne ein Land, in dem du {feature} erwarten würdest, und sag warum.',
        'answer'  => 'Jedes passende Land, mit einer Begründung',
        'patterns' => [
            'Welches Land hätte {feature}? Sag, woher du das weißt.',
            'Wohin auf der Welt würdest du fahren, um {feature} zu sehen?',
        ],
        'hint'    => 'Denk daran, wie warm oder kalt es dort ist.',
        'lists'   => ['feature' => ['einen Regenwald', 'eine Wüste', 'das ganze Jahr Schnee',
                                    'aktive Vulkane', 'Korallenriffe', 'sehr lange Flüsse',
                                    'wild lebende Pinguine', 'Olivenhaine', 'Tee an Hängen',
                                    'Rentierhirten', 'sehr hohe Berge mit Bergsteigern',
                                    'Kanäle statt Straßen', 'wilde Elefanten', 'Fjorde',
                                    'überall Windmühlen', 'eine sehr lange Mauer']],
    ],
    // ------------------------------------------------------- NEUE AUFGABEN
    'sci-hotcold' => [
        'name'    => 'Heiß oder kalt?',
        'pattern' => 'Ist {thing} normalerweise heiß oder kalt?',
        'answer'  => 'Beides gilt, wenn eine Begründung dabei ist',
        'patterns' => [
            'Würde sich {thing} warm oder kalt anfühlen?',
            'Warm oder kalt: {thing}?',
            'Heiß, kalt oder dazwischen: {thing}?',
            'Wenn du {thing} anfassen würdest, was würdest du spüren?',
            'Ist {thing} etwas, worauf man pustet, damit es kühler wird?',
            'Würde {thing} deine Hände wärmen oder kalt machen?',
            'Leg {thing} auf die warme oder die kalte Seite des Tisches.',
        ],
        'hint'    => 'Stell dir vor, du fasst es an.',
        'lists'   => ['thing' => ['ein Eis', 'eine Suppe', 'Schnee', 'eine Heizung', 'das Meer im Winter',
                                  'eine Tasse Tee', 'das Innere des Kühlschranks', 'eine Kerzenflamme',
                                  'Sand am Strand im Sommer', 'ein Eiswürfel', 'eine Wärmflasche',
                                  'der Tau am Morgen', 'ein Backofen', 'ein Schneeball', 'warme Milch',
                                  'ein Gefrierschrank', 'eine Mauer in der Sonne',
                                  'Wasser aus dem kalten Hahn']],
    ],
    'sci-living' => [
        'name'    => 'Lebt es?',
        'pattern' => 'Lebt {thing}? Woran erkennst du das?',
        'answer'  => 'Die richtige Antwort mit einer sinnvollen Begründung',
        'patterns' => [
            'Würdest du sagen, {thing} lebt? Warum?',
            'Lebendig oder nicht: {thing}? Nenne einen Grund.',
            'Wächst {thing}, isst und atmet es? Lebt es?',
            'Lebendig oder nie lebendig gewesen: {thing}?',
            'Nenne einen Grund, warum {thing} lebt oder nicht lebt.',
            'Würde eine Forscherin {thing} ein Lebewesen nennen?',
            '{thing}: Braucht es Essen und Wasser, um weiterzumachen?',
        ],
        'hint'    => 'Was lebt, wächst und braucht etwas zum Weitermachen.',
        'lists'   => ['thing' => ['ein Baum', 'ein Stein', 'eine Katze', 'eine Wolke', 'ein Pilz',
                                  'ein Fahrrad', 'ein Regenwurm', 'ein Fluss', 'ein Gänseblümchen',
                                  'ein Teddybär', 'eine Spinne', 'eine Kerze', 'Gras',
                                  'eine Muschel', 'eine Biene', 'eine Pfütze', 'ein Samenkorn',
                                  'ein Spielzeugroboter']],
    ],
    'logic-same' => [
        'name'    => 'Was ist gleich?',
        'pattern' => 'Was haben {pair} gemeinsam?',
        'answer'  => 'Jede sinnvolle Gemeinsamkeit',
        'patterns' => [
            '{pair}: Nenne eine Sache, die beide teilen.',
            'Denk an {pair}. Was ist bei beiden gleich?',
        ],
        'hint'    => 'Denk daran, wozu man sie braucht oder woraus sie sind.',
        'lists'   => ['pair' => ['ein Fahrrad und ein Auto', 'ein Apfel und eine Banane',
                                 'ein Hund und ein Wolf', 'Regen und Schnee', 'ein Stuhl und ein Bett',
                                 'ein Löffel und eine Gabel', 'die Sonne und eine Lampe',
                                 'ein Buch und eine Zeitung', 'ein Fluss und ein See',
                                 'Schuhe und Handschuhe', 'ein Klavier und eine Gitarre',
                                 'ein Baum und eine Blume', 'ein Flugzeug und ein Vogel',
                                 'eine Uhr und ein Kalender', 'ein Messer und eine Säge',
                                 'ein Boot und eine Ente']],
    ],
    'logic-order' => [
        'name'    => 'Vom Kleinsten zum Größten',
        'pattern' => 'Bring sie in die Reihenfolge, das Kleinste zuerst: {set}.',
        'answer'  => 'Die drei in der richtigen Reihenfolge',
        'patterns' => [
            'Vom Kleinsten zum Größten: {set}. Sag sie der Reihe nach.',
            '{set}: Was ist am kleinsten, was am größten?',
        ],
        'hint'    => 'Stell sie dir nebeneinander vor.',
        'lists'   => ['set' => ['eine Ameise, ein Hund, ein Elefant', 'eine Tasse, ein Eimer, eine Badewanne',
                                'eine Minute, eine Stunde, ein Tag', 'ein Kiesel, ein Felsen, ein Berg',
                                'ein Samenkorn, eine Blume, ein Baum', 'ein Schuh, ein Auto, ein Haus',
                                'ein Tropfen, eine Pfütze, ein See', 'eine Münze, ein Teller, ein Tisch',
                                'eine Maus, eine Katze, ein Pferd', 'ein Blatt, ein Ast, ein Stamm',
                                'ein Schritt, eine Straße, ein Land',
                                'ein Löffel, eine Schaufel, ein Bagger',
                                'ein Baby, ein Kind, ein Erwachsener', 'ein Knopf, ein Teller, ein Rad',
                                'eine Kerze, eine Laterne, ein Turm',
                                'eine Schneeflocke, ein Schneeball, ein Schneemann']],
    ],
    'logic-truefalse' => [
        'name'    => 'Richtig oder falsch?',
        'pattern' => 'Richtig oder falsch: {claim}? Sag warum.',
        'answer'  => 'Die richtige Antwort mit einer Begründung',
        'patterns' => [
            'Stimmt das oder nicht: {claim}? Erkläre es.',
            'Jemand sagt, {claim}. Bist du einverstanden? Sag warum.',
        ],
        'hint'    => 'Ein einziges Gegenbeispiel genügt, damit es falsch ist.',
        'lists'   => ['claim' => ['alle Vögel können fliegen', 'jedes Quadrat ist auch ein Rechteck',
                                  'alle Fische leben im Wasser', 'alle Spinnen haben sechs Beine',
                                  'die Sonne geht im Westen auf', 'manche Katzen haben keinen Schwanz',
                                  'jedes Dreieck hat drei Seiten', 'Eis ist schwerer als Wasser',
                                  'jeder Monat hat dreißig Tage', 'alle Pflanzen haben Blüten',
                                  'ein Wal ist ein Fisch', 'keine Zahl ist gerade und ungerade zugleich']],
    ],
    'geo-hotcold' => [
        'name'    => 'Warmes oder kaltes Land?',
        'pattern' => 'Bräuchtest du {thing} in einem warmen oder in einem kalten Land?',
        'answer'  => 'Beides gilt, mit einer Begründung',
        'patterns' => [
            '{thing}: Würdest du das für ein warmes oder ein kaltes Land einpacken?',
            'Warmes oder kaltes Land: Wo brauchst du {thing}?',
        ],
        'hint'    => 'Denk daran, was du am kältesten Tag des Jahres anziehst.',
        'lists'   => ['thing' => ['eine Wollmütze', 'eine Sonnenbrille', 'einen Schal', 'Sandalen',
                                  'einen dicken Mantel', 'einen Sonnenhut', 'Handschuhe',
                                  'einen Ventilator', 'Schneestiefel', 'einen Badeanzug',
                                  'eine warme Decke', 'kurze Hosen', 'ein heißes Getränk',
                                  'Schlittschuhe', 'ein kaltes Getränk', 'Sonnencreme']],
    ],
    'geo-travel' => [
        'name'    => 'Wie kommst du hin?',
        'pattern' => 'Wie würdest du {place} reisen?',
        'answer'  => 'Jede sinnvolle Art zu reisen',
        'patterns' => [
            'Plane die Reise {place}. Womit fährst du?',
            'Wie kommen Leute {place}?',
        ],
        'hint'    => 'Zu manchen Orten braucht es mehr als eine Reise.',
        'lists'   => ['place' => ['zu einer Insel draußen im Meer', 'auf einen Berggipfel',
                                  'zum Laden am Ende der Straße', 'in ein weit entferntes Land',
                                  'zu einem Bauernhof hinter den Feldern', 'in die Mitte eines großen Sees',
                                  'in eine Stadt auf der anderen Flussseite', 'zum Mond',
                                  'in ein Dorf oben auf einem steilen Berg', 'an den Strand',
                                  'in eine Höhle', 'mitten in einen Wald', 'in eine große Stadt',
                                  'zu einem Leuchtturm auf den Felsen', 'in die Nachbarstraße',
                                  'zu einem Flughafen']],
    ],
    'geo-difference' => [
        'name'    => 'Wo ist der Unterschied?',
        'pattern' => 'Was ist der Unterschied zwischen {pair}?',
        'answer'  => 'Jeder klare Unterschied',
        'patterns' => [
            '{pair}: Woran erkennt man den Unterschied?',
            'Erkläre, was {pair} unterscheidet.',
        ],
        'hint'    => 'Die Größe ist eine Antwort, aber nicht die einzige.',
        'lists'   => ['pair' => ['einem See und einem Meer', 'einem Hügel und einem Berg',
                                 'einem Dorf und einer Stadt', 'einem Fluss und einem Kanal',
                                 'einer Insel und einer Halbinsel', 'einem Wäldchen und einem Wald',
                                 'einer Straße und einer Autobahn', 'einem Bach und einem Strom',
                                 'einem Strand und einer Klippe', 'einem Bauernhof und einem Feld',
                                 'einer Karte und einem Globus', 'einem Land und einem Kontinent']],
    ],
    'eng-article' => [
        'name'    => 'Der, die oder das?',
        'pattern' => 'Heißt es "der", "die" oder "das" vor "{word}"?',
        'answer'  => 'Der richtige Artikel',
        'patterns' => [
            '„{word}“ - der, die oder das?',
            'Sag „{word}“ mit dem richtigen Artikel davor.',
        ],
        'hint'    => 'Sprich es laut mit allen dreien und hör, was passt.',
        'lists'   => ['word' => ['Apfel', 'Buch', 'Baum', 'Tisch', 'Wasser', 'Hand',
                                 'Tag', 'Problem', 'Blume', 'Auto', 'Milch', 'Karte',
                                 'Nase', 'Hund', 'Klasse', 'Sofa']],
    ],
    'eng-question' => [
        'name'    => 'Mach eine Frage daraus',
        'pattern' => 'Mach aus diesem Satz eine Frage: „{sentence}“',
        'answer'  => 'Dieselben Wörter, als Frage',
        'patterns' => [
            'Frag es, statt es zu sagen: „{sentence}“',
            '„{sentence}“ - mach eine Frage daraus.',
        ],
        'hint'    => 'Oft musst du nur die ersten beiden Wörter tauschen.',
        'lists'   => ['sentence' => ['Du hast Hunger.', 'Sie kann schwimmen.', 'Sie sind nach Hause gegangen.',
                                     'Es regnet.', 'Er hat ein Fahrrad.', 'Wir sind spät dran.',
                                     'Der Hund schläft.', 'Du magst Äpfel.',
                                     'Gestern war es kalt.', 'Sie sind fertig.',
                                     'Sie hat den Schlüssel gefunden.', 'Der Bus kommt.',
                                     'Du kannst mich hören.', 'Er war in der Schule.',
                                     'Der Kuchen ist alle.', 'Wir haben genug.']],
    ],
    'nature-baby' => [
        'name'    => 'Tierkinder',
        'pattern' => 'Wie nennt man das Junge {animal}?',
        'answer'  => 'Der richtige Name für das Junge',
        'patterns' => [
            '{animal} bekommt ein Junges. Wie heißt es?',
            'Welchen Namen geben wir dem Jungen {animal}?',
            'Wie heißt das Junge {animal}?',
            '{animal} hat gerade ein Junges bekommen. Wie nennen wir es?',
            'Sag den besonderen Namen für das Junge {animal}, falls es einen gibt.',
            'Welches Wort benutzen Bauern für das Junge {animal}?',
            'Ein ganz kleines Junges {animal} - wie heißt es?',
        ],
        'hint'    => 'Manche haben einen eigenen Namen, manche heißen einfach „Junges“.',
        'lists'   => ['animal' => ['von der Katze', 'vom Hund', 'von der Kuh', 'vom Schaf',
                                   'von der Ente', 'vom Pferd', 'vom Frosch', 'vom Bären',
                                   'von der Ziege', 'vom Huhn', 'vom Schwein', 'vom Schwan',
                                   'vom Hirsch', 'vom Känguru', 'vom Schmetterling', 'von der Eule']],
    ],
    'nature-need' => [
        'name'    => 'Was braucht es?',
        'pattern' => 'Nenne zwei Dinge, die {living} zum Leben braucht.',
        'answer'  => 'Zwei sinnvolle Bedürfnisse',
        'patterns' => [
            '{living}: Nenne zwei Dinge, ohne die es nicht leben kann.',
            'Was bräuchte {living}, wenn du es versorgen würdest?',
            'Was müsstest du {living} geben, damit es am Leben bleibt?',
            'Zwei Dinge, ohne die {living} nicht auskommt - nenne sie.',
            'Wenn du dich um {living} kümmern würdest, was bräuchte es?',
            '{living} ist in deiner Obhut. Nenne zwei Dinge, die es haben muss.',
            'Ohne welche zwei Dinge würde {living} nicht überleben?',
        ],
        'hint'    => 'Essen und Wasser sind zwei - und was noch?',
        'lists'   => ['living' => ['ein Baum', 'ein Hund', 'ein Fisch', 'eine Biene', 'ein Mensch',
                                   'eine Topfpflanze', 'ein Vogel', 'ein Regenwurm', 'ein Pferd',
                                   'eine Katze', 'eine Sonnenblume', 'ein Frosch', 'ein Kaninchen',
                                   'ein Pilz']],
    ],
    'life-tidy' => [
        'name'    => 'Wohin gehört es?',
        'pattern' => 'Wohin gehört {thing}, wenn du aufräumst?',
        'answer'  => 'Jeder sinnvolle Platz',
        'patterns' => [
            'Du räumst auf: Wo ist der Platz für {thing}?',
            '{thing} liegt auf dem Boden. Wohin gehört es?',
        ],
        'hint'    => 'Dorthin, wo du es das nächste Mal suchen würdest.',
        'lists'   => ['thing' => ['deine Schuhe', 'ein schmutziger Teller', 'ein Buch aus der Bücherei',
                                  'deine Jacke', 'der Müll', 'ein Spielzeugauto',
                                  'ein nasses Handtuch', 'schmutzige Socken', 'die Milch',
                                  'ein Bleistift', 'dein Schulranzen', 'eine leere Flasche',
                                  'ein Apfelrest', 'saubere Wäsche', 'matschige Stiefel',
                                  'eine Schere']],
    ],
    'life-before' => [
        'name'    => 'Was kommt zuerst?',
        'pattern' => 'Nenne zwei Dinge, die du erledigen musst, bevor du {activity}.',
        'answer'  => 'Zwei sinnvolle Schritte',
        'patterns' => [
            'Was muss passieren, bevor du {activity}? Nenne zwei Dinge.',
            'Du willst gleich {activity}. Was regelst du zuerst?',
        ],
        'hint'    => 'Denk daran, was schiefginge, wenn du es vergisst.',
        'lists'   => ['activity' => ['schwimmen gehst', 'etwas kochst', 'mit dem Rad losfährst',
                                     'zur Schule aufbrichst', 'Freunde einlädst',
                                     'auf eine lange Wanderung gehst', 'Samen einpflanzt',
                                     'allein mit dem Bus fährst', 'mit den Hausaufgaben anfängst',
                                     'ins Bett gehst', 'ein Tier fütterst', 'deinen Koffer packst']],
    ],
    // Die fünf, die es nur auf Englisch gab
    'life-action' => [
        'name'    => 'Mach es sofort',
        'pattern' => 'Versuche {n} Sekunden lang {action}. Wenn du es schaffst, geht es weiter!',
        'answer'  => 'Die Aufgabe schaffen',
        'patterns' => [
            'Schaffst du es, {n} Sekunden lang {action}? Los!',
            '{n} Sekunden lang {action}. Alle zählen mit.',
        ],
        'hint'    => 'Alle zählen laut mit.',
        'lists'   => ['action' => ['auf einem Bein zu hüpfen', 'auf einem Bein zu stehen',
                                   'so schnell wie möglich zu klatschen', 'dich langsam zu drehen',
                                   'laut zu lachen', 'eine Katze nachzumachen',
                                   'ein Buch auf dem Kopf zu balancieren', 'rückwärts zu gehen',
                                   'deine Zehen zu berühren', 'stillzustehen wie eine Statue',
                                   'ohne den Buchstaben S zu sprechen', 'auf der Stelle zu marschieren']],
    ],
    'life-team' => [
        'name'    => 'Was würdest du tun?',
        'pattern' => 'Was würdest du tun, wenn {situation}? Sag allen einen Weg, damit umzugehen.',
        'answer'  => 'Jede durchdachte Antwort zählt',
        'patterns' => [
            'Angenommen, {situation}. Was ist deine Idee?',
            '{situation} - sag der Runde einen Weg, das zu lösen.',
        ],
        'hint'    => 'Sag, was du zuerst versuchen würdest.',
        'lists'   => ['situation' => ['ein Freund auf dem Schulhof hinfällt',
                                      'sich deine Gruppe auf gar nichts einigen kann',
                                      'du Wasser über den ganzen Tisch schüttest',
                                      'du jemanden ganz allein sitzen siehst',
                                      'jemand bei einem Spiel nicht mitmachen darf',
                                      'zwei Freunde beide anfangen wollen',
                                      'die Regeln unklar sind und ein Streit beginnt',
                                      'jemand allen anderen ständig ins Wort fällt']],
    ],
    'en-word' => [
        'name'    => 'Wörter aus dem Abenteuer',
        'pattern' => 'Was bedeutet das Wort „{word}“? Erkläre es mit deinen eigenen Worten.',
        'answer'  => 'Jede sinnvolle Erklärung zählt',
        'patterns' => [
            'Jemand in deinem Spiel sagt „{word}“. Was meint er damit?',
            'Erkläre „{word}“, als würdest du die Geschichte erzählen.',
        ],
        'hint'    => 'Bau es in einen Satz über dein Spiel ein.',
        'lists'   => ['word' => ['Wald', 'Fluss', 'Berg', 'Schatz', 'Brücke',
                                 'Burg', 'Drache', 'Kompass', 'Insel', 'Reise',
                                 'Mut', 'Freundschaft', 'Hafen', 'Laterne', 'Schiffbruch', 'Karte']],
    ],
    'science-why' => [
        'name'    => 'Warum passiert das?',
        'pattern' => 'Warum {phenomenon}?',
        'answer'  => 'Jede vernünftige Erklärung zählt',
        'patterns' => [
            'Kannst du erklären, warum {phenomenon}?',
            'Jemand fragt: Warum {phenomenon}? Was antwortest du?',
            'Gib deine beste Erklärung: Warum {phenomenon}?',
            'Ein jüngeres Kind fragt, warum {phenomenon}. Was sagst du?',
            'Was ist der Grund dafür, dass {phenomenon}?',
            'Warum glaubst du, dass {phenomenon}?',
            'Erkläre mit deinen Worten, warum {phenomenon}.',
        ],
        'hint'    => 'Sag erst, was dir auffällt, und dann warum du denkst, dass es so ist.',
        'lists'   => ['phenomenon' => ['regnet es', 'gibt es nach dem Regen Regenbögen',
                                       'schmilzt Eis, wenn man es liegen lässt',
                                       'werden die Blätter im Herbst bunt',
                                       'sieht man nachts die Sterne',
                                       'steigen Luftballons mit Helium nach oben',
                                       'sind die Schatten am Nachmittag länger',
                                       'zittern wir, wenn uns kalt ist',
                                       'wird Brot hart, wenn es offen liegt',
                                       'schwimmen Boote',
                                       'ändert der Mond seine Form',
                                       'müssen wir schlafen']],
    ],
    'geo-continent' => [
        'name'    => 'Welcher Kontinent?',
        'pattern' => 'Auf welchem Kontinent liegt {place}?',
        'answer'  => 'Der richtige Kontinent',
        'patterns' => [
            'Auf welchem Kontinent liegt {place} denn?',
            'Zeig auf den Kontinent, zu dem {place} gehört, und nenne ihn.',
        ],
        'hint'    => 'Es gibt sieben zur Auswahl.',
        'lists'   => ['place' => ['Ägypten', 'Brasilien', 'Japan', 'Italien', 'Kenia',
                                  'Kanada', 'Indien', 'Norwegen', 'Peru', 'Vietnam',
                                  'Australien', 'Mexiko', 'Spanien', 'China',
                                  'Marokko', 'Argentinien']],
    ],
    // ------------------------------------------------ MEHR RECHENAUFGABEN
    'math-halve' => [
        'name'    => 'Die Hälfte',
        'pattern' => '{who} teilt {a} {thing} gerecht mit einem Freund. Wie viele bekommt jeder?',
        'answer'  => '{a/2} {thing}',
        'hint'    => 'Gib sie einzeln aus: eins für dich, eins für mich.',
        'lists'   => ['thing' => $things, 'who' => $names],
        'patterns' => [
            'Die Hälfte von {a} {thing} - wie viele sind das?',
            'Teile {a} {thing} in zwei gleich große Stapel. Wie viele sind in einem?',
            '{a} {thing}, gerecht unter zweien geteilt. Wie viele für jeden?',
            'Was ist die Hälfte von {a}?',
            '{who} behält die Hälfte von {a} {thing}. Wie viele sind das?',
            'Zwei Kinder, {a} {thing}, gleich viele für beide. Wie viele?',
            'Halbiere {a} {thing}. Was kommt heraus?',
            'Wenn {a} {thing} in zwei gleiche Teile geteilt werden, wie groß ist ein Teil?',
        ],
    ],
    'math-tens' => [
        'name'    => 'Zehn dazu',
        'pattern' => 'Wie viel ist {a} + 10?',
        'answer'  => '{a+10}',
        'hint'    => 'Nur die Zehnerstelle ändert sich.',
        'patterns' => [
            'Zähl zehn zu {a} dazu.',
            '{a} und zehn mehr - wie viel ist das?',
            'Zehn mehr als {a} ist wie viel?',
            'Fang bei {a} an und spring zehn nach vorn.',
            'Welche Zahl ist zehn größer als {a}?',
            '{a} + 10 = ?',
            'Zähl von {a} aus zehn weiter. Wo landest du?',
            'Wenn du {a} hättest und zehn mehr fändest, wie viele wären es?',
        ],
    ],
    'math-compare' => [
        'name'    => 'Was ist mehr?',
        'pattern' => 'Was ist mehr: {a} oder {b}? Um wie viel?',
        'answer'  => '{a}, um {a-b}',
        'hint'    => 'Zähl von der kleineren Zahl aus weiter.',
        'patterns' => [
            '{a} und {b} - was ist größer, und um wie viel?',
            'Setz das Größer-als-Zeichen zwischen {a} und {b}. In welche Richtung zeigt es?',
            'Um wie viel ist {a} größer als {b}?',
            '{a} oder {b}: Was hättest du lieber, und warum ist es mehr?',
            'Wie groß ist der Unterschied zwischen {a} und {b}?',
            'Zwei Stapel: einer mit {a}, einer mit {b}. Wie viele mehr sind im größeren?',
            'Ist {a} mehr oder weniger als {b}? Sag, um wie viel.',
            'Zähl den Abstand von {b} bis {a}.',
        ],
    ],
    'math-order' => [
        'name'    => 'Bring sie in die Reihe',
        'pattern' => 'Bring sie in die Reihenfolge, die kleinste zuerst: {a}, {b}, {c}.',
        'answer'  => 'Die drei Zahlen der Reihe nach',
        'hint'    => 'Schau zuerst auf die Zehner.',
        'patterns' => [
            'Welche von {a}, {b} und {c} ist am kleinsten? Und dann?',
            'Stell {a}, {b} und {c} von klein nach groß auf.',
            '{a}, {b}, {c} - sag sie stattdessen von groß nach klein.',
            'Sortiere diese drei: {a}, {b}, {c}.',
            'Welche kommt auf dem Zahlenstrahl zuerst: {a}, {b} oder {c}?',
            'Ordne {a}, {b} und {c} von der kleinsten zur größten.',
            'Zeig auf die größte von {a}, {b} und {c}, dann auf die kleinste.',
            'Drei Zahlen: {a}, {b}, {c}. Welche steht in der Mitte?',
        ],
    ],
    'math-repeat' => [
        'name'    => 'In {b}er-Schritten',
        'pattern' => 'Zähle von {a} aus in {b}er-Schritten. Sag die nächsten drei Zahlen.',
        'answer'  => '{a+b}, {a+b+b}, {a+b+b+b}',
        'hint'    => 'Sag jede Zahl laut, bevor du weiterzählst.',
        'patterns' => [
            'Fang bei {a} an und zähl immer {b} dazu. Welche drei kommen als Nächstes?',
            '{a}, dann {b} mehr, und noch einmal {b}. Sag sie.',
            'Mach drei Sprünge von {b} ab {a}.',
            'Was kommt nach {a}, wenn du in {b}er-Schritten zählst?',
            'In {b}er-Schritten: {a}, und dann?',
            'Zähl {b} zu {a} dazu, und noch einmal, und noch einmal.',
            'Drei Schritte von je {b} ab {a} - wo kommst du an?',
            'Sag die {b}er-Reihe ab {a}, drei Zahlen davon.',
        ],
    ],
    'math-remainder' => [
        'name'    => 'Was übrig bleibt',
        'pattern' => 'Teile {a} {thing} einzeln unter {b} Freunden auf. Wie viele bleiben am Ende übrig?',
        'answer'  => '{a%b} {thing}',
        'hint'    => 'Teile aus, bis nicht mehr jeder eins bekommen kann.',
        'lists'   => ['thing' => $things],
        'patterns' => [
            '{a} {thing} unter {b}. Wie viele lassen sich nicht verteilen?',
            'Gib {a} {thing} einzeln an {b} Kinder aus. Wie viele bleiben übrig?',
            '{a} {thing} in Gruppen zu {b} - wie groß ist der Rest?',
            '{b} Freunde teilen {a} {thing} gerecht. Wie viele bleiben in der Kiste?',
            'Teile {a} {thing} durch {b}. Was bleibt übrig?',
            'Mach aus {a} {thing} Gruppen zu {b}. Wie viele bleiben ohne Gruppe?',
            '{a} {thing}, {b} Teller, auf jedem gleich viele. Wie viele bleiben in der Kiste?',
            'Verteile {a} {thing} unter {b} und zähl den Rest.',
        ],
    ],
    // ------------------------------------------------ MEHR NATURWISSENSCHAFT
    'sci-bodypart' => [
        'name' => 'Wozu ist das da?',
        'pattern' => 'Wofür brauchst du {part}? Nenne zwei Dinge.',
        'answer' => 'Zwei sinnvolle Verwendungen',
        'hint' => 'Versuch mal etwas ohne.',
        'lists' => ['part' => ['deine Hände', 'deine Augen', 'deine Ohren', 'deine Nase',
                               'deine Füße', 'deinen Mund', 'deine Zähne', 'deine Beine',
                               'deine Finger', 'deine Zunge', 'deine Haut', 'deine Arme']],
        'patterns' => [
            'Nenne zwei Aufgaben, die {part} erledigen.',
            '{part} - was würde dir ohne fehlen?',
            'Nenne zwei Dinge, die du ohne {part} nicht könntest.',
            'Wozu braucht man {part}?',
            'Denk an zwei Arten, wie du heute {part} benutzt hast.',
            'Jemand kennt {part} nicht. Erkläre, wozu sie da sind.',
            'Zwei Verwendungen für {part} - los.',
            'Welche Arbeit machen {part} den ganzen Tag?',
        ],
    ],
    'sci-weather' => [
        'name' => 'Anziehen nach dem Wetter',
        'pattern' => 'Was würdest du anziehen, wenn {weather}?',
        'answer' => 'Alles, was zu dem Wetter passt',
        'hint' => 'Denk daran, trocken und warm zu bleiben - oder kühl.',
        'lists' => ['weather' => ['es regnet', 'es schneit', 'die Sonne stark scheint', 'es windig ist',
                                  'Nebel liegt', 'es friert', 'es heiß ist', 'ein Gewitter kommt',
                                  'es nieselt', 'es glatt ist', 'es mild ist', 'der Himmel bedeckt ist']],
        'patterns' => [
            'Draußen {weather}. Was ziehst du an?',
            'Nenne eine Sache, die du mitnehmen würdest, wenn {weather}.',
            '{weather}: Sag, was du anziehen würdest.',
            'Was würdest du NICHT anziehen, wenn {weather}?',
            'Du gehst raus und {weather}. Was schnappst du dir?',
            'Pack für einen Tag, an dem {weather}. Nenne zwei Dinge.',
            'Welche Kleidung passt, wenn {weather}?',
            'Den ganzen Morgen schon {weather}. Was hast du an?',
        ],
    ],
    'sci-material' => [
        'name' => 'Woraus ist das?',
        'pattern' => 'Woraus ist {thing} normalerweise gemacht?',
        'answer' => 'Das übliche Material',
        'hint' => 'Denk daran, wie es sich anfühlt.',
        'lists' => ['thing' => ['ein Fenster', 'ein Löffel', 'ein Buch', 'ein Pullover', 'ein Reifen',
                                'eine Flasche', 'ein Tisch', 'eine Münze', 'ein Luftballon',
                                'ein Ziegelstein', 'ein Bleistift', 'eine Socke']],
        'patterns' => [
            '{thing} - nenne das Material.',
            'Ist {thing} aus Holz, Metall, Plastik oder etwas anderem?',
            'Woraus würdest du {thing} machen?',
            'Fühl {thing} in Gedanken. Welches Material ist das?',
            'Aus welchem Material macht man {thing} normalerweise?',
            'Metall, Glas, Stoff oder Papier - was ist {thing}?',
            'Sag, woraus {thing} ist und woran du das merkst.',
            'Nach welchem Material würdest du suchen, um {thing} zu bauen?',
        ],
    ],
    'sci-daynight' => [
        'name' => 'Tag oder Nacht?',
        'pattern' => 'Passiert es am Tag oder in der Nacht, dass {event}?',
        'answer' => 'Das eine oder das andere',
        'hint' => 'Denk daran, wo die Sonne steht.',
        'lists' => ['event' => ['die Sonne aufgeht', 'Eulen jagen', 'die Sterne herauskommen',
                                'Fledermäuse fliegen', 'Gänseblümchen sich öffnen',
                                'der Mond am hellsten scheint', 'Kinder zur Schule gehen',
                                'die Straßenlaternen angehen', 'Vögel im Morgengrauen singen',
                                'der Himmel dunkel wird']],
        'patterns' => [
            'Tag oder Nacht: {event}?',
            'Wann würdest du sehen, dass {event}?',
            'Merkt man bei Sonnenlicht, dass {event}?',
            'Wärst du am Schlafen, wenn {event}?',
            '{event}: morgens, nachmittags oder mitten in der Nacht?',
            'Sag, ob es am Tag ist, dass {event}.',
            'Zeig den Himmel, den du sehen würdest, wenn {event}.',
            'Ist es eher am Tag oder nachts, dass {event}?',
        ],
    ],
    'sci-magnet' => [
        'name' => 'Nimmt ein Magnet das mit?',
        'pattern' => 'Würde ein Magnet {thing} anziehen?',
        'answer' => 'Ja oder nein, mit einer Begründung',
        'hint' => 'Magneten sind wählerisch: fast nur Metalle.',
        'lists' => ['thing' => ['eine Büroklammer', 'einen Plastikbecher', 'einen Nagel',
                                'einen Holzlöffel', 'eine Münze', 'ein Gummiband', 'einen Schlüssel',
                                'ein Blatt', 'eine Blechdose', 'einen Bleistift',
                                'eine Glasmurmel', 'einen Metallöffel']],
        'patterns' => [
            'Halt einen Magneten neben {thing}. Passiert etwas?',
            'Ist {thing} etwas, woran ein Magnet haftet?',
            'Mit oder ohne Magnet: Würde {thing} hinüberspringen?',
            'Würdest du {thing} an einem Kühlschrankmagneten kleben sehen?',
            'Sag, ob ein Magnet bei {thing} wirkt, und warum.',
            '{thing}: magnetisch oder nicht?',
            'Was würde ein Magnet hochheben: {thing} oder gar nichts?',
            'Probier es im Kopf: Magnet trifft {thing}. Was passiert?',
        ],
    ],
    'sci-origin' => [
        'name' => 'Woher kommt das?',
        'pattern' => 'Woher kommt {thing}, bevor es in den Laden kommt?',
        'answer' => 'Die richtige Herkunft, in eigenen Worten',
        'hint' => 'Fast alles fängt bei einer Pflanze oder einem Tier an.',
        'lists' => ['thing' => ['Milch', 'Brot', 'Wolle', 'Honig', 'Eier', 'Äpfel',
                                'Papier', 'Schokolade', 'Käse', 'Orangensaft',
                                'ein Baumwoll-T-Shirt', 'Kartoffeln']],
        'patterns' => [
            'Verfolge {thing} zurück. Wo fängt es an?',
            'Bevor es {thing} war - was war es da?',
            'Wer oder was macht {thing}?',
            '{thing}: Bauernhof, Fabrik, Wald oder Meer?',
            'Erzähl die Geschichte von {thing} vom Anfang bis ins Regal.',
            'Was muss passieren, damit es {thing} im Laden gibt?',
            'Nenne die Pflanze oder das Tier, von dem {thing} kommt, falls es eins gibt.',
            'Wie wird {thing} gemacht?',
        ],
    ],
    'sci-states' => [
        'name' => 'Fest, flüssig oder gasförmig?',
        'pattern' => 'Ist {thing} fest, flüssig oder ein Gas?',
        'answer' => 'Das Richtige von den dreien',
        'hint' => 'Kannst du es halten, gießen, oder keins von beidem?',
        'lists' => ['thing' => ['Wasser', 'Eis', 'Wasserdampf', 'ein Stein', 'Milch', 'Luft',
                                'Honig', 'Sand', 'Rauch', 'Saft', 'Holz', 'Wind']],
        'patterns' => [
            'Was von dreien ist {thing}: fest, flüssig oder Gas?',
            'Kann man {thing} gießen? Was macht das daraus?',
            'Behält {thing} seine eigene Form?',
            '{thing}: Würde es einen Krug ausfüllen oder einfach darin liegen?',
            'Sortiere {thing} als fest, flüssig oder gasförmig ein und sag warum.',
            'Würde {thing} entwischen, wenn man den Deckel öffnet?',
            'Sag, in welchem Zustand {thing} ist.',
            'Fest, flüssig, Gas - wohin gehört {thing}?',
        ],
    ],
    'sci-without' => [
        'name' => 'Und wenn es das nicht gäbe?',
        'pattern' => 'Was wäre, wenn es {thing} nicht gäbe?',
        'answer' => 'Jede durchdachte Antwort',
        'hint' => 'Denk daran, was sonst noch davon abhängt.',
        'lists' => ['thing' => ['die Sonne', 'Regen', 'Bäume', 'Bienen', 'sauberes Wasser',
                                'Luft', 'die Nacht', 'Pflanzen', 'Regenwürmer', 'Eis an den Polen']],
        'patterns' => [
            'Stell dir eine Welt ohne {thing} vor. Was ändert sich zuerst?',
            'Warum ist es wichtig, dass es {thing} gibt?',
            'Nimm {thing} weg. Was funktioniert dann nicht mehr?',
            'Wer würde es zuerst merken, wenn {thing} verschwindet?',
            'Nenne zwei Dinge, die von {thing} abhängen.',
            'Kämen wir ohne {thing} zurecht? Sag warum oder warum nicht.',
            'Was tut {thing} für uns, ohne dass wir es merken?',
            'Wenn {thing} morgen weg wäre - was würde dir fehlen?',
        ],
    ],
    'sci-findout' => [
        'name' => 'Wie findest du das heraus?',
        'pattern' => 'Wie könntest du herausfinden, ob {question}?',
        'answer' => 'Jeder Test, der es wirklich zeigt',
        'hint' => 'Ändere nur eine Sache und lass den Rest gleich.',
        'lists' => ['question' => [
            'ein Stein schwerer ist als ein Schuh',
            'Eis in einem warmen Zimmer schneller schmilzt',
            'Pflanzen Licht zum Wachsen brauchen',
            'ein Magnet durch Papier wirkt',
            'Schall durch Wasser wandert',
            'Salz sich in heißem Wasser schneller auflöst',
            'ein Ball auf dem Weg weiter rollt als auf Gras',
            'manches Papier fester ist als anderes',
        ]],
        'patterns' => [
            'Denk dir einen Test aus, der zeigt, ob {question}.',
            'Was würdest du tun, um zu prüfen, ob {question}?',
            'Du glaubst, dass {question}. Wie würdest du es beweisen?',
            'Beschreib ein Experiment dazu, ob {question}.',
            'Was bräuchtest du, um herauszufinden, ob {question}?',
            'Wie machst du den Test fair, wenn du prüfst, ob {question}?',
            'Jemand zweifelt, dass {question}. Zeig ihm, wie man das prüft.',
            'Überleg dir: Stimmt es, dass {question}?',
        ],
    ],
    // ------------------------------------------------- MEHR NATUR
    'nature-legs' => [
        'name' => 'Wie viele Beine?',
        'pattern' => 'Wie viele Beine hat {animal}?',
        'answer' => 'Die richtige Zahl',
        'hint' => 'Insekten haben sechs, Spinnen acht.',
        'lists' => ['animal' => ['eine Spinne', 'ein Hund', 'ein Vogel', 'eine Ameise',
                                 'eine Schlange', 'ein Mensch', 'eine Katze', 'ein Käfer',
                                 'ein Fisch', 'ein Pferd', 'ein Marienkäfer', 'eine Krabbe']],
        'patterns' => [
            'Zähl die Beine von {animal}.',
            '{animal} - wie viele Beine sind das?',
            'Zeig mit den Fingern, wie viele Beine {animal} hat.',
            'Mehr Beine als du oder weniger: {animal}?',
            'Mit wie vielen Füßen würde {animal} Spuren hinterlassen?',
            'Sag die Anzahl der Beine von {animal}.',
            'Hat {animal} überhaupt Beine? Wie viele?',
            'Beine bei {animal}: wie viele?',
        ],
    ],
    'nature-bigger' => [
        'name' => 'Was ist größer?',
        'pattern' => 'Was ist größer: {pair}?',
        'answer' => 'Das Größere von beiden',
        'hint' => 'Stell sie dir nebeneinander vor.',
        'lists' => ['pair' => ['eine Maus oder ein Pferd', 'eine Ameise oder eine Biene',
                               'ein Wal oder ein Hai', 'ein Spatz oder ein Adler',
                               'eine Katze oder ein Tiger', 'ein Frosch oder eine Kröte',
                               'eine Eiche oder ein Gänseblümchen', 'eine Fliege oder ein Schmetterling',
                               'ein Kaninchen oder ein Hase', 'eine Schnecke oder ein Wurm',
                               'eine Ziege oder eine Kuh', 'ein Pinguin oder eine Ente']],
        'patterns' => [
            '{pair} - wofür bräuchtest du mehr Platz?',
            'Ordne {pair} nach der Größe.',
            'Was von {pair} würde in deine Hand passen?',
            'Ist das Erste oder das Zweite größer: {pair}?',
            'Stell {pair} nebeneinander. Was ist höher?',
            'Was ist kleiner: {pair}?',
            '{pair}: Sag, was größer ist und ungefähr um wie viel.',
            'Wenn {pair} um die Wette liefen - wer bräuchte mehr Bahn?',
        ],
    ],
    'nature-grows' => [
        'name' => 'Wo wächst das?',
        'pattern' => 'Wo wächst {thing}?',
        'answer' => 'Am Baum, unter der Erde, am Strauch und so weiter',
        'hint' => 'Manches versteckt sich unter der Erde.',
        'lists' => ['thing' => ['Äpfel', 'Kartoffeln', 'Erdbeeren', 'Eicheln',
                                'Pilze', 'Karotten', 'Brombeeren', 'Haselnüsse',
                                'Weizen', 'Weintrauben', 'Birnen', 'Zwiebeln']],
        'patterns' => [
            'Wächst {thing} über oder unter der Erde?',
            'Am Baum, am Strauch oder unter der Erde: {thing}?',
            'Wohin würdest du gehen, um {thing} zu pflücken?',
            '{thing} - woran wächst das?',
            'Zeig, woher {thing} kommt, bevor es in den Laden geht.',
            'Sag jemandem, wo {thing} wächst.',
            'Müsstest du für {thing} graben oder nach oben greifen?',
            'Nenne die Pflanze, die uns {thing} gibt.',
        ],
    ],
    'nature-colour' => [
        'name' => 'Welche Farbe?',
        'pattern' => 'Welche Farbe hat {thing} normalerweise?',
        'answer' => 'Die übliche Farbe',
        'hint' => 'Denk daran, wann du zuletzt eines gesehen hast.',
        'lists' => ['thing' => ['Gras', 'der Himmel an einem klaren Tag', 'eine Karotte',
                                'die Brust eines Rotkehlchens', 'Schnee', 'eine Sonnenblume',
                                'ein Frosch', 'ein Marienkäfer', 'eine Orange', 'ein Rabe',
                                'eine Tomate', 'eine Osterglocke']],
        'patterns' => [
            'Mach die Augen zu und stell dir {thing} vor. Welche Farbe?',
            'Zu welchem Buntstift würdest du greifen, um {thing} zu malen?',
            '{thing} - nenne die Farbe.',
            'Hat {thing} das ganze Jahr dieselbe Farbe?',
            'Sag die Farbe von {thing}, ohne auf etwas zu zeigen.',
            'In welcher Farbe würdest du {thing} anmalen?',
            'Jemand hat {thing} noch nie gesehen. Sag ihm die Farbe.',
            'Nenne eine Farbe, die du für {thing} NICHT nehmen würdest.',
        ],
    ],
    'nature-move' => [
        'name' => 'Wie bewegt es sich?',
        'pattern' => 'Wie bewegt sich {animal} fort?',
        'answer' => 'Jede richtige Art der Fortbewegung',
        'hint' => 'Manche können mehr als eins davon.',
        'lists' => ['animal' => ['eine Schlange', 'ein Fisch', 'ein Vogel', 'ein Känguru',
                                 'eine Schnecke', 'ein Pferd', 'eine Spinne', 'eine Ente',
                                 'eine Fledermaus', 'eine Krabbe', 'ein Frosch', 'ein Regenwurm']],
        'patterns' => [
            'Zeig, wie {animal} von einem Ort zum anderen kommt.',
            'Läuft, schwimmt, fliegt oder gleitet {animal}?',
            'Beweg dich drei Sekunden lang wie {animal}.',
            'Was benutzt {animal} zum Fortbewegen - Beine, Flügel oder etwas anderes?',
            'Wer ist schneller: du oder {animal}? Wie bewegt es sich?',
            'Beschreib, wie {animal} unterwegs ist.',
            '{animal} muss ein Feld überqueren. Wie macht es das?',
            'Nenne die Art, wie {animal} sich fortbewegt.',
        ],
    ],
    'nature-parts' => [
        'name' => 'Die Teile eines Lebewesens',
        'pattern' => 'Nenne zwei Teile von {thing} und sag, was sie tun.',
        'answer' => 'Zwei Teile mit ihrer Aufgabe',
        'hint' => 'Wurzeln, Flügel, Blütenblätter - jedes hat eine Aufgabe.',
        'lists' => ['thing' => ['einem Baum', 'einer Blume', 'einem Vogel', 'einem Fisch',
                                'einem Insekt', 'einem Blatt', 'einem Pilz', 'einem Samenkorn',
                                'einer Spinne', 'einem Schmetterling']],
        'patterns' => [
            'Welches sind die wichtigsten Teile von {thing}?',
            'Wähl einen Teil von {thing} und erkläre seine Aufgabe.',
            'Benenne laut zwei Teile von {thing}.',
            '{thing} - welcher Teil macht die wichtigste Arbeit?',
            'Zwei Teile von {thing} und warum jeder zählt.',
            'Wenn du {thing} malen würdest - welche zwei Teile müssten drauf?',
            'Was ginge schief, wenn {thing} einen seiner Teile verlöre?',
            'Beschreib {thing} anhand seiner Teile.',
        ],
    ],
    'nature-help' => [
        'name' => 'Tieren helfen',
        'pattern' => 'Wie könntest du {creature} in deiner Nähe helfen?',
        'answer' => 'Jede freundliche, sinnvolle Idee',
        'hint' => 'Futter, Wasser und ein sicherer Platz.',
        'lists' => ['creature' => ['Vögeln im Winter', 'Bienen', 'Igeln', 'Regenwürmern',
                                   'Schmetterlingen', 'Fröschen', 'einem jungen Baum',
                                   'Marienkäfern', 'Fledermäusen', 'Eichhörnchen']],
        'patterns' => [
            'Nenne eine Sache, die du für {creature} tun könntest.',
            '{creature} haben einen harten Winter. Was würde helfen?',
            'Was würdest du für {creature} in einen Garten stellen?',
            'Wie könnte eine ganze Straße {creature} helfen?',
            'Eine Kleinigkeit, die du diese Woche für {creature} tun könntest - welche?',
            'Was brauchen {creature}, das Menschen geben können?',
            'Nenne eine Sache, die {creature} schadet, und eine, die hilft.',
            'Überleg dir, wie dein Garten besser für {creature} würde.',
        ],
    ],
    'nature-adapt' => [
        'name' => 'Dafür gebaut',
        'pattern' => 'Wie kommt {animal} mit {condition} zurecht?',
        'answer' => 'Jede echte Art, wie es das schafft',
        'hint' => 'Schau dir Haut, Füße und Augen an.',
        'lists' => ['animal' => ['ein Eisbär', 'ein Kamel', 'ein Pinguin', 'eine Eule',
                                 'ein Maulwurf', 'ein Fisch', 'eine Fledermaus', 'eine Schildkröte',
                                 'ein Eichhörnchen', 'ein Wüstenfuchs'],
                    'condition' => ['der Kälte', 'Tagen ohne Wasser', 'der Dunkelheit',
                                    'Jägern', 'starker Sonne']],
        'patterns' => [
            'Was hilft {animal}, {condition} zu überstehen?',
            '{animal} steht {condition} gegenüber. Womit ist es ausgerüstet?',
            'Welcher Teil von {animal} kommt mit {condition} klar?',
            'Warum hält {condition} {animal} nicht auf?',
            'Beschreib, wie {animal} mit {condition} umgeht.',
            'Was würde {animal} bei {condition} tun?',
            '{condition} würde die meisten Tiere schaffen. Wie hält {animal} das aus?',
            'Nenne eine Sache an {animal}, die zu {condition} passt.',
        ],
    ],
    'nature-year' => [
        'name' => 'Durch das Jahr',
        'pattern' => 'Was passiert mit {thing} im Lauf des Jahres?',
        'answer' => 'Jede zutreffende Beschreibung der Veränderungen',
        'hint' => 'Denk an Futter, Wärme und Tageslicht.',
        'lists' => ['thing' => ['einer Eiche', 'einem Teich', 'einem Igel', 'einem Feld',
                                'einer Schwalbe', 'einer Raupe', 'einem Garten', 'einem Hang',
                                'einem Bienenstock', 'einem Fluss']],
        'patterns' => [
            'Folge {thing} durch vier Jahreszeiten. Was ändert sich?',
            '{thing} im Frühling und {thing} im Winter - was ist anders?',
            'Welche Jahreszeit ist am härtesten für {thing}? Warum?',
            'Beschreib ein Jahr im Leben von {thing}.',
            'Was macht {thing}, wenn es kalt wird?',
            'Nenne eine Veränderung, die {thing} jedes Jahr erlebt.',
            'Würdest du {thing} im Sommer oder im Winter mehr bemerken? Warum?',
            'Wie bereitet sich {thing} auf den Winter vor?',
        ],
    ],
];
