<?php
/**
 * The question templates in German. Keyed by the English template's code;
 * see install/mission-templates-all.php for how the two halves are joined.
 *
 * CASE AND GENDER
 *
 * German bends the words around a blank, and one sentence has to hold a dozen
 * different ones. So each place carries its own preposition and case - im
 * Garten, auf der Wiese - and the sentences are written to avoid an article in
 * front of a blank: "mit je 5 Murmeln" rather than "in jedem Korb". Every
 * creature and object is a plural, which needs no gender.
 *
 * The reading and grammar questions are not translations: rhymes, plurals and
 * past tenses only exist inside one language, so those are written fresh here.
 */

$creatures = ['Kaninchen', 'Kätzchen', 'Welpen', 'Entenküken', 'Frösche', 'Bienen',
              'Pinguine', 'Füchse', 'Eulen', 'Schildkröten', 'Eichhörnchen', 'Delfine'];

$things = ['Äpfel', 'Murmeln', 'Aufkleber', 'Buntstifte', 'Muscheln', 'Eicheln',
           'Knöpfe', 'Kieselsteine', 'Bänder', 'Kastanien', 'Federn', 'Kirschen'];

$places = ['auf der Wiese', 'im Garten', 'am Teich', 'im Wald', 'auf dem Spielplatz',
           'am Strand', 'im Obstgarten', 'im Baumhaus', 'in der Scheune', 'am Bach'];

$names = ['Mia', 'Ben', 'Lina', 'Jonas', 'Emma', 'Theo',
          'Sana', 'Milo', 'Bella', 'Pedro', 'Ada', 'Noor'];

$containers = ['Körbe', 'Kisten', 'Gläser', 'Eimer', 'Taschen', 'Schachteln', 'Tabletts'];

$treats = ['Kekse', 'Trauben', 'Brote', 'Erdbeeren', 'Muffins', 'Pflaumen'];

return [

    // ----------------------------------------------------------------- MATHS
    'math-add' => [
        'name'    => 'Dazuzählen',
        'pattern' => 'Es sind {a} {creature} {place}. {b} weitere kommen dazu. Wie viele {creature} sind es jetzt?',
        'answer'  => '{a+b} {creature}',
        'hint'    => 'Zähle alle zusammen.',
        'lists'   => ['creature' => $creatures, 'place' => $places],
    ],
    'math-sub' => [
        'name'    => 'Wegnehmen',
        'pattern' => '{who} hat {a} {thing} gesammelt und verschenkt {b} davon. Wie viele {thing} bleiben übrig?',
        'answer'  => '{a-b} {thing}',
        'hint'    => 'Fang bei dem an, was du hattest, und nimm den Rest weg.',
        'lists'   => ['thing' => $things, 'who' => $names],
    ],
    'math-count-back' => [
        'name'    => 'Rückwärts zählen',
        'pattern' => 'Fang bei {a} an und zähle {b} zurück. Wo kommst du an?',
        'answer'  => '{a-b}',
        'hint'    => 'Nimm die Finger zu Hilfe, wenn es hilft.',
    ],
    'math-double' => [
        'name'    => 'Verdoppeln',
        'pattern' => '{who} hat {a} {thing} und findet noch einmal genauso viele. Wie viele sind es jetzt?',
        'answer'  => '{a+a} {thing}',
        'hint'    => 'Verdoppeln heißt: dieselbe Menge zweimal.',
        'lists'   => ['thing' => $things, 'who' => $names],
    ],
    'math-mul' => [
        'name'    => 'Gruppen von',
        'pattern' => 'Es gibt {a} {container} mit je {b} {thing}. Wie viele {thing} sind das zusammen?',
        'answer'  => '{a*b} {thing}',
        'hint'    => 'Zähle die Gruppen und dann, was in jeder steckt.',
        'lists'   => ['container' => $containers, 'thing' => $things],
    ],
    'math-div' => [
        'name'    => 'Gerecht teilen',
        'pattern' => 'Teile {a} {treat} gerecht unter {b} Freunden auf. Wie viele bekommt jeder?',
        'answer'  => '{a/b} {treat} pro Kind',
        'hint'    => 'Gib sie einzeln aus, wie Spielkarten.',
        'lists'   => ['treat' => $treats],
    ],
    'math-missing' => [
        'name'    => 'Die fehlende Zahl',
        'pattern' => '{who} hatte ein paar {thing}, bekam {b} dazu und hat jetzt {c}. Wie viele waren es am Anfang?',
        'answer'  => '{c-b} {thing}',
        'hint'    => 'Rechne von der Gesamtzahl rückwärts.',
        'lists'   => ['thing' => $things, 'who' => $names],
    ],
    'math-word2' => [
        'name'    => 'Rechnen mit Münzen',
        'pattern' => 'Du hast {a} Münzen. Du kaufst {b} {thing} für je {c} Münzen. Wie viele Münzen bleiben dir?',
        'answer'  => '{a-b*c} Münzen',
        'hint'    => 'Rechne erst die Kosten aus und zieh sie dann ab.',
        'lists'   => ['thing' => $things],
    ],
    'math-two-step' => [
        'name'    => 'Zwei Schritte',
        'pattern' => '{who} packt {a} {container} mit je {b} {thing}, dann fallen {c} {thing} heraus. Wie viele sind noch eingepackt?',
        'answer'  => '{a*b-c} {thing}',
        'hint'    => 'Erst malnehmen, dann abziehen.',
        'lists'   => ['container' => $containers, 'thing' => $things, 'who' => $names],
    ],

    // -------------------------------------------------------------- LITERACY
    'lit-rhyme' => [
        'name'    => 'Finde einen Reim',
        'pattern' => 'Sag ein Wort, das sich auf „{word}“ reimt.',
        'answer'  => 'Jedes echte Reimwort zählt',
        'hint'    => 'Sprich es laut aus und hör auf das Ende.',
        'lists'   => ['word' => ['Haus', 'Baum', 'Stern', 'Maus', 'Hand', 'Katze',
                                 'Blume', 'Schnecke', 'Nase', 'Boot', 'Glocke', 'Kuchen',
                                 'Stuhl', 'Tür', 'Mond', 'Hut', 'Zug', 'Schaf',
                                 'Löffel', 'Wand', 'Weg', 'Sonne']],
    ],
    'lit-letter' => [
        'name'    => 'Der erste Laut',
        'pattern' => 'Nenne {a} Dinge, die mit dem Buchstaben „{letter}“ anfangen.',
        'answer'  => 'Beliebige {a} passende Wörter',
        'hint'    => 'Schau dich im Raum um, das gibt Ideen.',
        'lists'   => ['letter' => ['B', 'D', 'F', 'G', 'H', 'K', 'L', 'M', 'R', 'S', 'T', 'W']],
    ],
    'lit-opposite' => [
        'name'    => 'Gegenteile',
        'pattern' => 'Was ist das Gegenteil von „{word}“?',
        'answer'  => 'Das richtige Gegenteil',
        'hint'    => 'Denk an das Wort, das genau andersherum bedeutet.',
        'lists'   => ['word' => ['heiß', 'groß', 'schnell', 'fröhlich', 'Tag', 'oben',
                                 'laut', 'nass', 'voll', 'früh', 'hart', 'nah',
                                 'offen', 'schwer', 'jung', 'sauber', 'erster', 'drinnen',
                                 'süß', 'rau', 'mutig', 'wach']],
    ],
    'lit-define' => [
        'name'    => 'Mit eigenen Worten',
        'pattern' => 'Was bedeutet das Wort „{word}“? Erkläre es mit deinen eigenen Worten.',
        'answer'  => 'Jede sinnvolle Erklärung zählt',
        'hint'    => 'Bau es erst einmal in einen Satz ein.',
        'lists'   => ['word' => ['Mut', 'neugierig', 'sanft', 'uralt', 'zerbrechlich',
                                 'großzügig', 'stur', 'dankbar', 'ängstlich', 'treu',
                                 'geduldig', 'ehrlich', 'ungeschickt', 'riesig', 'still',
                                 'eifersüchtig', 'höflich', 'erschöpft', 'empfindlich', 'stolz']],
    ],
    'lit-sentence' => [
        'name'    => 'Bau einen Satz',
        'pattern' => 'Denk dir einen Satz aus, in dem „{word}“ und „{other}“ beide vorkommen.',
        'answer'  => 'Jeder Satz mit beiden Wörtern',
        'hint'    => 'Er darf so albern sein, wie du willst.',
        'lists'   => ['word'  => ['Fluss', 'Burg', 'Sturm', 'Laterne', 'Hafen', 'Wiese',
                                  'Treppe', 'Markt', 'Leuchtturm', 'Obstgarten'],
                      'other' => ['still', 'golden', 'plötzlich', 'riesig', 'gefroren', 'krumm',
                                  'vergessen', 'laut', 'verkehrt herum', 'unsichtbar']],
    ],
    'lit-story' => [
        'name'    => 'Erzähl weiter',
        'pattern' => 'Erzähl, wie die Geschichte weitergeht: „{opening}“',
        'answer'  => 'Jede Fortsetzung, die dazu passt',
        'hint'    => 'Zwei oder drei Sätze reichen völlig.',
        'lists'   => ['opening' => [
            'Die Tür oben an der Treppe war noch nie offen gewesen ...',
            'Auf der Karte war eine Insel, die auf keiner anderen Karte stand ...',
            'Das ganze Dorf wachte auf und sprach rückwärts ...',
            'Der alte Leuchtturm ging nach zwanzig Jahren von selbst wieder an ...',
            'Ein Brief kam für jemanden, der dort gar nicht wohnte ...',
            'Die Katze kam mit einem Halsband nach Hause, das niemand gekauft hatte ...',
            'Alle Uhren im Haus blieben in derselben Minute stehen ...',
            'Am Himmel stand ein zweiter Mond, und nur die Kinder sahen ihn ...',
            'In der Bibliothek gab es ein Regal, das gestern noch nicht da war ...',
            'Fußspuren kamen aus dem Meer und endeten vor der Haustür ...',
            'Der älteste Baum im Park hatte an diesem Morgen eine Tür ...',
            'Ein Paket kam ohne Adresse, mit einem Loch an der Seite ...',
            'Die Schulglocke läutete eine Stunde zu früh, und niemand hatte sie berührt ...',
            'Jemand hatte auf die letzte Seite des Hefts eine Karte gezeichnet ...',
            'Alle Vögel verließen die Stadt am selben Nachmittag ...',
            'Ein Fenster, das seit Jahren klemmte, ging von selbst auf ...',
        ]],
    ],

    // --------------------------------------------------------------- ENGLISH
    // In German this is German grammar: its own plurals and past tenses.
    'eng-plural' => [
        'name'    => 'Eins und viele',
        'pattern' => 'Wie heißt die Mehrzahl von „{word}“?',
        'answer'  => 'Die richtige Mehrzahl',
        'hint'    => 'Manche Wörter ändern sich mehr, als man denkt.',
        'lists'   => ['word' => ['Kind', 'Maus', 'Blatt', 'Fuß', 'Buch',
                                 'Messer', 'Gans', 'Haus', 'Zahn', 'Baby',
                                 'Mann', 'Frau', 'Schaf', 'Wolf', 'Stadt',
                                 'Kirche', 'Hälfte', 'Mensch', 'Apfel', 'Kartoffel']],
    ],
    'eng-verb' => [
        'name'    => 'Gestern',
        'pattern' => 'Setz den Satz in die Vergangenheit: „Jeden Tag {verb} ich.“',
        'answer'  => 'Die richtige Vergangenheitsform von „{verb}“',
        'hint'    => 'Sag es so, als wäre es schon passiert.',
        'lists'   => ['verb' => ['laufe', 'schwimme', 'esse', 'schreibe', 'singe',
                                 'denke', 'bringe', 'fange', 'male', 'fliege',
                                 'gehe', 'nehme', 'gebe', 'schlafe', 'kaufe',
                                 'lese', 'trage', 'baue', 'finde', 'trinke']],
    ],
    'eng-describe' => [
        'name'    => 'Beschreib es',
        'pattern' => 'Beschreibe {thing} jemandem, der so etwas noch nie gesehen hat - ohne das Wort zu benutzen.',
        'answer'  => 'Jede klare Beschreibung',
        'hint'    => 'Fang damit an, wozu man es braucht.',
        'lists'   => ['thing' => ['ein Fahrrad', 'einen Regenschirm', 'einen Wasserkocher', 'eine Treppe',
                                  'ein Teleskop', 'eine Sandburg', 'eine Windmühle', 'einen Drachen',
                                  'einen Leuchtturm', 'eine Schubkarre', 'einen Reißverschluss',
                                  'einen Spiegel', 'eine Leiter', 'eine Uhr', 'einen Schwamm',
                                  'eine Trillerpfeife', 'einen Schnürsenkel', 'einen Schneemann']],
    ],

    // --------------------------------------------------------------- SCIENCE
    'sci-sense' => [
        'name'    => 'Welcher Sinn?',
        'pattern' => 'Welchen Körperteil brauchst du, um {sense}?',
        'answer'  => 'Das passende Sinnesorgan',
        'hint'    => 'Zeig darauf.',
        'lists'   => ['sense' => ['an einer Blume zu riechen', 'eine Glocke zu hören',
                                  'Honig zu schmecken', 'einen Regenbogen zu sehen',
                                  'warmen Sand zu spüren', 'Donner zu hören',
                                  'eine Zitrone zu schmecken', 'nachts einen Stern zu sehen',
                                  'frisches Brot zu riechen', 'eine kalte Scheibe zu spüren',
                                  'deinen eigenen Namen zu hören', 'Salz zu schmecken',
                                  'die Farbe Rot zu sehen', 'eine schnurrende Katze zu spüren']],
    ],
    'sci-float' => [
        'name'    => 'Schwimmt es oder geht es unter?',
        'pattern' => 'Würde {thing} im Wasser schwimmen oder untergehen? Sag, warum du das denkst.',
        'answer'  => 'Beides gilt, wenn eine Begründung dabei ist',
        'hint'    => 'Denk daran, wie schwer es für seine Größe ist.',
        'lists'   => ['thing' => ['ein Korken', 'ein Stein', 'ein Apfel', 'eine Münze', 'eine Feder',
                                  'ein Schwamm', 'ein Nagel', 'eine Kerze', 'eine Orange',
                                  'ein Holzlöffel', 'eine Weintraube', 'eine verschlossene Plastikflasche',
                                  'eine Büroklammer', 'eine Zitrone', 'eine Gummiente', 'ein Ziegelstein',
                                  'ein Bleistift', 'eine Murmel']],
    ],
    'sci-change' => [
        'name'    => 'Was passiert dann?',
        'pattern' => 'Was passiert, wenn {event}? Erkläre es so gut du kannst.',
        'answer'  => 'Eine sinnvolle Erklärung',
        'hint'    => 'Sag, was du sehen würdest, und dann warum.',
        'lists'   => ['event' => [
            'du einen Eiswürfel in einem warmen Zimmer liegen lässt',
            'eine Pflanze in einem dunklen Schrank steht',
            'du deine Hände schnell aneinander reibst',
            'man Salz in ein Glas Wasser rührt',
            'ein Luftballon in der Sonne liegt',
            'eine Pfütze den ganzen Vormittag in der Sonne steht',
            'du eine kalte Fensterscheibe anhauchst',
            'ein aufgeschnittener Apfel auf dem Tisch liegen bleibt',
            'du einen Magneten neben einen Haufen Büroklammern hältst',
            'ein Fahrrad einen Monat lang im Regen steht',
            'du einen Stein und eine Feder gleichzeitig fallen lässt',
            'man ein Glas über eine brennende Kerze stülpt',
            'nasse Wäsche an einem windigen Tag draußen hängt',
            'du eine Flasche mit Wasser und Öl schüttelst',
            'ein Samenkorn eingepflanzt und jeden Tag gegossen wird',
        ]],
    ],

    // ---------------------------------------------------------------- NATURE
    'nature-animal' => [
        'name'    => 'Tierstimmen',
        'pattern' => 'Welches Geräusch macht {animal}? Mach es so gut nach, wie du kannst!',
        'answer'  => 'Jeder gute Versuch zählt',
        'hint'    => 'Hier gibt niemand Noten.',
        'lists'   => ['animal' => ['eine Kuh', 'eine Ente', 'ein Löwe', 'ein Schaf', 'eine Eule',
                                   'ein Frosch', 'ein Pferd', 'eine Biene', 'eine Katze',
                                   'ein Wolf', 'eine Ziege', 'eine Krähe', 'ein Schwein', 'ein Esel',
                                   'ein Huhn', 'eine Maus', 'eine Schlange', 'ein Elefant',
                                   'ein Hund', 'eine Möwe', 'ein Affe', 'eine Grille']],
    ],
    'nature-home' => [
        'name'    => 'Wo wohnt es?',
        'pattern' => 'Wo wohnt {animal}?',
        'answer'  => 'Die richtige Art von Zuhause',
        'hint'    => 'Denk daran, was es braucht, um sicher zu sein.',
        'lists'   => ['animal' => ['eine Biene', 'ein Kaninchen', 'ein Pinguin', 'ein Kamel', 'ein Fisch',
                                   'eine Eule', 'ein Maulwurf', 'eine Krabbe', 'eine Fledermaus',
                                   'ein Eichhörnchen', 'ein Eisbär', 'ein Känguru', 'eine Spinne',
                                   'ein Biber', 'eine Ameise', 'eine Schwalbe', 'eine Schildkröte',
                                   'ein Dachs', 'ein Delfin', 'ein Igel']],
    ],
    'nature-season' => [
        'name'    => 'Die Jahreszeiten',
        'pattern' => 'Nenne zwei Dinge, die {season} passieren. Schau {aspect}.',
        'answer'  => 'Zwei sinnvolle Antworten',
        'hint'    => 'Denk an das Wetter und an die Pflanzen.',
        'lists'   => ['season' => ['im Frühling', 'im Sommer', 'im Herbst', 'im Winter'],
                      'aspect' => ['beim Wetter', 'bei den Bäumen', 'bei den Tieren',
                                   'bei der Kleidung', 'im Garten']],
    ],
    'nature-chain' => [
        'name'    => 'Wer frisst was',
        'pattern' => 'Was frisst {animal} wohl, und wer frisst es vielleicht?',
        'answer'  => 'Eine sinnvolle Nahrungskette',
        'hint'    => 'Jedes Tier ist das Abendessen von jemandem.',
        'lists'   => ['animal' => ['eine Maus', 'ein Frosch', 'ein Kaninchen', 'ein Fisch',
                                   'eine Raupe', 'ein Spatz', 'ein Regenwurm', 'eine Schnecke',
                                   'ein Grashüpfer', 'ein Entenküken', 'ein Eichhörnchen',
                                   'ein Marienkäfer', 'eine Garnele', 'eine Feldmaus',
                                   'eine junge Eule', 'eine Kaulquappe']],
    ],

    // ----------------------------------------------------------------- LOGIC
    'logic-odd' => [
        'name'    => 'Was passt nicht?',
        'pattern' => 'Was passt hier nicht dazu: {set}? Sag warum.',
        'answer'  => 'Jede Antwort mit guter Begründung',
        'hint'    => 'Es kann mehr als eine richtige Antwort geben.',
        'lists'   => ['set' => [
            'Apfel, Banane, Karotte, Birne',
            'Hund, Katze, Fisch, Kaninchen',
            'rot, blau, Quadrat, grün',
            'Schuh, Socke, Hut, Löffel',
            'Auto, Boot, Fahrrad, Baum',
            'Löffel, Gabel, Messer, Bleistift',
            'Regen, Schnee, Nebel, Berg',
            'zwei, vier, sieben, sechs',
            'Gitarre, Trommel, Gemälde, Klavier',
            'Montag, Dienstag, Juli, Freitag',
            'Stuhl, Tisch, Wolke, Bett',
            'Löwe, Tiger, Kuh, Leopard',
            'Auge, Ohr, Nase, Handschuh',
            'Fluss, See, Meer, Wüste',
            'Fußball, Tennis, Schach, Schwimmen',
            'Eiche, Kiefer, Rose, Birke',
            'Hammer, Säge, Apfel, Schraubenzieher',
            'Kreis, Dreieck, rot, Quadrat',
        ]],
    ],
    'logic-seq' => [
        'name'    => 'Wie geht es weiter?',
        'pattern' => 'Welche Zahl kommt als Nächstes: {a}, {b}, {c}, ... ?',
        'answer'  => 'Die Zahl, die die Reihe fortsetzt',
        'hint'    => 'Finde heraus, wie groß der Schritt dazwischen ist.',
    ],
    'logic-riddle' => [
        'name'    => 'Rätsel',
        'pattern' => '{riddle}',
        'answer'  => 'Die Lösung des Rätsels',
        'hint'    => 'Lies es zweimal - der Trick steckt in den Worten.',
        'lists'   => ['riddle' => [
            'Ich habe Zeiger, aber keine Hände. Was bin ich?',
            'Je mehr ich trockne, desto nasser werde ich. Was bin ich?',
            'Ich habe Tasten, aber öffne kein Schloss. Was bin ich?',
            'Je mehr du von mir wegnimmst, desto größer werde ich. Was bin ich?',
            'Ich gehe hinauf und hinunter und bleibe doch am selben Platz. Was bin ich?',
            'Ich habe ein Gesicht und zwei Zeiger, aber weder Arme noch Beine. Was bin ich?',
            'Ich bin voller Löcher und halte trotzdem Wasser. Was bin ich?',
            'Ich folge dir den ganzen Tag und verschwinde nachts. Was bin ich?',
            'Ich habe einen Hals, aber keinen Kopf. Was bin ich?',
            'Je mehr es von mir gibt, desto weniger siehst du. Was bin ich?',
            'Ich habe Zähne, aber esse nichts. Was bin ich?',
            'Jung bin ich lang, alt bin ich kurz. Was bin ich?',
            'Ich habe Blätter, bin aber kein Baum. Was bin ich?',
            'Man kann mich fangen, aber nicht werfen. Was bin ich?',
            'Ich komme herunter, gehe aber nie hinauf. Was bin ich?',
            'Ich habe ein Bett, schlafe aber nie, und einen Mund, esse aber nie. Was bin ich?',
            'Ich habe ein Auge und sehe doch nichts. Was bin ich?',
            'Was muss man zerbrechen, bevor man es benutzen kann?',
        ]],
    ],

    // ------------------------------------------------------------ LIFE SKILLS
    'life-kind' => [
        'name'    => 'Etwas Nettes',
        'pattern' => 'Nenne eine nette Sache, die du heute für {who} tun könntest.',
        'answer'  => 'Jede nette Idee zählt',
        'hint'    => 'Auch kleine Sachen zählen.',
        'lists'   => ['who' => ['einen Freund', 'jemanden aus deiner Familie', 'einen Nachbarn',
                                'ein neues Kind in der Klasse', 'jemanden, der traurig ist',
                                'ein jüngeres Kind', 'jemanden, der dir letzte Woche geholfen hat',
                                'eine Lehrerin oder einen Lehrer', 'jemanden, der allein isst',
                                'ein Großelternteil', 'jemanden, der krank ist',
                                'die Person neben dir', 'jemanden mit vollen Händen',
                                'jemanden, der gerade verloren hat',
                                'jemanden, mit dem du dich gestritten hast',
                                'jemanden, der neu im Land ist']],
    ],
    'life-safe' => [
        'name'    => 'Sicher bleiben',
        'pattern' => 'Was solltest du tun, wenn {situation}?',
        'answer'  => 'Jede vernünftige, sichere Antwort',
        'hint'    => 'Eine vertraute erwachsene Person zu suchen, ist meist der erste Schritt.',
        'lists'   => ['situation' => [
            'du im Geschäft deine erwachsene Begleitung verlierst',
            'eine fremde Person dich bittet mitzukommen',
            'es zu Hause verbrannt riecht',
            'du siehst, dass jemandem wehgetan wird',
            'dir in der Schule schlecht wird',
            'du dir in den Finger schneidest und es nicht aufhört zu bluten',
            'der Feueralarm losgeht, während du oben bist',
            'dich jemand im Internet fragt, wo du wohnst',
            'du eine Packung Tabletten auf dem Boden findest',
            'dein Ball auf die Straße rollt',
            'beim Radfahren die Bremsen nicht mehr gehen',
            'ein fremder Hund auf dich zurennt',
            'du dich auf dem Heimweg verläufst',
            'dir jemand Nachrichten schickt, die dich trauriger machen',
            'du als Erste jemanden findest, der gestürzt ist',
        ]],
    ],
    'life-choice' => [
        'name'    => 'Was würdest du tun?',
        'pattern' => 'Was würdest du tun, wenn {situation}?',
        'answer'  => 'Es gibt keine einzig richtige Antwort - sei einfach freundlich',
        'hint'    => 'Sag, was du tun würdest, und warum.',
        'lists'   => ['situation' => [
            'ein Freund die Schuld für etwas auf sich nimmt, das du getan hast',
            'du deine Hausaufgaben vergessen hast',
            'du etwas findest, das jemand anderem gehört',
            'du denselben Nachmittag zwei Leuten versprochen hast',
            'jemand deine Arbeit abschreibt und dafür gelobt wird',
            'du etwas kaputt machst und niemand es sieht',
            'du im Laden zu viel Wechselgeld zurückbekommst',
            'deine Mannschaft jemanden nicht mitspielen lassen will',
            'ein Freund dir ein Geheimnis erzählt, das dir Sorgen macht',
            'du gerade gewinnst und dein Freund aufhören will',
            'jemand sich über die Sprache eines anderen Kindes lustig macht',
            'du etwas gefragt wirst und die Antwort nicht weißt',
            'ein Freund deine Hausaufgaben abschreiben will',
            'du beim Spielen aus Versehen jemandem wehtust',
            'du ein Geschenk bekommst, das dir nicht gefällt',
            'du siehst, wie jemandem Geld hinfällt, ohne es zu merken',
        ]],
    ],

    // ------------------------------------------------------------- GEOGRAPHY
    'geo-where' => [
        'name'    => 'Nah und fern',
        'pattern' => 'Würdest du {thing} in der Nähe deines Zuhauses finden oder weit weg?',
        'answer'  => 'Beides geht, mit einer Begründung',
        'hint'    => 'Denk daran, was es rund um deinen Wohnort gibt.',
        'lists'   => ['thing' => ['einen Berg', 'einen Strand', 'einen Fluss', 'eine Wüste',
                                  'einen Wald', 'einen Hafen', 'einen Vulkan', 'einen Bauernhof',
                                  'einen Bahnhof', 'einen Gletscher', 'einen See', 'eine Insel',
                                  'einen Kanal', 'einen Regenwald', 'einen Wasserfall', 'eine Höhle',
                                  'eine Brücke über ein Tal', 'ein Weizenfeld']],
    ],
    'geo-direction' => [
        'name'    => 'In welche Richtung?',
        'pattern' => 'Du schaust nach {direction} und drehst dich {turn}. Wohin schaust du jetzt?',
        'answer'  => 'Die Richtung {turn} von {direction}',
        'hint'    => 'Stell dir einen Kompass vor, oder nimm die Hände zu Hilfe.',
        'lists'   => ['direction' => ['Norden', 'Süden', 'Osten', 'Westen'],
                      'turn'      => ['nach rechts', 'nach links', 'zweimal nach rechts',
                                      'einmal ganz herum']],
    ],
    'geo-place' => [
        'name'    => 'Orte auf der Erde',
        'pattern' => 'Nenne ein Land, in dem du {feature} erwarten würdest, und sag warum.',
        'answer'  => 'Jedes passende Land, mit einer Begründung',
        'hint'    => 'Denk daran, wie warm oder kalt es dort ist.',
        'lists'   => ['feature' => ['einen Regenwald', 'eine Wüste', 'das ganze Jahr Schnee',
                                    'aktive Vulkane', 'Korallenriffe', 'sehr lange Flüsse',
                                    'wild lebende Pinguine', 'Olivenhaine', 'Tee an Hängen',
                                    'Rentierhirten', 'sehr hohe Berge mit Bergsteigern',
                                    'Kanäle statt Straßen', 'wilde Elefanten', 'Fjorde',
                                    'überall Windmühlen', 'eine sehr lange Mauer']],
    ],
    // ------------------------------------------------------- NEUE AUFGABEN
    'sci-hotcold' => [
        'name'    => 'Heiß oder kalt?',
        'pattern' => 'Ist {thing} normalerweise heiß oder kalt?',
        'answer'  => 'Beides gilt, wenn eine Begründung dabei ist',
        'hint'    => 'Stell dir vor, du fasst es an.',
        'lists'   => ['thing' => ['ein Eis', 'eine Suppe', 'Schnee', 'eine Heizung', 'das Meer im Winter',
                                  'eine Tasse Tee', 'das Innere des Kühlschranks', 'eine Kerzenflamme',
                                  'Sand am Strand im Sommer', 'ein Eiswürfel', 'eine Wärmflasche',
                                  'der Tau am Morgen', 'ein Backofen', 'ein Schneeball', 'warme Milch',
                                  'ein Gefrierschrank', 'eine Mauer in der Sonne',
                                  'Wasser aus dem kalten Hahn']],
    ],
    'sci-living' => [
        'name'    => 'Lebt es?',
        'pattern' => 'Lebt {thing}? Woran erkennst du das?',
        'answer'  => 'Die richtige Antwort mit einer sinnvollen Begründung',
        'hint'    => 'Was lebt, wächst und braucht etwas zum Weitermachen.',
        'lists'   => ['thing' => ['ein Baum', 'ein Stein', 'eine Katze', 'eine Wolke', 'ein Pilz',
                                  'ein Fahrrad', 'ein Regenwurm', 'ein Fluss', 'ein Gänseblümchen',
                                  'ein Teddybär', 'eine Spinne', 'eine Kerze', 'Gras',
                                  'eine Muschel', 'eine Biene', 'eine Pfütze', 'ein Samenkorn',
                                  'ein Spielzeugroboter']],
    ],
    'logic-same' => [
        'name'    => 'Was ist gleich?',
        'pattern' => 'Was haben {pair} gemeinsam?',
        'answer'  => 'Jede sinnvolle Gemeinsamkeit',
        'hint'    => 'Denk daran, wozu man sie braucht oder woraus sie sind.',
        'lists'   => ['pair' => ['ein Fahrrad und ein Auto', 'ein Apfel und eine Banane',
                                 'ein Hund und ein Wolf', 'Regen und Schnee', 'ein Stuhl und ein Bett',
                                 'ein Löffel und eine Gabel', 'die Sonne und eine Lampe',
                                 'ein Buch und eine Zeitung', 'ein Fluss und ein See',
                                 'Schuhe und Handschuhe', 'ein Klavier und eine Gitarre',
                                 'ein Baum und eine Blume', 'ein Flugzeug und ein Vogel',
                                 'eine Uhr und ein Kalender', 'ein Messer und eine Säge',
                                 'ein Boot und eine Ente']],
    ],
    'logic-order' => [
        'name'    => 'Vom Kleinsten zum Größten',
        'pattern' => 'Bring sie in die Reihenfolge, das Kleinste zuerst: {set}.',
        'answer'  => 'Die drei in der richtigen Reihenfolge',
        'hint'    => 'Stell sie dir nebeneinander vor.',
        'lists'   => ['set' => ['eine Ameise, ein Hund, ein Elefant', 'eine Tasse, ein Eimer, eine Badewanne',
                                'eine Minute, eine Stunde, ein Tag', 'ein Kiesel, ein Felsen, ein Berg',
                                'ein Samenkorn, eine Blume, ein Baum', 'ein Schuh, ein Auto, ein Haus',
                                'ein Tropfen, eine Pfütze, ein See', 'eine Münze, ein Teller, ein Tisch',
                                'eine Maus, eine Katze, ein Pferd', 'ein Blatt, ein Ast, ein Stamm',
                                'ein Schritt, eine Straße, ein Land',
                                'ein Löffel, eine Schaufel, ein Bagger',
                                'ein Baby, ein Kind, ein Erwachsener', 'ein Knopf, ein Teller, ein Rad',
                                'eine Kerze, eine Laterne, ein Turm',
                                'eine Schneeflocke, ein Schneeball, ein Schneemann']],
    ],
    'logic-truefalse' => [
        'name'    => 'Richtig oder falsch?',
        'pattern' => 'Richtig oder falsch: {claim}? Sag warum.',
        'answer'  => 'Die richtige Antwort mit einer Begründung',
        'hint'    => 'Ein einziges Gegenbeispiel genügt, damit es falsch ist.',
        'lists'   => ['claim' => ['alle Vögel können fliegen', 'jedes Quadrat ist auch ein Rechteck',
                                  'alle Fische leben im Wasser', 'alle Spinnen haben sechs Beine',
                                  'die Sonne geht im Westen auf', 'manche Katzen haben keinen Schwanz',
                                  'jedes Dreieck hat drei Seiten', 'Eis ist schwerer als Wasser',
                                  'jeder Monat hat dreißig Tage', 'alle Pflanzen haben Blüten',
                                  'ein Wal ist ein Fisch', 'keine Zahl ist gerade und ungerade zugleich']],
    ],
    'geo-hotcold' => [
        'name'    => 'Warmes oder kaltes Land?',
        'pattern' => 'Bräuchtest du {thing} in einem warmen oder in einem kalten Land?',
        'answer'  => 'Beides gilt, mit einer Begründung',
        'hint'    => 'Denk daran, was du am kältesten Tag des Jahres anziehst.',
        'lists'   => ['thing' => ['eine Wollmütze', 'eine Sonnenbrille', 'einen Schal', 'Sandalen',
                                  'einen dicken Mantel', 'einen Sonnenhut', 'Handschuhe',
                                  'einen Ventilator', 'Schneestiefel', 'einen Badeanzug',
                                  'eine warme Decke', 'kurze Hosen', 'ein heißes Getränk',
                                  'Schlittschuhe', 'ein kaltes Getränk', 'Sonnencreme']],
    ],
    'geo-travel' => [
        'name'    => 'Wie kommst du hin?',
        'pattern' => 'Wie würdest du {place} reisen?',
        'answer'  => 'Jede sinnvolle Art zu reisen',
        'hint'    => 'Zu manchen Orten braucht es mehr als eine Reise.',
        'lists'   => ['place' => ['zu einer Insel draußen im Meer', 'auf einen Berggipfel',
                                  'zum Laden am Ende der Straße', 'in ein weit entferntes Land',
                                  'zu einem Bauernhof hinter den Feldern', 'in die Mitte eines großen Sees',
                                  'in eine Stadt auf der anderen Flussseite', 'zum Mond',
                                  'in ein Dorf oben auf einem steilen Berg', 'an den Strand',
                                  'in eine Höhle', 'mitten in einen Wald', 'in eine große Stadt',
                                  'zu einem Leuchtturm auf den Felsen', 'in die Nachbarstraße',
                                  'zu einem Flughafen']],
    ],
    'geo-difference' => [
        'name'    => 'Wo ist der Unterschied?',
        'pattern' => 'Was ist der Unterschied zwischen {pair}?',
        'answer'  => 'Jeder klare Unterschied',
        'hint'    => 'Die Größe ist eine Antwort, aber nicht die einzige.',
        'lists'   => ['pair' => ['einem See und einem Meer', 'einem Hügel und einem Berg',
                                 'einem Dorf und einer Stadt', 'einem Fluss und einem Kanal',
                                 'einer Insel und einer Halbinsel', 'einem Wäldchen und einem Wald',
                                 'einer Straße und einer Autobahn', 'einem Bach und einem Strom',
                                 'einem Strand und einer Klippe', 'einem Bauernhof und einem Feld',
                                 'einer Karte und einem Globus', 'einem Land und einem Kontinent']],
    ],
    'eng-article' => [
        'name'    => 'Der, die oder das?',
        'pattern' => 'Heißt es "der", "die" oder "das" vor "{word}"?',
        'answer'  => 'Der richtige Artikel',
        'hint'    => 'Sprich es laut mit allen dreien und hör, was passt.',
        'lists'   => ['word' => ['Apfel', 'Buch', 'Baum', 'Tisch', 'Wasser', 'Hand',
                                 'Tag', 'Problem', 'Blume', 'Auto', 'Milch', 'Karte',
                                 'Nase', 'Hund', 'Klasse', 'Sofa']],
    ],
    'eng-question' => [
        'name'    => 'Mach eine Frage daraus',
        'pattern' => 'Mach aus diesem Satz eine Frage: „{sentence}“',
        'answer'  => 'Dieselben Wörter, als Frage',
        'hint'    => 'Oft musst du nur die ersten beiden Wörter tauschen.',
        'lists'   => ['sentence' => ['Du hast Hunger.', 'Sie kann schwimmen.', 'Sie sind nach Hause gegangen.',
                                     'Es regnet.', 'Er hat ein Fahrrad.', 'Wir sind spät dran.',
                                     'Der Hund schläft.', 'Du magst Äpfel.',
                                     'Gestern war es kalt.', 'Sie sind fertig.',
                                     'Sie hat den Schlüssel gefunden.', 'Der Bus kommt.',
                                     'Du kannst mich hören.', 'Er war in der Schule.',
                                     'Der Kuchen ist alle.', 'Wir haben genug.']],
    ],
    'nature-baby' => [
        'name'    => 'Tierkinder',
        'pattern' => 'Wie nennt man das Junge {animal}?',
        'answer'  => 'Der richtige Name für das Junge',
        'hint'    => 'Manche haben einen eigenen Namen, manche heißen einfach „Junges“.',
        'lists'   => ['animal' => ['von der Katze', 'vom Hund', 'von der Kuh', 'vom Schaf',
                                   'von der Ente', 'vom Pferd', 'vom Frosch', 'vom Bären',
                                   'von der Ziege', 'vom Huhn', 'vom Schwein', 'vom Schwan',
                                   'vom Hirsch', 'vom Känguru', 'vom Schmetterling', 'von der Eule']],
    ],
    'nature-need' => [
        'name'    => 'Was braucht es?',
        'pattern' => 'Nenne zwei Dinge, die {living} zum Leben braucht.',
        'answer'  => 'Zwei sinnvolle Bedürfnisse',
        'hint'    => 'Essen und Wasser sind zwei - und was noch?',
        'lists'   => ['living' => ['ein Baum', 'ein Hund', 'ein Fisch', 'eine Biene', 'ein Mensch',
                                   'eine Topfpflanze', 'ein Vogel', 'ein Regenwurm', 'ein Pferd',
                                   'eine Katze', 'eine Sonnenblume', 'ein Frosch', 'ein Kaninchen',
                                   'ein Pilz']],
    ],
    'life-tidy' => [
        'name'    => 'Wohin gehört es?',
        'pattern' => 'Wohin gehört {thing}, wenn du aufräumst?',
        'answer'  => 'Jeder sinnvolle Platz',
        'hint'    => 'Dorthin, wo du es das nächste Mal suchen würdest.',
        'lists'   => ['thing' => ['deine Schuhe', 'ein schmutziger Teller', 'ein Buch aus der Bücherei',
                                  'deine Jacke', 'der Müll', 'ein Spielzeugauto',
                                  'ein nasses Handtuch', 'schmutzige Socken', 'die Milch',
                                  'ein Bleistift', 'dein Schulranzen', 'eine leere Flasche',
                                  'ein Apfelrest', 'saubere Wäsche', 'matschige Stiefel',
                                  'eine Schere']],
    ],
    'life-before' => [
        'name'    => 'Was kommt zuerst?',
        'pattern' => 'Nenne zwei Dinge, die du erledigen musst, bevor du {activity}.',
        'answer'  => 'Zwei sinnvolle Schritte',
        'hint'    => 'Denk daran, was schiefginge, wenn du es vergisst.',
        'lists'   => ['activity' => ['schwimmen gehst', 'etwas kochst', 'mit dem Rad losfährst',
                                     'zur Schule aufbrichst', 'Freunde einlädst',
                                     'auf eine lange Wanderung gehst', 'Samen einpflanzt',
                                     'allein mit dem Bus fährst', 'mit den Hausaufgaben anfängst',
                                     'ins Bett gehst', 'ein Tier fütterst', 'deinen Koffer packst']],
    ],
    // Die fünf, die es nur auf Englisch gab
    'life-action' => [
        'name'    => 'Mach es sofort',
        'pattern' => 'Versuche {n} Sekunden lang {action}. Wenn du es schaffst, geht es weiter!',
        'answer'  => 'Die Aufgabe schaffen',
        'hint'    => 'Alle zählen laut mit.',
        'lists'   => ['action' => ['auf einem Bein zu hüpfen', 'auf einem Bein zu stehen',
                                   'so schnell wie möglich zu klatschen', 'dich langsam zu drehen',
                                   'laut zu lachen', 'eine Katze nachzumachen',
                                   'ein Buch auf dem Kopf zu balancieren', 'rückwärts zu gehen',
                                   'deine Zehen zu berühren', 'stillzustehen wie eine Statue',
                                   'ohne den Buchstaben S zu sprechen', 'auf der Stelle zu marschieren']],
    ],
    'life-team' => [
        'name'    => 'Was würdest du tun?',
        'pattern' => 'Was würdest du tun, wenn {situation}? Sag allen einen Weg, damit umzugehen.',
        'answer'  => 'Jede durchdachte Antwort zählt',
        'hint'    => 'Sag, was du zuerst versuchen würdest.',
        'lists'   => ['situation' => ['ein Freund auf dem Schulhof hinfällt',
                                      'sich deine Gruppe auf gar nichts einigen kann',
                                      'du Wasser über den ganzen Tisch schüttest',
                                      'du jemanden ganz allein sitzen siehst',
                                      'jemand bei einem Spiel nicht mitmachen darf',
                                      'zwei Freunde beide anfangen wollen',
                                      'die Regeln unklar sind und ein Streit beginnt',
                                      'jemand allen anderen ständig ins Wort fällt']],
    ],
    'en-word' => [
        'name'    => 'Wörter aus dem Abenteuer',
        'pattern' => 'Was bedeutet das Wort „{word}“? Erkläre es mit deinen eigenen Worten.',
        'answer'  => 'Jede sinnvolle Erklärung zählt',
        'hint'    => 'Bau es in einen Satz über dein Spiel ein.',
        'lists'   => ['word' => ['Wald', 'Fluss', 'Berg', 'Schatz', 'Brücke',
                                 'Burg', 'Drache', 'Kompass', 'Insel', 'Reise',
                                 'Mut', 'Freundschaft', 'Hafen', 'Laterne', 'Schiffbruch', 'Karte']],
    ],
    'science-why' => [
        'name'    => 'Warum passiert das?',
        'pattern' => 'Warum {phenomenon}?',
        'answer'  => 'Jede vernünftige Erklärung zählt',
        'hint'    => 'Sag erst, was dir auffällt, und dann warum du denkst, dass es so ist.',
        'lists'   => ['phenomenon' => ['regnet es', 'gibt es nach dem Regen Regenbögen',
                                       'schmilzt Eis, wenn man es liegen lässt',
                                       'werden die Blätter im Herbst bunt',
                                       'sieht man nachts die Sterne',
                                       'steigen Luftballons mit Helium nach oben',
                                       'sind die Schatten am Nachmittag länger',
                                       'zittern wir, wenn uns kalt ist',
                                       'wird Brot hart, wenn es offen liegt',
                                       'schwimmen Boote',
                                       'ändert der Mond seine Form',
                                       'müssen wir schlafen']],
    ],
    'geo-continent' => [
        'name'    => 'Welcher Kontinent?',
        'pattern' => 'Auf welchem Kontinent liegt {place}?',
        'answer'  => 'Der richtige Kontinent',
        'hint'    => 'Es gibt sieben zur Auswahl.',
        'lists'   => ['place' => ['Ägypten', 'Brasilien', 'Japan', 'Italien', 'Kenia',
                                  'Kanada', 'Indien', 'Norwegen', 'Peru', 'Vietnam',
                                  'Australien', 'Mexiko', 'Spanien', 'China',
                                  'Marokko', 'Argentinien']],
    ],
];
