<?php
/**
 * The question templates in Spanish. Keyed by the English template's code;
 * see install/mission-templates-all.php for how the two halves are joined.
 *
 * GENDER
 *
 * A blank dropped into a Spanish sentence has to agree with it, and the
 * sentence is written once for a dozen different words. So each word list is
 * kept to a single gender - every creature masculine, every container feminine
 * - and the places carry their own article. That way "Hay 5 conejos en la
 * playa" and "Hay 5 patitos en el jardin" are both correct without the sentence
 * having to know which word turned up.
 *
 * The reading and spelling questions are not translations. Rhymes, plurals and
 * past tenses only exist inside one language, so those are written fresh here.
 */

$creatures = ['conejos', 'gatitos', 'cachorros', 'patitos', 'zorros', 'búhos',
              'pingüinos', 'delfines', 'erizos', 'caballos', 'ratones', 'cocodrilos'];

$things = ['botones', 'cromos', 'caramelos', 'lápices', 'guijarros', 'globos',
           'bloques', 'coches', 'sellos', 'dados', 'palitos', 'cubos'];

$places = ['el prado', 'el jardín', 'el estanque', 'el bosque', 'el parque',
           'la playa', 'el huerto', 'la casa del árbol', 'el granero', 'la charca'];

$names = ['Lucía', 'Mateo', 'Sofía', 'Hugo', 'Carmen', 'Diego',
          'Noa', 'Bruno', 'Elena', 'Pablo', 'Ada', 'Nur'];

$containers = ['cestas', 'cajas', 'bolsas', 'huchas', 'bandejas', 'cubetas', 'latas'];

$treats = ['bizcochos', 'plátanos', 'bocadillos', 'caramelos', 'pasteles', 'higos'];

return [

    // ----------------------------------------------------------------- MATHS
    'math-add' => [
        'name'    => 'Sumar',
        'pattern' => 'Hay {a} {creature} en {place}. Llegan {b} más. ¿Cuántos {creature} hay ahora?',
        'answer'  => '{a+b} {creature}',
        'patterns' => [
            'Llegan {b} {creature} más a {place}, donde ya había {a}. ¿Cuántos hay ahora?',
            'Cuenta los {creature} de {place}: primero {a} y luego llegan {b} más.',
        ],
        'hint'    => 'Cuéntalos todos juntos.',
        'lists'   => ['creature' => $creatures, 'place' => $places],
    ],
    'math-sub' => [
        'name'    => 'Restar',
        'pattern' => '{who} ha reunido {a} {thing}. {who} regala {b}. ¿Cuántos {thing} le quedan?',
        'answer'  => '{a-b} {thing}',
        'patterns' => [
            '{who} tenía {a} {thing} esta mañana y ya ha regalado {b}. ¿Cuántos le quedan?',
            'De {a} {thing}, {who} le da {b} a un amigo. ¿Cuántos se queda?',
        ],
        'hint'    => 'Empieza por lo que tenías y quita el resto.',
        'lists'   => ['thing' => $things, 'who' => $names],
    ],
    'math-count-back' => [
        'name'    => 'Contar hacia atrás',
        'pattern' => 'Empieza en {a} y cuenta {b} hacia atrás. ¿Dónde llegas?',
        'answer'  => '{a-b}',
        'patterns' => [
            'Cuenta {b} hacia atrás desde {a}. ¿Qué número dices al final?',
            'Estás en el {a} y das {b} pasos hacia atrás. ¿Dónde te paras?',
        ],
        'hint'    => 'Usa los dedos si te ayuda.',
    ],
    'math-double' => [
        'name'    => 'El doble',
        'pattern' => '{who} tiene {a} {thing} y encuentra exactamente la misma cantidad otra vez. ¿Cuántos tiene ahora?',
        'answer'  => '{a+a} {thing}',
        'patterns' => [
            '{who} tiene {a} {thing}. Dobla esa cantidad. ¿Cuántos son?',
            'Hay {a} {thing} en la mesa y otros tantos en la caja. ¿Cuántos hay en total?',
        ],
        'hint'    => 'El doble es la misma cantidad dos veces.',
        'lists'   => ['thing' => $things, 'who' => $names],
    ],
    'math-mul' => [
        'name'    => 'Grupos de',
        'pattern' => 'Hay {a} {container} y cada una lleva {b} {thing}. ¿Cuántos {thing} hay en total?',
        'answer'  => '{a*b} {thing}',
        'patterns' => [
            '{a} {container}, {b} {thing} en cada una. ¿Cuántos {thing} son?',
            'Cada una de las {a} {container} lleva {b} {thing}. Calcula el total.',
        ],
        'hint'    => 'Cuenta los grupos y luego lo que hay en cada uno.',
        'lists'   => ['container' => $containers, 'thing' => $things],
    ],
    'math-div' => [
        'name'    => 'Repartir',
        'pattern' => 'Reparte {a} {treat} en partes iguales entre {b} amigos. ¿Cuántos le tocan a cada uno?',
        'answer'  => '{a/b} {treat} para cada uno',
        'patterns' => [
            '{b} amigos se reparten {a} {treat} en partes iguales. ¿Cuántos le tocan a cada uno?',
            'Divide {a} {treat} en {b} montones iguales. ¿Cuántos hay en cada montón?',
        ],
        'hint'    => 'Répartelos de uno en uno, como si fueran cartas.',
        'lists'   => ['treat' => $treats],
    ],
    'math-missing' => [
        'name'    => 'El número que falta',
        'pattern' => '{who} tenía algunos {thing}, le dieron {b} más y ahora tiene {c}. ¿Cuántos tenía al principio?',
        'answer'  => '{c-b} {thing}',
        'patterns' => [
            '{who} tiene ahora {c} {thing}, después de que le dieran {b}. ¿Cuántos tenía antes?',
            'A {who} le dieron {b} {thing} y así llegó a {c}. ¿Con cuántos empezó?',
        ],
        'hint'    => 'Ve hacia atrás desde el total.',
        'lists'   => ['thing' => $things, 'who' => $names],
    ],
    'math-word2' => [
        'name'    => 'Problema de monedas',
        'pattern' => 'Tienes {a} monedas. Compras {b} {thing} que cuestan {c} monedas cada uno. ¿Cuántas monedas te quedan?',
        'answer'  => '{a-b*c} monedas',
        'patterns' => [
            '{b} {thing} cuestan {c} monedas cada uno. Pagas con {a} monedas. ¿Cuánto te devuelven?',
            'Empiezas con {a} monedas y compras {b} {thing} a {c} monedas cada uno. ¿Cuánto te queda?',
        ],
        'hint'    => 'Calcula primero lo que gastas y réstalo de lo que tenías.',
        'lists'   => ['thing' => $things],
    ],
    'math-two-step' => [
        'name'    => 'Dos pasos',
        'pattern' => '{who} llena {a} {container} con {b} {thing} en cada una, y luego se caen {c} {thing}. ¿Cuántos quedan guardados?',
        'answer'  => '{a*b-c} {thing}',
        'patterns' => [
            'Se llenan {a} {container} con {b} {thing} cada una y luego se caen {c} {thing}. ¿Cuántos siguen guardados?',
            '{who} mete {b} {thing} en cada una de las {a} {container} y pierde {c} por el camino. ¿Cuántos llegan?',
        ],
        'hint'    => 'Multiplica primero y resta después.',
        'lists'   => ['container' => $containers, 'thing' => $things, 'who' => $names],
    ],

    // -------------------------------------------------------------- LITERACY
    'lit-rhyme' => [
        'name'    => 'Busca una rima',
        'pattern' => 'Di una palabra que rime con "{word}".',
        'answer'  => 'Vale cualquier palabra que rime de verdad',
        'patterns' => [
            '¿Qué palabras riman con "{word}"? Di una.',
            'Busca algo que suene igual que "{word}" al final.',
        ],
        'hint'    => 'Díla en voz alta y escucha el final.',
        'lists'   => ['word' => ['gato', 'flor', 'ratón', 'sol', 'pan', 'mano',
                                 'rana', 'estrella', 'nariz', 'pelota', 'barco', 'campana',
                                 'silla', 'puerta', 'luna', 'gorro', 'tren', 'oveja',
                                 'cuchara', 'pared', 'camino', 'zapato']],
    ],
    'lit-letter' => [
        'name'    => 'El sonido del principio',
        'pattern' => 'Di {a} cosas que empiecen por la letra "{letter}".',
        'answer'  => 'Cualquier {a} palabras válidas',
        'patterns' => [
            'Mira a tu alrededor y encuentra {a} cosas que empiecen por "{letter}".',
            '"{letter}": di {a} cosas que empiecen con ese sonido.',
        ],
        'hint'    => 'Mira a tu alrededor para buscar ideas.',
        'lists'   => ['letter' => ['B', 'C', 'D', 'F', 'G', 'L', 'M', 'P', 'R', 'S', 'T', 'Z']],
    ],
    'lit-opposite' => [
        'name'    => 'Contrarios',
        'pattern' => '¿Cuál es lo contrario de "{word}"?',
        'answer'  => 'El contrario correcto',
        'patterns' => [
            '"{word}": ¿y lo contrario?',
            'Si algo no es "{word}", ¿cómo es?',
        ],
        'hint'    => 'Piensa en la palabra que significa justo al revés.',
        'lists'   => ['word' => ['caliente', 'grande', 'rápido', 'contento', 'día', 'arriba',
                                 'ruidoso', 'mojado', 'lleno', 'temprano', 'duro', 'cerca',
                                 'abierto', 'pesado', 'joven', 'limpio', 'primero', 'dentro',
                                 'dulce', 'áspero', 'valiente', 'despierto']],
    ],
    'lit-define' => [
        'name'    => 'Con tus palabras',
        'pattern' => '¿Qué significa la palabra "{word}"? Explícalo con tus palabras.',
        'answer'  => 'Vale cualquier explicación razonable',
        'patterns' => [
            'Explícale "{word}" a alguien que nunca la ha oído.',
            'Alguien te pregunta qué quiere decir "{word}". ¿Qué le contestas?',
        ],
        'hint'    => 'Prueba a usarla primero en una frase.',
        'lists'   => ['word' => ['valentía', 'curioso', 'amable', 'antiguo', 'frágil',
                                 'generoso', 'testarudo', 'agradecido', 'nervioso', 'leal',
                                 'paciente', 'honesto', 'torpe', 'enorme', 'silencioso',
                                 'celoso', 'educado', 'agotado', 'delicado', 'orgulloso']],
    ],
    'lit-sentence' => [
        'name'    => 'Construye una frase',
        'pattern' => 'Inventa una frase que use "{word}" y "{other}" a la vez.',
        'answer'  => 'Cualquier frase con las dos palabras',
        'patterns' => [
            'Usa "{word}" y "{other}" en la misma frase.',
            'Haz una sola frase con "{word}" y "{other}" dentro.',
        ],
        'hint'    => 'Puede ser todo lo tonta que quieras.',
        'lists'   => ['word'  => ['río', 'castillo', 'tormenta', 'farol', 'puerto', 'prado',
                                  'escalera', 'mercado', 'faro', 'huerto'],
                      'other' => ['silencioso', 'dorado', 'repentino', 'enorme', 'helado', 'torcido',
                                  'olvidado', 'ruidoso', 'del revés', 'invisible']],
    ],
    'lit-story' => [
        'name'    => 'Sigue el cuento',
        'pattern' => 'Cuenta la parte siguiente de la historia: "{opening}"',
        'answer'  => 'Cualquier continuación que encaje',
        'patterns' => [
            'Este es el principio: "{opening}" ¿Qué pasa después?',
            '"{opening}" Sigue tú desde ahí.',
        ],
        'hint'    => 'Con dos o tres frases basta.',
        'lists'   => ['opening' => [
            'La puerta del final de la escalera nunca había estado abierta...',
            'El mapa mostraba una isla que no salía en ningún otro mapa...',
            'Todo el pueblo se despertó hablando al revés...',
            'El faro viejo se encendió solo después de veinte años...',
            'Llegó una carta a nombre de alguien que no vivía allí...',
            'El gato volvió a casa con un collar que nadie había comprado...',
            'Todos los relojes de la casa se pararon en el mismo minuto...',
            'Había una segunda luna en el cielo y solo los niños la veían...',
            'La biblioteca tenía una estantería que ayer no estaba...',
            'Unas huellas salían del mar y terminaban en la puerta de casa...',
            'El árbol más viejo del parque amaneció con una puerta...',
            'Llegó un paquete sin dirección y con un agujero en un lado...',
            'La campana del colegio sonó una hora antes y nadie la había tocado...',
            'Alguien había dibujado un mapa en la última página del cuaderno...',
            'Todos los pájaros se fueron del pueblo la misma tarde...',
            'Una ventana que llevaba años sellada se abrió sola...',
        ]],
    ],

    // --------------------------------------------------------------- ENGLISH
    // In Spanish this is Spanish grammar: plurals and past tenses of its own.
    'eng-plural' => [
        'name'    => 'Uno y muchos',
        'pattern' => '¿Cuál es el plural de "{word}"?',
        'answer'  => 'El plural correcto',
        'patterns' => [
            '¿Cómo se dice "{word}" cuando hay más de uno?',
            'Un "{word}", pero ¿y dos?',
        ],
        'hint'    => 'Algunas palabras cambian más de lo que esperas.',
        'lists'   => ['word' => ['lápiz', 'pez', 'ratón', 'jardín', 'luz',
                                 'camión', 'rey', 'flor', 'pared', 'bebé',
                                 'lámpara', 'razón', 'inglés', 'ciudad', 'maíz',
                                 'sofá', 'reloj', 'nariz', 'joven', 'árbol']],
    ],
    'eng-verb' => [
        'name'    => 'Ayer',
        'pattern' => 'Ponlo en pasado: "Todos los días {verb}."',
        'answer'  => 'El pasado correcto de "{verb}"',
        'patterns' => [
            '"Todos los días {verb}": dilo como si hubiera pasado ayer.',
            'Cambia "{verb}" para que hable del pasado.',
        ],
        'hint'    => 'Dílo como si ya hubiera pasado.',
        'lists'   => ['verb' => ['corro', 'nado', 'como', 'escribo', 'canto',
                                 'pienso', 'traigo', 'juego', 'dibujo', 'duermo',
                                 'voy', 'hago', 'digo', 'tengo', 'salgo',
                                 'leo', 'pongo', 'vengo', 'quiero', 'puedo']],
    ],
    'eng-describe' => [
        'name'    => 'Descríbelo',
        'pattern' => 'Describe {thing} a alguien que no sabe qué es, sin decir la palabra.',
        'answer'  => 'Cualquier descripción clara',
        'patterns' => [
            'Explica qué es {thing} sin decir la palabra.',
            'Alguien nunca ha visto {thing}. Descríbeselo.',
        ],
        'hint'    => 'Empieza por para qué sirve.',
        'lists'   => ['thing' => ['una bicicleta', 'un paraguas', 'una tetera', 'una escalera',
                                  'un telescopio', 'un castillo de arena', 'un molino', 'una cometa',
                                  'un faro', 'una carretilla', 'una cremallera', 'un espejo',
                                  'una escalera de mano', 'un reloj', 'una esponja', 'un silbato',
                                  'un cordon de zapato', 'un muñeco de nieve']],
    ],

    // --------------------------------------------------------------- SCIENCE
    'sci-sense' => [
        'name'    => '¿Qué sentido?',
        'pattern' => '¿Qué parte del cuerpo usas para {sense}?',
        'answer'  => 'El órgano del sentido que toca',
        'patterns' => [
            'Quieres {sense}. ¿Qué parte de ti hace el trabajo?',
            '¿Qué sentido usas para {sense}?',
        ],
        'hint'    => 'Señálala.',
        'lists'   => ['sense' => ['oler una flor', 'oír una campana', 'saborear la miel',
                                  'ver un arco iris', 'notar la arena caliente', 'oír un trueno',
                                  'probar un limón', 'ver una estrella de noche', 'oler pan recién hecho',
                                  'notar un cristal frío', 'oír tu propio nombre', 'probar la sal',
                                  'ver el color rojo', 'notar a un gato ronroneando']],
    ],
    'sci-float' => [
        'name'    => '¿Flota o se hunde?',
        'pattern' => '¿{thing} flotaría o se hundiría en el agua? Di por qué lo piensas.',
        'answer'  => 'Cualquiera de las dos con un motivo',
        'patterns' => [
            'Echas {thing} al agua. ¿Flota o se hunde? ¿Por qué?',
            '¿{thing} se quedaría encima del agua o se iría al fondo? Di por qué.',
        ],
        'hint'    => 'Piensa en lo que pesa para el tamaño que tiene.',
        'lists'   => ['thing' => ['Un corcho', 'Una piedra', 'Una manzana', 'Una moneda', 'Una pluma',
                                  'Una esponja', 'Un clavo', 'Una vela', 'Una naranja', 'Una cuchara de madera',
                                  'Una uva', 'Una botella de plástico cerrada', 'Un clip',
                                  'Un limón', 'Un patito de goma', 'Un ladrillo', 'Un lápiz', 'Una canica']],
    ],
    'sci-change' => [
        'name'    => '¿Qué pasa después?',
        'pattern' => '¿Qué pasa si {event}? Explícalo lo mejor que puedas.',
        'answer'  => 'Una explicación razonable',
        'patterns' => [
            'Di qué verías si {event}.',
            '{event}: ¿qué pasa y por qué?',
        ],
        'hint'    => 'Di lo que verías y luego por qué.',
        'lists'   => ['event' => [
            'dejas un cubito de hielo en una habitación cálida',
            'guardas una planta en un armario oscuro',
            'te frotas las manos muy deprisa',
            'echas sal en un vaso de agua y lo remueves',
            'dejas un globo al sol',
            'un charco se queda al sol toda la mañana',
            'echas el aliento en un cristal frío',
            'dejas una manzana cortada encima de la mesa',
            'acercas un imán a un montón de clips',
            'dejas una bicicleta bajo la lluvia un mes entero',
            'sueltas una piedra y una pluma a la vez',
            'tapas una vela encendida con un tarro',
            'tiendes la ropa mojada en un día de viento',
            'agitas una botella con agua y aceite',
            'plantas una semilla y la riegas cada día',
        ]],
    ],

    // ---------------------------------------------------------------- NATURE
    'nature-animal' => [
        'name'    => 'Sonidos de animales',
        'pattern' => '¿Qué sonido hace {animal}? ¡Imítalo lo mejor que puedas!',
        'answer'  => 'Vale cualquier intento',
        'patterns' => [
            'Haz el sonido que hace {animal}.',
            '{animal} está detrás de ti. ¿Qué oirías?',
        ],
        'hint'    => 'Aquí nadie te pone nota.',
        'lists'   => ['animal' => ['una vaca', 'un pato', 'un león', 'una oveja', 'un búho',
                                   'una rana', 'un caballo', 'una abeja', 'un gato', 'un lobo',
                                   'una cabra', 'un cuervo', 'un cerdo', 'un burro', 'una gallina',
                                   'un ratón', 'una serpiente', 'un elefante', 'un perro',
                                   'una gaviota', 'un mono', 'un grillo']],
    ],
    'nature-home' => [
        'name'    => '¿Dónde vive?',
        'pattern' => '¿Dónde vive {animal}?',
        'answer'  => 'El tipo de hogar correcto',
        'patterns' => [
            '¿Qué tipo de casa tiene {animal}?',
            'Si buscaras {animal}, ¿dónde mirarías?',
        ],
        'hint'    => 'Piensa en lo que necesita para estar a salvo.',
        'lists'   => ['animal' => ['una abeja', 'un conejo', 'un pingüino', 'un camello', 'un pez',
                                   'un búho', 'un topo', 'un cangrejo', 'un murciélago', 'una ardilla',
                                   'un oso polar', 'un canguro', 'una araña', 'un castor', 'una hormiga',
                                   'una golondrina', 'una tortuga', 'un tejón', 'un delfín', 'un erizo']],
    ],
    'nature-season' => [
        'name'    => 'Las estaciones',
        'pattern' => 'Di dos cosas que pasan en {season}. Fíjate {aspect}.',
        'answer'  => 'Dos respuestas razonables',
        'patterns' => [
            'Piensa en {season}. Di dos cosas que cambian {aspect}.',
            '¿Qué es distinto {aspect} en {season}? Di dos cosas.',
        ],
        'hint'    => 'Piensa en el tiempo que hace y en las plantas.',
        'lists'   => ['season' => ['primavera', 'verano', 'otoño', 'invierno'],
                      'aspect' => ['en el tiempo que hace', 'en los árboles', 'en los animales',
                                   'en la ropa que lleva la gente', 'en el jardín']],
    ],
    'nature-chain' => [
        'name'    => 'Quién come qué',
        'pattern' => '¿Qué puede comer {animal}, y quién puede comérselo a él?',
        'answer'  => 'Una cadena alimentaria razonable',
        'patterns' => [
            '{animal} come algo, y algo se come a {animal}. ¿Qué son?',
            '¿Dónde está {animal} en la cadena alimentaria? Di qué hay encima y debajo.',
        ],
        'hint'    => 'Todos los animales son la cena de alguien.',
        'lists'   => ['animal' => ['un ratón', 'una rana', 'un conejo', 'un pez', 'una oruga', 'un gorrión',
                                   'una lombriz', 'un caracol', 'un saltamontes', 'un patito', 'una ardilla',
                                   'una mariquita', 'una gamba', 'un topillo', 'un búho joven', 'un renacuajo']],
    ],

    // ----------------------------------------------------------------- LOGIC
    'logic-odd' => [
        'name'    => 'El intruso',
        'pattern' => '¿Cuál sobra: {set}? Di por qué.',
        'answer'  => 'Cualquier respuesta bien razonada',
        'patterns' => [
            'Uno de estos no encaja: {set}. ¿Cuál y por qué?',
            '{set}: tacha uno y di qué tienen en común los demás.',
        ],
        'hint'    => 'Puede haber más de una respuesta buena.',
        'lists'   => ['set' => [
            'manzana, plátano, zanahoria, pera',
            'perro, gato, pez, conejo',
            'rojo, azul, cuadrado, verde',
            'zapato, calcetín, gorro, cuchara',
            'coche, barco, bicicleta, árbol',
            'cuchara, tenedor, cuchillo, lápiz',
            'lluvia, nieve, niebla, montaña',
            'dos, cuatro, siete, seis',
            'guitarra, tambor, cuadro, piano',
            'lunes, martes, julio, viernes',
            'silla, mesa, nube, cama',
            'león, tigre, vaca, leopardo',
            'ojo, oreja, nariz, guante',
            'río, lago, mar, desierto',
            'fútbol, tenis, ajedrez, natación',
            'roble, pino, rosa, abedul',
            'martillo, sierra, manzana, destornillador',
            'círculo, triángulo, rojo, cuadrado',
        ]],
    ],
    'logic-seq' => [
        'name'    => '¿Qué viene después?',
        'pattern' => '¿Qué número sigue: {a}, {b}, {c}, ... ?',
        'answer'  => 'El número que continúa la serie',
        'patterns' => [
            'Sigue la serie: {a}, {b}, {c}, ...',
            '{a}, {b}, {c}: ¿qué número va después?',
        ],
        'hint'    => 'Averigua el salto que hay entre ellos.',
    ],
    'logic-riddle' => [
        'name'    => 'Adivinanza',
        'pattern' => '{riddle}',
        'answer'  => 'La solución de la adivinanza',
        'patterns' => [
            'Aquí va una adivinanza. {riddle}',
            'A ver si aciertas esta: {riddle}',
        ],
        'hint'    => 'Léela dos veces: el truco está en cómo lo dice.',
        'lists'   => ['riddle' => [
            'Tengo agujas pero no coso. ¿Qué soy?',
            'Cuanto más seco, más mojada estoy. ¿Qué soy?',
            'Tengo teclas pero no abro ninguna puerta. ¿Qué soy?',
            'Cuanto más me quitas, más grande me hago. ¿Qué soy?',
            'Subo y bajo sin moverme del sitio. ¿Qué soy?',
            'Tengo cara y dos manecillas, pero ni brazos ni piernas. ¿Qué soy?',
            'Estoy llena de agujeros y aún así guardo agua. ¿Qué soy?',
            'Te sigo todo el día y de noche desaparezco. ¿Qué soy?',
            'Tengo cuello pero no cabeza. ¿Qué soy?',
            'Cuanta más hay de mí, menos ves. ¿Qué soy?',
            'Tengo dientes pero no como. ¿Qué soy?',
            'Soy alta de joven y baja de vieja. ¿Qué soy?',
            'Tengo hojas pero no soy un árbol. ¿Qué soy?',
            'Me puedes coger pero no lanzar. ¿Qué soy?',
            'Bajo siempre y nunca subo. ¿Qué soy?',
            'Tengo cauce pero no duermo, y boca pero no como. ¿Qué soy?',
            'Tengo ojo pero no veo. ¿Qué soy?',
            '¿Qué hay que romper antes de poder usarlo?',
        ]],
    ],

    // ------------------------------------------------------------ LIFE SKILLS
    'life-kind' => [
        'name'    => 'Algo amable',
        'pattern' => 'Di una cosa amable que puedas hacer hoy por {who}.',
        'answer'  => 'Vale cualquier idea amable',
        'patterns' => [
            'Piensa en algo amable que podrías hacer por {who}.',
            '¿Cómo podrías alegrar hoy a {who}?',
        ],
        'hint'    => 'Las cosas pequeñas también cuentan.',
        'lists'   => ['who' => ['un amigo', 'alguien de tu familia', 'un vecino',
                                'alguien nuevo en el colegio', 'alguien que está triste',
                                'un niño más pequeño', 'alguien que te ayudó la semana pasada',
                                'un profesor', 'alguien que come solo', 'un abuelo',
                                'alguien que está malito', 'la persona que se sienta a tu lado',
                                'alguien con las manos ocupadas', 'alguien que ha perdido un juego',
                                'alguien con quien te enfadaste', 'alguien que acaba de llegar al país']],
    ],
    'life-safe' => [
        'name'    => 'Estar a salvo',
        'pattern' => '¿Qué deberías hacer si {situation}?',
        'answer'  => 'Cualquier respuesta sensata y segura',
        'patterns' => [
            '{situation}: ¿qué haces lo primero?',
            'Imagina que {situation}. ¿Qué es lo más seguro que puedes hacer?',
        ],
        'hint'    => 'Buscar a un adulto de confianza suele ser el primer paso.',
        'lists'   => ['situation' => [
            'te pierdes de tu adulto en una tienda',
            'un desconocido te pide que vayas con él',
            'hueles a quemado en casa',
            'ves que están haciendo daño a alguien',
            'te encuentras mal en el colegio',
            'te cortas un dedo y no para de sangrar',
            'suena la alarma de incendios y estás arriba',
            'alguien por internet te pregunta dónde vives',
            'encuentras un bote de pastillas en el suelo',
            'la pelota se te va a la carretera',
            'vas en bici y los frenos dejan de funcionar',
            'un perro que no conoces corre hacia ti',
            'te pierdes camino de casa',
            'alguien te manda mensajes que te hacen sentir mal',
            'eres el primero en encontrar a alguien que se ha caído',
        ]],
    ],
    'life-choice' => [
        'name'    => '¿Qué harías tú?',
        'pattern' => '¿Qué harías si {situation}?',
        'answer'  => 'No hay una sola respuesta correcta: basta con ser amable',
        'patterns' => [
            'Imagina que {situation}. ¿Qué haces después?',
            '{situation}: háblalo con los demás. ¿Qué elegirías?',
        ],
        'hint'    => 'Di qué harías y por qué.',
        'lists'   => ['situation' => [
            'un amigo carga con la culpa de algo que hiciste tú',
            'se te olvida traer los deberes',
            'te encuentras algo que es de otra persona',
            'has prometido la misma tarde a dos personas',
            'alguien copia tu trabajo y lo felicitan por él',
            'rompes algo y nadie te ha visto',
            'en una tienda te devuelven de más',
            'tu equipo quiere dejar fuera del juego a alguien',
            'un amigo te cuenta un secreto que te preocupa',
            'vas ganando y tu amigo quiere abandonar',
            'alguien se ríe de cómo habla otro niño',
            'te preguntan algo y no sabes la respuesta',
            'un amigo quiere copiarte los deberes',
            'sin querer haces daño a alguien jugando',
            'te regalan algo que no te gusta',
            'ves que a alguien se le cae dinero sin darse cuenta',
        ]],
    ],

    // ------------------------------------------------------------- GEOGRAPHY
    'geo-where' => [
        'name'    => 'Cerca y lejos',
        'pattern' => '¿Encontrarías {thing} cerca de tu casa, o lejos?',
        'answer'  => 'Cualquiera de las dos, con un motivo',
        'patterns' => [
            '¿{thing} es de las cosas que hay cerca o de las que están lejos?',
            '{thing}: ¿cerca de tu casa o muy lejos? ¿Por qué?',
        ],
        'hint'    => 'Piensa en lo que hay alrededor de donde vives.',
        'lists'   => ['thing' => ['una montaña', 'una playa', 'un río', 'un desierto',
                                  'un bosque', 'un puerto', 'un volcán', 'una granja',
                                  'una estación de tren', 'un glaciar', 'un lago', 'una isla',
                                  'un canal', 'una selva', 'una cascada', 'una cueva',
                                  'un puente sobre un valle', 'un campo de trigo']],
    ],
    'geo-direction' => [
        'name'    => '¿Hacia dónde?',
        'pattern' => 'Si miras hacia el {direction} y giras {turn}, ¿hacia dónde miras ahora?',
        'answer'  => 'La dirección que queda {turn} del {direction}',
        'patterns' => [
            'Míralo al {direction} y gira {turn}. ¿Hacia dónde miras ahora?',
            'Estás mirando al {direction}. Giras {turn}: ¿qué dirección es esa?',
        ],
        'hint'    => 'Imagina una brújula, o usa las manos.',
        'lists'   => ['direction' => ['norte', 'sur', 'este', 'oeste'],
                      'turn'      => ['a la derecha', 'a la izquierda', 'dos veces a la derecha',
                                      'media vuelta']],
    ],
    'geo-place' => [
        'name'    => 'Lugares del mundo',
        'pattern' => 'Di un país donde esperarías encontrar {feature}, y explica por qué.',
        'answer'  => 'Cualquier país que encaje, con un motivo',
        'patterns' => [
            '¿Qué país tendría {feature}? Di cómo lo sabes.',
            '¿A qué parte del mundo irías para ver {feature}?',
        ],
        'hint'    => 'Piensa en el frío o el calor que hace allí.',
        'lists'   => ['feature' => ['una selva tropical', 'un desierto', 'nieve todo el año',
                                    'volcanes activos', 'arrecifes de coral', 'ríos muy largos',
                                    'pingüinos en libertad', 'olivares', 'té cultivado en laderas',
                                    'pastores de renos', 'montañas muy altas con escaladores',
                                    'canales en vez de calles', 'elefantes salvajes', 'fiordos',
                                    'molinos de viento por todas partes', 'una muralla muy larga']],
    ],
    // ----------------------------------------------------- NUEVAS PREGUNTAS
    'sci-hotcold' => [
        'name'    => 'Frío o caliente',
        'pattern' => '{thing}: ¿es algo frío o algo caliente?',
        'answer'  => 'Lo que sea, con un motivo',
        'patterns' => [
            '¿{thing} se notaría caliente o frío al tocarlo?',
            'Frío o caliente: {thing}?',
        ],
        'hint'    => 'Piensa en tocarlo.',
        'lists'   => ['thing' => ['El helado', 'La sopa', 'La nieve', 'Un radiador', 'El mar en invierno',
                                  'Una taza de té', 'El interior de la nevera', 'La llama de una vela',
                                  'La arena de la playa en verano', 'Un cubito de hielo', 'Una bolsa de agua caliente',
                                  'El rocío de la mañana', 'Un horno', 'Una bola de nieve', 'La leche templada',
                                  'Un congelador', 'Una pared al sol', 'El agua del grifo frío']],
    ],
    'sci-living' => [
        'name'    => '¿Está vivo?',
        'pattern' => '{thing}: ¿es un ser vivo? ¿Cómo lo sabes?',
        'answer'  => 'La respuesta correcta con cualquier motivo razonable',
        'patterns' => [
            '¿Dirías que {thing} es un ser vivo? ¿Por qué?',
            'Vivo o no vivo: {thing}? Da un motivo.',
        ],
        'hint'    => 'Los seres vivos crecen y necesitan algo para seguir adelante.',
        'lists'   => ['thing' => ['Un árbol', 'Una piedra', 'Un gato', 'Una nube', 'Una seta',
                                  'Una bicicleta', 'Una lombriz', 'Un río', 'Una margarita', 'Un peluche',
                                  'Una araña', 'Una vela', 'La hierba', 'Una concha', 'Una abeja',
                                  'Un charco', 'Una semilla', 'Un robot de juguete']],
    ],
    'logic-same' => [
        'name'    => '¿En qué se parecen?',
        'pattern' => '¿En qué se parecen {pair}?',
        'answer'  => 'Cualquier cosa razonable que compartan',
        'patterns' => [
            '{pair}: di una cosa que compartan.',
            'Piensa en {pair}. ¿Qué tienen igual?',
        ],
        'hint'    => 'Piensa para qué sirven o de qué están hechos.',
        'lists'   => ['pair' => ['una bicicleta y un coche', 'una manzana y un plátano',
                                 'un perro y un lobo', 'la lluvia y la nieve', 'una silla y una cama',
                                 'una cuchara y un tenedor', 'el sol y una lámpara',
                                 'un libro y un periódico', 'un río y un lago',
                                 'los zapatos y los guantes', 'un piano y una guitarra',
                                 'un árbol y una flor', 'un avión y un pájaro',
                                 'un reloj y un calendario', 'un cuchillo y una sierra',
                                 'un barco y un pato']],
    ],
    'logic-order' => [
        'name'    => 'De menor a mayor',
        'pattern' => 'Ordénalos de menor a mayor: {set}.',
        'answer'  => 'Los tres en el orden correcto',
        'patterns' => [
            'De menor a mayor: {set}. Dílos en orden.',
            '{set}: ¿cuál es el más pequeño y cuál el más grande?',
        ],
        'hint'    => 'Imagínalos uno al lado del otro.',
        'lists'   => ['set' => ['una hormiga, un perro, un elefante', 'una taza, un cubo, una bañera',
                                'un minuto, una hora, un día', 'un guijarro, una roca, una montaña',
                                'una semilla, una flor, un árbol', 'un zapato, un coche, una casa',
                                'una gota, un charco, un lago', 'una moneda, un plato, una mesa',
                                'un ratón, un gato, un caballo', 'una hoja, una rama, un tronco',
                                'un paso, una calle, un país', 'una cuchara, una pala, una excavadora',
                                'un bebé, un niño, un adulto', 'un botón, un plato, una rueda',
                                'una vela, una farola, una torre',
                                'un copo de nieve, una bola de nieve, un muñeco de nieve']],
    ],
    'logic-truefalse' => [
        'name'    => '¿Verdadero o falso?',
        'pattern' => '¿Verdadero o falso: {claim}? Di por qué.',
        'answer'  => 'La respuesta correcta con un motivo',
        'patterns' => [
            '¿Esto está bien o mal: {claim}? Explícalo.',
            'Alguien dice que {claim}. ¿Estás de acuerdo? Di por qué.',
        ],
        'hint'    => 'Basta un ejemplo que no encaje para que sea falso.',
        'lists'   => ['claim' => ['todos los pájaros vuelan', 'todo cuadrado es también un rectángulo',
                                  'todos los peces viven en el agua', 'todas las arañas tienen seis patas',
                                  'el sol sale por el oeste', 'algunos gatos no tienen cola',
                                  'todos los triángulos tienen tres lados', 'el hielo pesa más que el agua',
                                  'todos los meses tienen treinta días', 'todas las plantas tienen flores',
                                  'una ballena es un pez', 'ningún número es par e impar a la vez']],
    ],
    'geo-hotcold' => [
        'name'    => '¿Sitio cálido o frío?',
        'pattern' => '¿Necesitarías {thing} en un sitio cálido o en uno frío?',
        'answer'  => 'Lo que sea, con un motivo',
        'patterns' => [
            '{thing}: ¿lo meterías en la maleta para un país cálido o para uno frío?',
            'País cálido o país frío: ¿dónde necesitas {thing}?',
        ],
        'hint'    => 'Piensa en lo que te pones el día más frío del año.',
        'lists'   => ['thing' => ['un gorro de lana', 'gafas de sol', 'una bufanda', 'sandalias',
                                  'un abrigo grueso', 'un sombrero para el sol', 'guantes', 'un ventilador',
                                  'botas de nieve', 'un bañador', 'una manta gruesa', 'pantalón corto',
                                  'una bebida caliente', 'patines de hielo', 'una bebida fría', 'crema solar']],
    ],
    'geo-travel' => [
        'name'    => '¿Cómo llegarías?',
        'pattern' => '¿Cómo viajarías hasta {place}?',
        'answer'  => 'Cualquier forma razonable de viajar',
        'patterns' => [
            'Planea el viaje hasta {place}. ¿En qué vas?',
            '¿Cómo llega la gente hasta {place}?',
        ],
        'hint'    => 'A algunos sitios hace falta más de un viaje.',
        'lists'   => ['place' => ['una isla en medio del mar', 'la cima de una montaña',
                                  'la tienda del final de la calle', 'un país muy lejano',
                                  'una granja al otro lado de los campos', 'el centro de un lago grande',
                                  'un pueblo al otro lado del río', 'la luna',
                                  'una aldea en una cuesta empinada', 'la playa', 'una cueva',
                                  'el centro de un bosque', 'una ciudad grande',
                                  'un faro sobre las rocas', 'la calle de al lado', 'un aeropuerto']],
    ],
    'geo-difference' => [
        'name'    => '¿En qué se diferencian?',
        'pattern' => '¿En qué se diferencian {pair}?',
        'answer'  => 'Cualquier diferencia clara',
        'patterns' => [
            '{pair}: ¿en qué se distinguen?',
            'Explica qué hace distintos a {pair}.',
        ],
        'hint'    => 'El tamaño es una respuesta, pero no la única.',
        'lists'   => ['pair' => ['un lago y un mar', 'una colina y una montaña',
                                 'un pueblo y una ciudad', 'un río y un canal',
                                 'una isla y una península', 'un bosque y una selva',
                                 'una carretera y una autopista', 'un arroyo y un río',
                                 'una playa y un acantilado', 'una granja y un campo',
                                 'un mapa y un globo terráqueo', 'un país y un continente']],
    ],
    'eng-article' => [
        'name'    => '¿El o la?',
        'pattern' => '¿Se dice "el" o "la" delante de "{word}"?',
        'answer'  => 'El artículo correcto',
        'patterns' => [
            '"{word}": ¿lleva "el" o "la"?',
            'Di "{word}" con el artículo delante que le toca.',
        ],
        'hint'    => 'Di la palabra en voz alta con las dos y escucha cuál suena bien.',
        'lists'   => ['word' => ['manzana', 'libro', 'árbol', 'mesa', 'agua', 'mano',
                                 'día', 'problema', 'flor', 'coche', 'leche', 'mapa',
                                 'nariz', 'perro', 'clase', 'sofá']],
    ],
    'eng-question' => [
        'name'    => 'Conviértelo en pregunta',
        'pattern' => 'Convierte esto en una pregunta: "{sentence}"',
        'answer'  => 'Las mismas palabras, en forma de pregunta',
        'patterns' => [
            'En vez de decirlo, pregúntalo: "{sentence}"',
            '"{sentence}": ahora hazlo pregunta.',
        ],
        'hint'    => 'A veces basta con cambiar el orden y la entonación.',
        'lists'   => ['sentence' => ['Tienes hambre.', 'Ella sabe nadar.', 'Se fueron a casa.',
                                     'Está lloviendo.', 'Él tiene una bici.', 'Llegamos tarde.',
                                     'El perro está dormido.', 'Te gustan las manzanas.',
                                     'Ayer hacía frío.', 'Están listos.',
                                     'Ella encontró la llave.', 'El autobús ya viene.',
                                     'Puedes oírme.', 'Él estaba en el colegio.',
                                     'Se acabó la tarta.', 'Tenemos suficiente.']],
    ],
    'nature-baby' => [
        'name'    => 'Crías de animales',
        'pattern' => '¿Cómo se llama la cría de {animal}?',
        'answer'  => 'El nombre correcto de la cría',
        'patterns' => [
            '{animal} tiene una cría. ¿Cómo se llama?',
            '¿Qué nombre le damos a la cría de {animal}?',
        ],
        'hint'    => 'Algunas tienen nombre propio y otras son solo "una cría".',
        'lists'   => ['animal' => ['el gato', 'el perro', 'la vaca', 'la oveja', 'el pato', 'el caballo',
                                   'la rana', 'el oso', 'la cabra', 'la gallina', 'el cerdo', 'el cisne',
                                   'el ciervo', 'el canguro', 'la mariposa', 'el búho']],
    ],
    'nature-need' => [
        'name'    => '¿Qué necesita?',
        'pattern' => 'Di dos cosas que {living} necesita para seguir vivo.',
        'answer'  => 'Dos necesidades razonables',
        'patterns' => [
            '{living}: di dos cosas sin las que no puede vivir.',
            '¿Qué necesitaría {living} si tú lo cuidaras?',
        ],
        'hint'    => 'Comida y agua son dos, ¿qué más?',
        'lists'   => ['living' => ['un árbol', 'un perro', 'un pez', 'una abeja', 'una persona',
                                   'una planta en una maceta', 'un pájaro', 'una lombriz', 'un caballo',
                                   'un gato', 'un girasol', 'una rana', 'un conejo', 'una seta']],
    ],
    'life-tidy' => [
        'name'    => '¿Dónde va?',
        'pattern' => 'Cuando recoges, ¿dónde va {thing}?',
        'answer'  => 'Cualquier sitio razonable',
        'patterns' => [
            'Estás recogiendo: ¿cuál es el sitio de {thing}?',
            '{thing} está en el suelo. ¿Dónde debería estar?',
        ],
        'hint'    => 'Donde lo buscarías la próxima vez.',
        'lists'   => ['thing' => ['tus zapatos', 'un plato sucio', 'un libro de la biblioteca',
                                  'tu abrigo', 'la basura', 'un coche de juguete', 'una toalla mojada',
                                  'los calcetines sucios', 'la leche', 'un lápiz', 'tu mochila',
                                  'una botella vacía', 'un corazón de manzana', 'la ropa limpia',
                                  'las botas llenas de barro', 'unas tijeras']],
    ],
    'life-before' => [
        'name'    => '¿Qué va primero?',
        'pattern' => 'Di dos cosas que hay que hacer antes de {activity}.',
        'answer'  => 'Dos pasos razonables',
        'patterns' => [
            '¿Qué hay que hacer antes de {activity}? Di dos cosas.',
            'Estás a punto de {activity}. ¿Qué dejas resuelto primero?',
        ],
        'hint'    => 'Piensa en qué saldría mal si se te olvidara.',
        'lists'   => ['activity' => ['ir a nadar', 'cocinar una comida', 'salir en bici',
                                     'salir para el colegio', 'invitar a amigos a casa',
                                     'ir de excursión larga', 'plantar semillas',
                                     'coger tú solo el autobús', 'empezar los deberes',
                                     'irte a la cama', 'dar de comer a una mascota', 'hacer la maleta']],
    ],
    // Los cinco que solo existían en inglés
    'life-action' => [
        'name'    => 'Házlo ahora',
        'pattern' => 'Intenta {action} durante {n} segundos. ¡Si lo consigues, sigues jugando!',
        'answer'  => 'Completar la acción',
        'patterns' => [
            '¿Puedes {action} durante {n} segundos? ¡Ya!',
            '{n} segundos para {action}. Que cuenten todos.',
        ],
        'hint'    => 'Que todos cuenten en voz alta.',
        'lists'   => ['action' => ['saltar a la pata coja', 'quedarte de pie sobre un pie',
                                   'aplaudir lo más rápido que puedas', 'dar vueltas despacio',
                                   'reírte a carcajadas', 'imitar a un gato',
                                   'sostener un libro en la cabeza', 'andar hacia atrás',
                                   'tocarte los pies', 'quedarte quieto como una estatua',
                                   'hablar sin decir la letra S', 'marchar sin moverte del sitio']],
    ],
    'life-team' => [
        'name'    => '¿Qué harías tú?',
        'pattern' => '¿Qué harías si {situation}? Cuéntale a todos una manera de resolverlo.',
        'answer'  => 'Cualquier respuesta pensada',
        'patterns' => [
            'Imagina que {situation}. ¿Qué se te ocurre?',
            '{situation}: dile a la mesa una manera de arreglarlo.',
        ],
        'hint'    => 'Di qué intentarías primero.',
        'lists'   => ['situation' => ['un amigo se cae en el patio',
                                      'tu grupo no se pone de acuerdo en nada',
                                      'derramas agua por toda la mesa',
                                      'ves a alguien sentado solo',
                                      'dejan a alguien fuera de un juego',
                                      'dos amigos quieren empezar los dos',
                                      'las reglas no estaban claras y empieza una discusión',
                                      'alguien interrumpe a todo el mundo']],
    ],
    'en-word' => [
        'name'    => 'Palabras de aventura',
        'pattern' => '¿Qué significa la palabra "{word}"? Explícalo con tus palabras.',
        'answer'  => 'Vale cualquier explicación razonable',
        'patterns' => [
            'Alguien en tu juego dice "{word}". ¿Qué quiere decir?',
            'Explica "{word}" como si estuvieras contando la historia.',
        ],
        'hint'    => 'Úsala en una frase sobre tu juego.',
        'lists'   => ['word' => ['bosque', 'río', 'montaña', 'tesoro', 'puente',
                                 'castillo', 'dragón', 'brújula', 'isla', 'viaje',
                                 'valentía', 'amistad', 'puerto', 'farol', 'naufragio', 'mapa']],
    ],
    'science-why' => [
        'name'    => '¿Por qué pasa eso?',
        'pattern' => '¿Por qué {phenomenon}?',
        'answer'  => 'Cualquier explicación razonable',
        'patterns' => [
            '¿Sabes explicar por qué {phenomenon}?',
            'Alguien pregunta: ¿por qué {phenomenon}? ¿Qué le dices?',
        ],
        'hint'    => 'Di primero lo que has visto y luego por qué crees que pasa.',
        'lists'   => ['phenomenon' => ['llueve', 'salen arcoíris después de la lluvia',
                                       'se derrite el hielo si lo dejas fuera',
                                       'cambian de color las hojas en otoño',
                                       'se ven las estrellas de noche',
                                       'flotan los globos llenos de helio',
                                       'son más largas las sombras por la tarde',
                                       'tiritamos cuando tenemos frío',
                                       'se pone duro el pan si lo dejas fuera',
                                       'flotan los barcos',
                                       'cambia de forma la luna',
                                       'necesitamos dormir']],
    ],
    'geo-continent' => [
        'name'    => '¿Qué continente?',
        'pattern' => '¿En qué continente está {place}?',
        'answer'  => 'El continente correcto',
        'patterns' => [
            '{place} está en qué continente?',
            'Señala el continente al que pertenece {place} y dí su nombre.',
        ],
        'hint'    => 'Hay siete para elegir.',
        'lists'   => ['place' => ['Egipto', 'Brasil', 'Japón', 'Italia', 'Kenia',
                                  'Canadá', 'India', 'Noruega', 'Perú', 'Vietnam',
                                  'Australia', 'México', 'España', 'China',
                                  'Marruecos', 'Argentina']],
    ],
];
