<?php
/**
 * The question templates a game draws its mission cards from.
 *
 * HOW A TEMPLATE WORKS
 *
 *     pattern    'There are {a} {animal}s in the {place}. {b} more arrive...'
 *     answer     '{a+b} {animal}s'
 *     variables  ['a' => ['min' => 2, 'max' => 12],
 *                 'animal' => ['list' => [...]], 'place' => ['list' => [...]]]
 *
 * Numbers are drawn between min and max; a list picks one entry at random. The
 * lists are what carry the variety: a template with two twelve-word lists and
 * two numbers reads differently almost every time it is dealt. Without them a
 * sixty-card maths deck was the same two sentences - rabbits and apples - with
 * the digits swapped, thirty times each.
 *
 * TIER is starter on every row. Templates are not sold by plan: a plan buys
 * maps, characters, card designs and the Advanced level, and what limits the
 * questions a game can reach is its LEVEL, which the plan already gates. Left
 * as it was, a Starter buyer making a 90-card Standard game - which the plan
 * sheet entitles them to - drew from the five beginner templates alone.
 *
 * Kept out of Seeder.php so that install and tools/refresh-mission-templates.php
 * read the same list.
 */

// ---------------------------------------------------------------------------
//  Word lists, shared between templates
// ---------------------------------------------------------------------------

$creatures = ['rabbits', 'kittens', 'puppies', 'ducklings', 'frogs', 'bees',
              'penguins', 'foxes', 'owls', 'turtles', 'squirrels', 'dolphins'];

$things = ['apples', 'marbles', 'stickers', 'crayons', 'shells', 'acorns',
           'buttons', 'pebbles', 'ribbons', 'conkers', 'feathers', 'cherries'];

$places = ['meadow', 'garden', 'pond', 'forest', 'playground', 'beach',
           'orchard', 'treehouse', 'barn', 'rockpool'];

$names = ['Maya', 'Ben', 'Chloe', 'Kai', 'Cora', 'Theo', 'Sana', 'Milo',
          'Bella', 'Pedro', 'Ada', 'Noor'];

$containers = ['baskets', 'boxes', 'jars', 'crates', 'baskets', 'buckets', 'trays'];

$treats = ['biscuits', 'grapes', 'sandwiches', 'strawberries', 'muffins', 'plums'];

return [

    // =======================================================================
    //  MATHS
    // =======================================================================
    [
        'code' => 'math-add', 'name' => 'Adding on', 'subject' => 'math',
        'level' => 'beginner', 'sticker' => 'star',
        'pattern' => 'There are {a} {creature} in the {place}. {b} more come along to join them. How many {creature} are there now?',
        'answer'  => '{a+b} {creature}',
        'variables' => ['a' => ['min' => 2, 'max' => 12], 'b' => ['min' => 1, 'max' => 8],
                        'creature' => ['list' => $creatures], 'place' => ['list' => $places]],
        'hint' => 'Count them all together.',
    ],
    [
        'code' => 'math-sub', 'name' => 'Taking away', 'subject' => 'math',
        'level' => 'beginner', 'sticker' => 'leaf',
        'pattern' => '{who} collected {a} {thing}. {who} gives {b} of them away. How many {thing} are left?',
        'answer'  => '{a-b} {thing}',
        'variables' => ['a' => ['min' => 6, 'max' => 20], 'b' => ['min' => 1, 'max' => 5],
                        'thing' => ['list' => $things], 'who' => ['list' => $names]],
        'hint' => 'Start with what you had and take the rest away.',
    ],
    [
        'code' => 'math-count-back', 'name' => 'Counting back', 'subject' => 'math',
        'level' => 'beginner', 'sticker' => 'footprint',
        'pattern' => 'Start at {a} and count back {b}. Where do you land?',
        'answer'  => '{a-b}',
        'variables' => ['a' => ['min' => 10, 'max' => 20], 'b' => ['min' => 2, 'max' => 8]],
        'hint' => 'Use your fingers if it helps.',
    ],
    [
        'code' => 'math-double', 'name' => 'Doubling', 'subject' => 'math',
        'level' => 'beginner', 'sticker' => 'gem',
        'pattern' => '{who} has {a} {thing} and finds exactly the same number again. How many now?',
        'answer'  => '{a+a} {thing}',
        'variables' => ['a' => ['min' => 2, 'max' => 10],
                        'thing' => ['list' => $things], 'who' => ['list' => $names]],
        'hint' => 'Double means the same amount twice.',
    ],

    [
        'code' => 'math-mul', 'name' => 'Groups of', 'subject' => 'math',
        'level' => 'standard', 'sticker' => 'sun',
        'pattern' => 'There are {a} {container} and each one holds {b} {thing}. How many {thing} altogether?',
        'answer'  => '{a*b} {thing}',
        'variables' => ['a' => ['min' => 2, 'max' => 9], 'b' => ['min' => 2, 'max' => 9],
                        'container' => ['list' => $containers], 'thing' => ['list' => $things]],
        'hint' => 'Count the groups, then count what is in each one.',
    ],
    [
        'code' => 'math-div', 'name' => 'Sharing out', 'subject' => 'math',
        'level' => 'standard', 'sticker' => 'heart',
        'pattern' => 'Share {a} {treat} equally between {b} friends. How many does each friend get?',
        'answer'  => '{a/b} {treat} each',
        'variables' => ['a' => ['min' => 12, 'max' => 48, 'step' => 6], 'b' => ['min' => 2, 'max' => 6],
                        'treat' => ['list' => $treats]],
        'hint' => 'Deal them out one at a time, like cards.',
    ],
    [
        'code' => 'math-missing', 'name' => 'The missing number', 'subject' => 'math',
        'level' => 'standard', 'sticker' => 'key',
        'pattern' => '{who} had some {thing}, was given {b} more, and now has {c}. How many did {who} start with?',
        'answer'  => '{c-b} {thing}',
        'variables' => ['b' => ['min' => 3, 'max' => 15], 'c' => ['min' => 20, 'max' => 60],
                        'thing' => ['list' => $things], 'who' => ['list' => $names]],
        'hint' => 'Work backwards from the total.',
    ],

    [
        'code' => 'math-word2', 'name' => 'Money problem', 'subject' => 'math',
        'level' => 'advanced', 'sticker' => 'gem',
        'pattern' => 'You have {a} coins. You buy {b} {thing} costing {c} coins each. How many coins are left?',
        'answer'  => '{a-b*c} coins',
        'variables' => ['a' => ['min' => 50, 'max' => 100, 'step' => 10], 'b' => ['min' => 2, 'max' => 4],
                        'c' => ['min' => 5, 'max' => 12], 'thing' => ['list' => $things]],
        'hint' => 'Work out the cost first, then take it off what you had.',
    ],
    [
        'code' => 'math-two-step', 'name' => 'Two steps', 'subject' => 'math',
        'level' => 'advanced', 'sticker' => 'rocket',
        'pattern' => '{who} packs {a} {container} with {b} {thing} in each, then {c} {thing} fall out. How many are packed?',
        'answer'  => '{a*b-c} {thing}',
        'variables' => ['a' => ['min' => 3, 'max' => 8], 'b' => ['min' => 4, 'max' => 9],
                        'c' => ['min' => 2, 'max' => 10], 'container' => ['list' => $containers],
                        'thing' => ['list' => $things], 'who' => ['list' => $names]],
        'hint' => 'Multiply first, then subtract.',
    ],

    // =======================================================================
    //  LITERACY
    // =======================================================================
    [
        'code' => 'lit-rhyme', 'name' => 'Find a rhyme', 'subject' => 'literacy',
        'level' => 'beginner', 'sticker' => 'book',
        'pattern' => 'Say a word that rhymes with "{word}".',
        'answer'  => 'Any real rhyming word counts',
        'variables' => ['word' => ['list' => ['cat', 'star', 'tree', 'moon', 'bell', 'cake',
                                              'frog', 'snail', 'nose', 'ring', 'boat', 'hen',
                                              'sock', 'chair', 'light', 'blue', 'door', 'mouse',
                                              'spoon', 'wall', 'train', 'sheep']]],
        'hint' => 'Say it out loud and listen to the ending.',
    ],
    [
        'code' => 'lit-letter', 'name' => 'Starting sound', 'subject' => 'literacy',
        'level' => 'beginner', 'sticker' => 'bulb',
        'pattern' => 'Name {a} things that begin with the letter "{letter}".',
        'answer'  => 'Any {a} valid words',
        'variables' => ['a' => ['min' => 2, 'max' => 4],
                        'letter' => ['list' => ['B', 'C', 'D', 'F', 'G', 'H', 'L', 'M', 'P', 'R', 'S', 'T']]],
        'hint' => 'Look around the room for ideas.',
    ],
    [
        'code' => 'lit-opposite', 'name' => 'Opposites', 'subject' => 'literacy',
        'level' => 'beginner', 'sticker' => 'flag',
        'pattern' => 'What is the opposite of "{word}"?',
        'answer'  => 'The correct opposite',
        'variables' => ['word' => ['list' => ['hot', 'big', 'fast', 'happy', 'day', 'up',
                                              'loud', 'wet', 'full', 'early', 'hard', 'near',
                                              'open', 'heavy', 'young', 'clean', 'first', 'inside',
                                              'sweet', 'rough', 'brave', 'awake']]],
        'hint' => 'Think of the word that means the other way round.',
    ],

    [
        'code' => 'lit-define', 'name' => 'In your own words', 'subject' => 'literacy',
        'level' => 'standard', 'sticker' => 'book',
        'pattern' => 'What does the word "{word}" mean? Explain it in your own words.',
        'answer'  => 'A sensible explanation counts',
        'variables' => ['word' => ['list' => ['courage', 'curious', 'gentle', 'ancient', 'fragile',
                                              'generous', 'stubborn', 'grateful', 'anxious', 'loyal',
                                              'patient', 'honest', 'clumsy', 'enormous', 'silent',
                                              'jealous', 'polite', 'exhausted', 'delicate', 'proud']]],
        'hint' => 'Try using it in a sentence first.',
    ],
    [
        'code' => 'lit-sentence', 'name' => 'Build a sentence', 'subject' => 'literacy',
        'level' => 'standard', 'sticker' => 'star',
        'pattern' => 'Make up a sentence that uses both "{word}" and "{other}".',
        'answer'  => 'Any sentence using both words',
        'variables' => ['word'  => ['list' => ['river', 'castle', 'storm', 'lantern', 'harbour', 'meadow',
                                               'staircase', 'market', 'lighthouse', 'orchard']],
                        'other' => ['list' => ['silent', 'golden', 'sudden', 'enormous', 'frozen', 'crooked',
                                               'forgotten', 'noisy', 'upside-down', 'invisible']]],
        'hint' => 'It can be as silly as you like.',
    ],

    [
        'code' => 'lit-story', 'name' => 'Carry the story on', 'subject' => 'literacy',
        'level' => 'advanced', 'sticker' => 'book',
        'pattern' => 'Tell the next part of the story: "{opening}"',
        'answer'  => 'Any story that follows on',
        'variables' => ['opening' => ['list' => [
            'The door at the top of the stairs had never been open before...',
            'The map showed an island that was not on any other map...',
            'Everyone in the village woke up speaking backwards...',
            'The old lighthouse switched itself back on after twenty years...',
            'A letter arrived addressed to someone who did not live there...',
            'The cat came home wearing a collar nobody had bought...',
            'Every clock in the house stopped at the same minute...',
            'There was a second moon in the sky, and only the children noticed...',
            'The library had a shelf that was never there yesterday...',
            'Footprints came out of the sea and stopped at the front door...',
            'The oldest tree in the park had a door in it that morning...',
            'A parcel arrived with no address and a hole in one side...',
            'The school bell rang an hour early, and nobody had touched it...',
            'Somebody had drawn a map on the last page of the exercise book...',
            'All the birds left town on the same afternoon...',
            'A window that had been painted shut for years swung open...',
        ]]],
        'hint' => 'Two or three sentences is plenty.',
    ],

    // =======================================================================
    //  ENGLISH
    // =======================================================================
    [
        'code' => 'eng-plural', 'name' => 'One and many', 'subject' => 'english',
        'level' => 'beginner', 'sticker' => 'leaf',
        'pattern' => 'What is the plural of "{word}"?',
        'answer'  => 'The correct plural',
        'variables' => ['word' => ['list' => ['child', 'mouse', 'leaf', 'foot', 'box',
                                              'knife', 'goose', 'shelf', 'tooth', 'baby',
                                              'man', 'woman', 'sheep', 'wolf', 'city',
                                              'church', 'half', 'person', 'life', 'potato']]],
        'hint' => 'Some words change more than you expect.',
    ],
    [
        'code' => 'eng-article', 'name' => 'A or an?', 'subject' => 'english',
        'level' => 'beginner', 'sticker' => 'book',
        'pattern' => 'Do you say "a" or "an" before "{word}"?',
        'answer'  => 'The right one, said out loud',
        'variables' => ['word' => ['list' => ['apple', 'book', 'orange', 'tree', 'elephant', 'cup',
                                              'umbrella', 'hat', 'egg', 'island', 'dog', 'hour',
                                              'ant', 'chair', 'owl', 'window']]],
        'hint' => 'Listen to the sound the word starts with.',
    ],
    [
        'code' => 'eng-question', 'name' => 'Make it a question', 'subject' => 'english',
        'level' => 'beginner', 'sticker' => 'bulb',
        'pattern' => 'Turn this into a question: "{sentence}"',
        'answer'  => 'The same words, asked as a question',
        'variables' => ['sentence' => ['list' => ['You are hungry.', 'She can swim.', 'They went home.',
                                                  'It is raining.', 'He has a bike.', 'We are late.',
                                                  'The dog is asleep.', 'You like apples.',
                                                  'It was cold yesterday.', 'They are ready.',
                                                  'She found the key.', 'The bus is coming.',
                                                  'You can hear me.', 'He was at school.',
                                                  'The cake is finished.', 'We have enough.']]],
        'hint' => 'Sometimes you only have to swap the first two words round.',
    ],
    [
        'code' => 'eng-verb', 'name' => 'Yesterday', 'subject' => 'english',
        'level' => 'standard', 'sticker' => 'flag',
        'pattern' => 'Put this into the past tense: "I {verb} every day."',
        'answer'  => 'The correct past tense of "{verb}"',
        'variables' => ['verb' => ['list' => ['run', 'swim', 'eat', 'write', 'sing',
                                              'think', 'bring', 'catch', 'draw', 'fly',
                                              'go', 'take', 'give', 'sleep', 'buy',
                                              'teach', 'ride', 'wear', 'build', 'find']]],
        'hint' => 'Say it as if it already happened.',
    ],
    [
        'code' => 'eng-describe', 'name' => 'Describe it', 'subject' => 'english',
        'level' => 'advanced', 'sticker' => 'bulb',
        'pattern' => 'Describe a {thing} to somebody who has never seen one - without using the word "{thing}".',
        'answer'  => 'Any clear description',
        'variables' => ['thing' => ['list' => ['bicycle', 'umbrella', 'kettle', 'staircase',
                                               'telescope', 'sandcastle', 'windmill', 'kite',
                                               'lighthouse', 'wheelbarrow', 'zip', 'mirror',
                                               'ladder', 'clock', 'sponge', 'whistle',
                                               'shoelace', 'snowman']]],
        'hint' => 'Start with what it is for.',
    ],

    // =======================================================================
    //  SCIENCE
    // =======================================================================
    [
        'code' => 'sci-sense', 'name' => 'Which sense?', 'subject' => 'science',
        'level' => 'beginner', 'sticker' => 'bulb',
        'pattern' => 'Which part of your body do you use to {sense}?',
        'answer'  => 'The matching sense organ',
        'variables' => ['sense' => ['list' => ['smell a flower', 'hear a bell', 'taste honey',
                                               'see a rainbow', 'feel warm sand', 'hear thunder',
                                               'taste a lemon', 'see a star at night', 'smell fresh bread',
                                               'feel a cold window', 'hear your own name', 'taste salt',
                                               'see the colour red', 'feel a cat purring']]],
        'hint' => 'Point to it.',
    ],
    [
        'code' => 'sci-hotcold', 'name' => 'Hot or cold?', 'subject' => 'science',
        'level' => 'beginner', 'sticker' => 'drop',
        'pattern' => 'Is {thing} usually hot or cold?',
        'answer'  => 'Whichever it is, with a reason',
        'variables' => ['thing' => ['list' => ['ice cream', 'soup', 'snow', 'a radiator', 'the sea in winter',
                                               'a cup of tea', 'the inside of a fridge', 'a candle flame',
                                               'sand on a summer beach', 'an ice cube', 'a hot water bottle',
                                               'morning dew', 'an oven', 'a snowball', 'warm milk',
                                               'a freezer', 'a wall in the sunshine', 'water from the cold tap']]],
        'hint' => 'Think about touching it.',
    ],
    [
        'code' => 'sci-living', 'name' => 'Alive or not?', 'subject' => 'science',
        'level' => 'beginner', 'sticker' => 'leaf',
        'pattern' => 'Is {thing} alive? How can you tell?',
        'answer'  => 'The right answer with any sensible reason',
        'variables' => ['thing' => ['list' => ['a tree', 'a rock', 'a cat', 'a cloud', 'a mushroom',
                                               'a bicycle', 'a worm', 'a river', 'a daisy', 'a teddy bear',
                                               'a spider', 'a candle', 'grass', 'a seashell', 'a bee',
                                               'a puddle', 'a seed', 'a toy robot']]],
        'hint' => 'Living things grow, and they need something to keep going.',
    ],
    [
        'code' => 'sci-float', 'name' => 'Float or sink?', 'subject' => 'science',
        'level' => 'standard', 'sticker' => 'drop',
        'pattern' => 'Would a {thing} float or sink in water? Say why you think so.',
        'answer'  => 'Either answer with a reason',
        'variables' => ['thing' => ['list' => ['cork', 'stone', 'apple', 'coin', 'feather',
                                               'sponge', 'nail', 'candle', 'orange', 'wooden spoon',
                                               'grape', 'plastic bottle with the lid on', 'paperclip',
                                               'lemon', 'rubber duck', 'brick', 'pencil', 'marble']]],
        'hint' => 'Think about how heavy it is for its size.',
    ],
    [
        'code' => 'sci-change', 'name' => 'What happens next?', 'subject' => 'science',
        'level' => 'advanced', 'sticker' => 'rocket',
        'pattern' => 'What happens when {event}? Explain as best you can.',
        'answer'  => 'A reasonable explanation',
        'variables' => ['event' => ['list' => [
            'you leave an ice cube in a warm room',
            'a plant is kept in a dark cupboard',
            'you rub your hands together quickly',
            'salt is stirred into a glass of water',
            'a balloon is left in the sun',
            'a puddle sits in the sunshine all morning',
            'you breathe on a cold window',
            'an apple is left cut open on the table',
            'you put a magnet near a pile of paperclips',
            'a bicycle is left out in the rain for a month',
            'you drop a stone and a feather at the same time',
            'a candle is covered with a jar',
            'wet clothes are hung on a line on a windy day',
            'you shake a bottle of water and oil together',
            'a seed is planted and watered every day',
        ]]],
        'hint' => 'Say what you would see, then why.',
    ],

    // =======================================================================
    //  NATURE
    // =======================================================================
    [
        'code' => 'nature-animal', 'name' => 'Animal sounds', 'subject' => 'nature',
        'level' => 'beginner', 'sticker' => 'heart',
        'pattern' => 'What sound does a {animal} make? Do your best impression!',
        'answer'  => 'Any good attempt counts',
        'variables' => ['animal' => ['list' => ['cow', 'duck', 'lion', 'sheep', 'owl', 'frog',
                                                'horse', 'bee', 'cat', 'wolf', 'goat', 'crow',
                                                'pig', 'donkey', 'hen', 'mouse', 'snake', 'elephant',
                                                'dog', 'seagull', 'monkey', 'cricket']]],
        'hint' => 'Nobody is marking you on this one.',
    ],
    [
        'code' => 'nature-home', 'name' => 'Where does it live?', 'subject' => 'nature',
        'level' => 'beginner', 'sticker' => 'leaf',
        'pattern' => 'Where does a {animal} live?',
        'answer'  => 'The right kind of home',
        'variables' => ['animal' => ['list' => ['bee', 'rabbit', 'penguin', 'camel', 'fish',
                                                'owl', 'mole', 'crab', 'bat', 'squirrel',
                                                'polar bear', 'kangaroo', 'spider', 'beaver', 'ant',
                                                'swallow', 'tortoise', 'badger', 'dolphin', 'hedgehog']]],
        'hint' => 'Think about what it needs to stay safe.',
    ],
    [
        'code' => 'nature-baby', 'name' => 'Baby animals', 'subject' => 'nature',
        'level' => 'beginner', 'sticker' => 'heart',
        'pattern' => 'What do we call a baby {animal}?',
        'answer'  => 'The right name for the young one',
        'variables' => ['animal' => ['list' => ['cat', 'dog', 'cow', 'sheep', 'duck', 'horse',
                                                'frog', 'bear', 'goat', 'hen', 'pig', 'swan',
                                                'deer', 'kangaroo', 'butterfly', 'owl']]],
        'hint' => 'Some have a special name, some are just "a baby".',
    ],
    [
        'code' => 'nature-need', 'name' => 'What does it need?', 'subject' => 'nature',
        'level' => 'standard', 'sticker' => 'drop',
        'pattern' => 'Name two things {living} needs to stay alive.',
        'answer'  => 'Any two sensible needs',
        'variables' => ['living' => ['list' => ['a tree', 'a dog', 'a fish', 'a bee', 'a person',
                                                'a plant in a pot', 'a bird', 'a worm', 'a horse',
                                                'a cat', 'a sunflower', 'a frog', 'a rabbit',
                                                'a mushroom']]],
        'hint' => 'Food and water are two - what else?',
    ],
    [
        'code' => 'nature-season', 'name' => 'Seasons', 'subject' => 'nature',
        'level' => 'standard', 'sticker' => 'sun',
        'pattern' => 'Name two things that happen in {season}. Look {aspect}.',
        'answer'  => 'Any two sensible answers',
        'variables' => ['season' => ['list' => ['spring', 'summer', 'autumn', 'winter']],
                        'aspect' => ['list' => ['to the weather', 'to the trees', 'to the animals',
                                                'to what people wear', 'in the garden']]],
        'hint' => 'Think about the weather, and about plants.',
    ],
    [
        'code' => 'nature-chain', 'name' => 'Who eats what', 'subject' => 'nature',
        'level' => 'advanced', 'sticker' => 'leaf',
        'pattern' => 'What might a {animal} eat, and what might eat a {animal}?',
        'answer'  => 'A sensible food chain',
        'variables' => ['animal' => ['list' => ['mouse', 'frog', 'rabbit', 'fish', 'caterpillar', 'sparrow',
                                                'worm', 'snail', 'grasshopper', 'duckling', 'squirrel',
                                                'ladybird', 'shrimp', 'field vole', 'young owl', 'tadpole']]],
        'hint' => 'Every animal is somebody\'s dinner.',
    ],

    // =======================================================================
    //  LOGIC
    // =======================================================================
    [
        'code' => 'logic-odd', 'name' => 'Odd one out', 'subject' => 'logic',
        'level' => 'beginner', 'sticker' => 'key',
        'pattern' => 'Which is the odd one out: {set}? Say why.',
        'answer'  => 'Any answer with a good reason',
        'variables' => ['set' => ['list' => [
            'apple, banana, carrot, pear',
            'dog, cat, fish, rabbit',
            'red, blue, square, green',
            'shoe, sock, hat, spoon',
            'car, boat, bicycle, tree',
            'spoon, fork, knife, pencil',
            'rain, snow, fog, mountain',
            'two, four, seven, six',
            'guitar, drum, painting, piano',
            'monday, tuesday, july, friday',
            'chair, table, cloud, bed',
            'lion, tiger, cow, leopard',
            'eye, ear, nose, glove',
            'river, lake, sea, desert',
            'football, tennis, chess, swimming',
            'oak, pine, rose, birch',
            'hammer, saw, apple, screwdriver',
            'circle, triangle, red, square',
        ]]],
        'hint' => 'There can be more than one right answer.',
    ],
    [
        'code' => 'logic-same', 'name' => 'What is the same?', 'subject' => 'logic',
        'level' => 'beginner', 'sticker' => 'gem',
        'pattern' => 'What do {pair} have in common?',
        'answer'  => 'Any sensible thing they share',
        'variables' => ['pair' => ['list' => ['a bicycle and a car', 'an apple and a banana',
                                              'a dog and a wolf', 'rain and snow', 'a chair and a bed',
                                              'a spoon and a fork', 'the sun and a lamp',
                                              'a book and a newspaper', 'a river and a lake',
                                              'shoes and gloves', 'a piano and a guitar',
                                              'a tree and a flower', 'an aeroplane and a bird',
                                              'a clock and a calendar', 'a knife and a saw',
                                              'a boat and a duck']]],
        'hint' => 'Think about what they are for, or what they are made of.',
    ],
    [
        'code' => 'logic-order', 'name' => 'Smallest first', 'subject' => 'logic',
        'level' => 'beginner', 'sticker' => 'footprint',
        'pattern' => 'Put these in order, smallest first: {set}.',
        'answer'  => 'The three in the right order',
        'variables' => ['set' => ['list' => ['an ant, a dog, an elephant', 'a cup, a bucket, a bath',
                                             'a minute, an hour, a day', 'a pebble, a rock, a mountain',
                                             'a seed, a flower, a tree', 'a shoe, a car, a house',
                                             'a drop, a puddle, a lake', 'a coin, a plate, a table',
                                             'a mouse, a cat, a horse', 'a leaf, a branch, a trunk',
                                             'a step, a street, a country', 'a spoon, a shovel, a digger',
                                             'a baby, a child, a grown-up', 'a button, a plate, a wheel',
                                             'a candle, a lamp post, a tower',
                                             'a snowflake, a snowball, a snowman']]],
        'hint' => 'Picture them side by side.',
    ],
    [
        'code' => 'logic-truefalse', 'name' => 'True or false?', 'subject' => 'logic',
        'level' => 'standard', 'sticker' => 'flag',
        'pattern' => 'True or false: {claim}? Say why.',
        'answer'  => 'The right answer with a reason',
        'variables' => ['claim' => ['list' => ['all birds can fly', 'every square is also a rectangle',
                                               'all fish live in water', 'all spiders have six legs',
                                               'the sun rises in the west', 'some cats have no tail',
                                               'every triangle has three sides', 'ice is heavier than water',
                                               'every month has thirty days', 'all plants have flowers',
                                               'a whale is a fish', 'no number is both even and odd']]],
        'hint' => 'One example that does not fit is enough to make it false.',
    ],
    [
        'code' => 'logic-seq', 'name' => 'What comes next?', 'subject' => 'logic',
        'level' => 'standard', 'sticker' => 'key',
        'pattern' => 'What comes next: {a}, {b}, {c}, ... ?',
        'answer'  => 'The number that continues the pattern',
        'variables' => ['a' => ['min' => 2, 'max' => 6], 'b' => ['min' => 8, 'max' => 12],
                        'c' => ['min' => 14, 'max' => 20]],
        'hint' => 'Work out the step between them.',
    ],
    [
        'code' => 'logic-riddle', 'name' => 'Riddle', 'subject' => 'logic',
        'level' => 'advanced', 'sticker' => 'bulb',
        'pattern' => '{riddle}',
        'answer'  => 'The riddle\'s answer',
        'variables' => ['riddle' => ['list' => [
            'I have hands but cannot clap. What am I?',
            'I get wetter the more I dry. What am I?',
            'I have keys but open no locks. What am I?',
            'The more you take of me, the more you leave behind. What am I?',
            'I go up but never come down. What am I?',
            'I have a face and two hands but no arms or legs. What am I?',
            'I am full of holes but still hold water. What am I?',
            'I follow you all day and disappear at night. What am I?',
            'I have a neck but no head. What am I?',
            'The more of me there is, the less you see. What am I?',
            'I have teeth but cannot eat. What am I?',
            'I am tall when I am young and short when I am old. What am I?',
            'I have branches but no leaves, no trunk and no fruit. What am I?',
            'You can catch me but not throw me. What am I?',
            'I come down but never go up. What am I?',
            'I have a bed but never sleep, and a mouth but never eat. What am I?',
            'I have an eye but cannot see. What am I?',
            'What has to be broken before you can use it?',
        ]]],
        'hint' => 'Read it twice - the trick is in the wording.',
    ],

    // =======================================================================
    //  LIFE SKILLS
    // =======================================================================
    [
        'code' => 'life-kind', 'name' => 'A kind thing', 'subject' => 'life',
        'level' => 'beginner', 'sticker' => 'heart',
        'pattern' => 'Name one kind thing you could do for {who} today.',
        'answer'  => 'Any kind idea counts',
        'variables' => ['who' => ['list' => ['a friend', 'someone in your family', 'a neighbour',
                                             'a new person at school', 'someone feeling sad',
                                             'a younger child', 'somebody who helped you last week',
                                             'a teacher', 'someone eating on their own',
                                             'a grandparent', 'somebody who is unwell',
                                             'the person sitting next to you', 'a person with their hands full',
                                             'someone who lost a game', 'somebody you had an argument with',
                                             'a person who is new to the country']]],
        'hint' => 'Small things count too.',
    ],
    [
        'code' => 'life-tidy', 'name' => 'Where does it belong?', 'subject' => 'life',
        'level' => 'beginner', 'sticker' => 'key',
        'pattern' => 'Where does {thing} belong when you tidy up?',
        'answer'  => 'Any sensible place',
        'variables' => ['thing' => ['list' => ['your shoes', 'a dirty plate', 'a library book',
                                               'your coat', 'the rubbish', 'a toy car', 'a wet towel',
                                               'dirty socks', 'the milk', 'a pencil', 'your school bag',
                                               'an empty bottle', 'an apple core', 'clean clothes',
                                               'muddy boots', 'a pair of scissors']]],
        'hint' => 'Somewhere you would look for it next time.',
    ],
    [
        'code' => 'life-before', 'name' => 'What comes first?', 'subject' => 'life',
        'level' => 'standard', 'sticker' => 'footprint',
        'pattern' => 'Name two things you need to do before {activity}.',
        'answer'  => 'Any two sensible steps',
        'variables' => ['activity' => ['list' => ['going swimming', 'cooking a meal', 'riding your bike',
                                                  'leaving for school', 'having friends over',
                                                  'going on a long walk', 'planting seeds',
                                                  'taking a bus on your own', 'starting your homework',
                                                  'going to bed', 'feeding a pet', 'packing for a trip']]],
        'hint' => 'Think about what would go wrong if you forgot.',
    ],
    [
        'code' => 'life-safe', 'name' => 'Staying safe', 'subject' => 'life',
        'level' => 'standard', 'sticker' => 'flag',
        'pattern' => 'What should you do if {situation}?',
        'answer'  => 'Any sensible, safe answer',
        'variables' => ['situation' => ['list' => [
            'you get separated from your grown-up in a shop',
            'a stranger asks you to go with them',
            'you smell burning at home',
            'you see someone being hurt',
            'you feel unwell at school',
            'you cut your finger and it will not stop bleeding',
            'the fire alarm goes off while you are upstairs',
            'somebody online asks where you live',
            'you find a bottle of pills on the floor',
            'your ball rolls into the road',
            'you are cycling and your brakes stop working',
            'a dog you do not know runs at you',
            'you get lost on the way home',
            'someone keeps sending you messages that upset you',
            'you are the first to find somebody who has fallen over',
        ]]],
        'hint' => 'Finding a trusted adult is usually the first step.',
    ],
    [
        'code' => 'life-choice', 'name' => 'What would you do?', 'subject' => 'life',
        'level' => 'advanced', 'sticker' => 'trophy',
        'pattern' => 'What would you do if {situation}?',
        'answer'  => 'There is no single right answer - just be kind',
        'variables' => ['situation' => ['list' => [
            'a friend takes the blame for something you did',
            'you forgot to bring your homework',
            'you found something that belongs to someone else',
            'you promised two people the same afternoon',
            'somebody copied your work and was praised for it',
            'you broke something and nobody saw',
            'you were given too much change in a shop',
            'your team wants to leave somebody out of the game',
            'a friend tells you a secret that worries you',
            'you are winning and your friend wants to give up',
            'somebody laughs at the way another child speaks',
            'you are asked a question and you do not know the answer',
            'a friend wants to copy your homework',
            'you accidentally hurt someone while playing',
            'you are given a present you do not like',
            'you see somebody drop money without noticing',
        ]]],
        'hint' => 'Say what you would do, and why.',
    ],

    // =======================================================================
    //  GEOGRAPHY
    // =======================================================================
    [
        'code' => 'geo-where', 'name' => 'Near and far', 'subject' => 'geography',
        'level' => 'beginner', 'sticker' => 'flag',
        'pattern' => 'Would you find {thing} near your home, or far away?',
        'answer'  => 'Either, with a reason',
        'variables' => ['thing' => ['list' => ['a mountain', 'a beach', 'a river', 'a desert',
                                               'a forest', 'a harbour', 'a volcano', 'a farm',
                                               'a railway station', 'a glacier', 'a lake', 'an island',
                                               'a canal', 'a rainforest', 'a waterfall', 'a cave',
                                               'a bridge over a valley', 'a field of wheat']]],
        'hint' => 'Think about what is around where you live.',
    ],
    [
        'code' => 'geo-hotcold', 'name' => 'Hot place or cold place?', 'subject' => 'geography',
        'level' => 'beginner', 'sticker' => 'sun',
        'pattern' => 'Would you need {thing} somewhere hot or somewhere cold?',
        'answer'  => 'Whichever it is, with a reason',
        'variables' => ['thing' => ['list' => ['a woolly hat', 'sunglasses', 'a scarf', 'sandals',
                                               'a thick coat', 'a sun hat', 'gloves', 'a fan',
                                               'snow boots', 'a swimming costume', 'a warm blanket',
                                               'shorts', 'a hot drink', 'ice skates', 'a cold drink',
                                               'sun cream']]],
        'hint' => 'Think about what you wear on the coldest day of the year.',
    ],
    [
        'code' => 'geo-travel', 'name' => 'How would you get there?', 'subject' => 'geography',
        'level' => 'beginner', 'sticker' => 'rocket',
        'pattern' => 'How would you travel to {place}?',
        'answer'  => 'Any sensible way of travelling',
        'variables' => ['place' => ['list' => ['an island out at sea', 'the top of a mountain',
                                               'the shop at the end of the road', 'a country far away',
                                               'a farm across the fields', 'the middle of a big lake',
                                               'a town on the other side of a river', 'the moon',
                                               'a village up a steep hill', 'the beach', 'a cave',
                                               'the middle of a forest', 'a big city',
                                               'a lighthouse on the rocks', 'the next street', 'an airport']]],
        'hint' => 'Some places need more than one kind of journey.',
    ],
    [
        'code' => 'geo-difference', 'name' => 'What is the difference?', 'subject' => 'geography',
        'level' => 'standard', 'sticker' => 'key',
        'pattern' => 'What is the difference between {pair}?',
        'answer'  => 'Any clear difference',
        'variables' => ['pair' => ['list' => ['a lake and a sea', 'a hill and a mountain',
                                              'a village and a city', 'a river and a canal',
                                              'an island and a peninsula', 'a wood and a forest',
                                              'a road and a motorway', 'a stream and a river',
                                              'a beach and a cliff', 'a farm and a field',
                                              'a map and a globe', 'a country and a continent']]],
        'hint' => 'Size is one answer, but not the only one.',
    ],
    [
        'code' => 'geo-direction', 'name' => 'Which way?', 'subject' => 'geography',
        'level' => 'standard', 'sticker' => 'footprint',
        'pattern' => 'If you face {direction} and turn {turn}, which way are you facing now?',
        'answer'  => 'The direction {turn} of {direction}',
        'variables' => ['direction' => ['list' => ['north', 'south', 'east', 'west']],
                        'turn'      => ['list' => ['right', 'left', 'right twice', 'all the way round']]],
        'hint' => 'Picture a compass, or use your hands.',
    ],
    [
        'code' => 'geo-place', 'name' => 'Places on Earth', 'subject' => 'geography',
        'level' => 'advanced', 'sticker' => 'gem',
        'pattern' => 'Name a country where you would expect to find {feature}, and say why.',
        'answer'  => 'Any country that fits, with a reason',
        'variables' => ['feature' => ['list' => ['a rainforest', 'a desert', 'snow all year round',
                                                 'active volcanoes', 'coral reefs', 'very long rivers',
                                                 'penguins in the wild', 'olive groves', 'tea growing on hills',
                                                 'reindeer herders', 'high mountains with climbers',
                                                 'canals instead of roads', 'wild elephants', 'fjords',
                                                 'a windmill in every field', 'a very long wall']]],
        'hint' => 'Think about how hot or cold it is there.',
    ],

    // =======================================================================
    //  THE FIRST FIVE, WHICH ONLY EXISTED IN THE DATABASE UNTIL NOW
    // =======================================================================
    [
        'code' => 'life-action', 'name' => 'Do it now', 'subject' => 'life',
        'level' => 'beginner', 'sticker' => 'sun',
        'pattern' => 'Try to {action} for {n} seconds. Manage it and you carry on!',
        'answer'  => 'Complete the action',
        'variables' => ['action' => ['list' => ['hop on one foot', 'stand on one leg',
                                                'clap as fast as you can', 'spin around slowly',
                                                'laugh out loud', 'pretend to be a cat',
                                                'balance a book on your head', 'walk backwards',
                                                'touch your toes', 'stand as still as a statue',
                                                'talk without using the letter S', 'march on the spot']],
                        'n' => ['min' => 5, 'max' => 15, 'step' => 5]],
        'hint' => 'Everybody counts out loud together.',
    ],
    [
        'code' => 'life-team', 'name' => 'What would you do?', 'subject' => 'life',
        'level' => 'advanced', 'sticker' => 'rocket',
        'pattern' => 'What would you do if {situation}? Tell everyone one way to handle it.',
        'answer'  => 'Any thoughtful answer counts',
        'variables' => ['situation' => ['list' => ['a friend fell over in the playground',
                                                   'your group could not agree on anything',
                                                   'you spilled water all over the table',
                                                   'you saw someone sitting on their own',
                                                   'somebody was left out of a game',
                                                   'two friends both wanted to go first',
                                                   'the rules were not clear and an argument started',
                                                   'somebody kept interrupting everyone else']]],
        'hint' => 'Say what you would try first.',
    ],
    [
        'code' => 'en-word', 'name' => 'Adventure words', 'subject' => 'english',
        'level' => 'standard', 'sticker' => 'bulb',
        'pattern' => 'What does the word "{word}" mean? Explain it in your own words.',
        'answer'  => 'A sensible explanation counts',
        'variables' => ['word' => ['list' => ['forest', 'river', 'mountain', 'treasure', 'bridge',
                                              'castle', 'dragon', 'compass', 'island', 'journey',
                                              'courage', 'friendship', 'harbour', 'lantern',
                                              'shipwreck', 'map']]],
        'hint' => 'Use it in a sentence about your game.',
    ],
    [
        'code' => 'science-why', 'name' => 'Why does that happen?', 'subject' => 'science',
        'level' => 'standard', 'sticker' => 'drop',
        'pattern' => 'Why {phenomenon}?',
        'answer'  => 'Any reasonable explanation counts',
        'variables' => ['phenomenon' => ['list' => ['does it rain', 'do rainbows appear after rain',
                                                    'does ice melt when you leave it out',
                                                    'do leaves change colour in autumn',
                                                    'can we see stars at night',
                                                    'do balloons float when filled with helium',
                                                    'are shadows longer in the afternoon',
                                                    'do we shiver when we are cold',
                                                    'does bread go hard when left out',
                                                    'do boats float',
                                                    'does the moon change shape',
                                                    'do we need to sleep']]],
        'hint' => 'Say what you have noticed first, then why you think it happens.',
    ],
    [
        'code' => 'geo-continent', 'name' => 'Which continent?', 'subject' => 'geography',
        'level' => 'advanced', 'sticker' => 'flag',
        'pattern' => 'Which continent is {place} in?',
        'answer'  => 'The correct continent',
        'variables' => ['place' => ['list' => ['Egypt', 'Brazil', 'Japan', 'Italy', 'Kenya',
                                               'Canada', 'India', 'Norway', 'Peru', 'Vietnam',
                                               'Australia', 'Mexico', 'Spain', 'China',
                                               'Morocco', 'Argentina']]],
        'hint' => 'There are seven to choose from.',
    ],
];
